In [1]:
import time

from nba_api.stats.static import players,teams

from nba_api.stats.endpoints import playercareerstats
import json

from pyspark.sql.types import DateType, BinaryType, IntegerType, StringType

In [2]:
import json

all_players = players.get_players()
count = 0
for p in all_players:
    print(p)
    count+=1
print(count)

{'id': 76001, 'full_name': 'Alaa Abdelnaby', 'first_name': 'Alaa', 'last_name': 'Abdelnaby', 'is_active': False}
{'id': 76002, 'full_name': 'Zaid Abdul-Aziz', 'first_name': 'Zaid', 'last_name': 'Abdul-Aziz', 'is_active': False}
{'id': 76003, 'full_name': 'Kareem Abdul-Jabbar', 'first_name': 'Kareem', 'last_name': 'Abdul-Jabbar', 'is_active': False}
{'id': 51, 'full_name': 'Mahmoud Abdul-Rauf', 'first_name': 'Mahmoud', 'last_name': 'Abdul-Rauf', 'is_active': False}
{'id': 1505, 'full_name': 'Tariq Abdul-Wahad', 'first_name': 'Tariq', 'last_name': 'Abdul-Wahad', 'is_active': False}
{'id': 949, 'full_name': 'Shareef Abdur-Rahim', 'first_name': 'Shareef', 'last_name': 'Abdur-Rahim', 'is_active': False}
{'id': 76005, 'full_name': 'Tom Abernethy', 'first_name': 'Tom', 'last_name': 'Abernethy', 'is_active': False}
{'id': 76006, 'full_name': 'Forest Able', 'first_name': 'Forest', 'last_name': 'Able', 'is_active': False}
{'id': 76007, 'full_name': 'John Abramovic', 'first_name': 'John', 'last_name': 'Abramovic', 'is_active': False}
{'id': 203518, 'full_name': 'Alex Abrines', 'first_name': 'Alex', 'last_name': 'Abrines', 'is_active': False}
{'id': 1630173, 'full_name': 'Precious Achiuwa', 'first_name': 'Precious', 'last_name': 'Achiuwa', 'is_active': True}
{'id': 101165, 'full_name': 'Alex Acker', 'first_name': 'Alex', 'last_name': 'Acker', 'is_active': False}
{'id': 76008, 'full_name': 'Donald Ackerman', 'first_name': 'Donald', 'last_name': 'Ackerman', 'is_active': False}
{'id': 76009, 'full_name': 'Mark Acres', 'first_name': 'Mark', 'last_name': 'Acres', 'is_active': False}
{'id': 76010, 'full_name': 'Charles Acton', 'first_name': 'Charles', 'last_name': 'Acton', 'is_active': False}
{'id': 203112, 'full_name': 'Quincy Acy', 'first_name': 'Quincy', 'last_name': 'Acy', 'is_active': False}
{'id': 76011, 'full_name': 'Alvan Adams', 'first_name': 'Alvan', 'last_name': 'Adams', 'is_active': False}
{'id': 76012, 'full_name': 'Don Adams', 'first_name': 'Don', 'last_name': 'Adams', 'is_active': False}
{'id': 200801, 'full_name': 'Hassan Adams', 'first_name': 'Hassan', 'last_name': 'Adams', 'is_active': False}
{'id': 1629121, 'full_name': 'Jaylen Adams', 'first_name': 'Jaylen', 'last_name': 'Adams', 'is_active': False}
{'id': 203919, 'full_name': 'Jordan Adams', 'first_name': 'Jordan', 'last_name': 'Adams', 'is_active': False}
{'id': 149, 'full_name': 'Michael Adams', 'first_name': 'Michael', 'last_name': 'Adams', 'is_active': False}
{'id': 203500, 'full_name': 'Steven Adams', 'first_name': 'Steven', 'last_name': 'Adams', 'is_active': True}
{'id': 912, 'full_name': 'Rafael Addison', 'first_name': 'Rafael', 'last_name': 'Addison', 'is_active': False}
{'id': 1628389, 'full_name': 'Bam Adebayo', 'first_name': 'Bam', 'last_name': 'Adebayo', 'is_active': True}
{'id': 1629061, 'full_name': 'Deng Adel', 'first_name': 'Deng', 'last_name': 'Adel', 'is_active': False}
{'id': 76015, 'full_name': 'Rick Adelman', 'first_name': 'Rick', 'last_name': 'Adelman', 'is_active': False}
{'id': 202399, 'full_name': 'Jeff Adrien', 'first_name': 'Jeff', 'last_name': 'Adrien', 'is_active': False}
{'id': 201167, 'full_name': 'Arron Afflalo', 'first_name': 'Arron', 'last_name': 'Afflalo', 'is_active': False}
{'id': 1630534, 'full_name': 'Ochai Agbaji', 'first_name': 'Ochai', 'last_name': 'Agbaji', 'is_active': True}
{'id': 200772, 'full_name': 'Maurice Ager', 'first_name': 'Maurice', 'last_name': 'Ager', 'is_active': False}
{'id': 76016, 'full_name': 'Mark Aguirre', 'first_name': 'Mark', 'last_name': 'Aguirre', 'is_active': False}
{'id': 201336, 'full_name': 'Blake Ahearn', 'first_name': 'Blake', 'last_name': 'Ahearn', 'is_active': False}
{'id': 76017, 'full_name': 'Danny Ainge', 'first_name': 'Danny', 'last_name': 'Ainge', 'is_active': False}
{'id': 201582, 'full_name': 'Alexis Ajinca', 'first_name': 'Alexis', 'last_name': 'Ajinca', 'is_active': False}
{'id': 76018, 'full_name': 'Henry Akin', 'first_name': 'Henry', 'last_name': 'Akin', 'is_active': False}
{'id': 203006, 'full_name': 'Josh Akognon', 'first_name': 'Josh', 'last_name': 'Akognon', 'is_active': False}
{'id': 1629152, 'full_name': 'DeVaughn Akoon-Purcell', 'first_name': 'DeVaughn', 'last_name': 'Akoon-Purcell', 'is_active': False}
{'id': 202374, 'full_name': 'Solomon Alabi', 'first_name': 'Solomon', 'last_name': 'Alabi', 'is_active': False}
{'id': 76019, 'full_name': 'Mark Alarie', 'first_name': 'Mark', 'last_name': 'Alarie', 'is_active': False}
{'id': 76020, 'full_name': 'Gary Alcorn', 'first_name': 'Gary', 'last_name': 'Alcorn', 'is_active': False}
{'id': 1630583, 'full_name': 'Santi Aldama', 'first_name': 'Santi', 'last_name': 'Aldama', 'is_active': True}
{'id': 203128, 'full_name': 'Furkan Aldemir', 'first_name': 'Furkan', 'last_name': 'Aldemir', 'is_active': False}
{'id': 202332, 'full_name': 'Cole Aldrich', 'first_name': 'Cole', 'last_name': 'Aldrich', 'is_active': False}
{'id': 200746, 'full_name': 'LaMarcus Aldridge', 'first_name': 'LaMarcus', 'last_name': 'Aldridge', 'is_active': False}
{'id': 76021, 'full_name': 'Chuck Aleksinas', 'first_name': 'Chuck', 'last_name': 'Aleksinas', 'is_active': False}
{'id': 1626146, 'full_name': 'Cliff Alexander', 'first_name': 'Cliff', 'last_name': 'Alexander', 'is_active': False}
{'id': 724, 'full_name': 'Cory Alexander', 'first_name': 'Cory', 'last_name': 'Alexander', 'is_active': False}
{'id': 2042, 'full_name': 'Courtney Alexander', 'first_name': 'Courtney', 'last_name': 'Alexander', 'is_active': False}
{'id': 76022, 'full_name': 'Gary Alexander', 'first_name': 'Gary', 'last_name': 'Alexander', 'is_active': False}
{'id': 201570, 'full_name': 'Joe Alexander', 'first_name': 'Joe', 'last_name': 'Alexander', 'is_active': False}
{'id': 1629734, 'full_name': 'Kyle Alexander', 'first_name': 'Kyle', 'last_name': 'Alexander', 'is_active': False}
{'id': 1641725, 'full_name': 'Trey Alexander', 'first_name': 'Trey', 'last_name': 'Alexander', 'is_active': True}
{'id': 1630234, 'full_name': 'Ty-Shon Alexander', 'first_name': 'Ty-Shon', 'last_name': 'Alexander', 'is_active': False}
{'id': 2349, 'full_name': 'Victor Alexander', 'first_name': 'Victor', 'last_name': 'Alexander', 'is_active': False}
{'id': 1629638, 'full_name': 'Nickeil Alexander-Walker', 'first_name': 'Nickeil', 'last_name': 'Alexander-Walker', 'is_active': True}
{'id': 76024, 'full_name': 'Steve Alford', 'first_name': 'Steve', 'last_name': 'Alford', 'is_active': False}
{'id': 1628959, 'full_name': 'Rawle Alkins', 'first_name': 'Rawle', 'last_name': 'Alkins', 'is_active': False}
{'id': 76028, 'full_name': 'Bob Allen', 'first_name': 'Bob', 'last_name': 'Allen', 'is_active': False}
{'id': 1628960, 'full_name': 'Grayson Allen', 'first_name': 'Grayson', 'last_name': 'Allen', 'is_active': True}
{'id': 1628386, 'full_name': 'Jarrett Allen', 'first_name': 'Jarrett', 'last_name': 'Allen', 'is_active': True}
{'id': 706, 'full_name': 'Jerome Allen', 'first_name': 'Jerome', 'last_name': 'Allen', 'is_active': False}
{'id': 1628443, 'full_name': 'Kadeem Allen', 'first_name': 'Kadeem', 'last_name': 'Allen', 'is_active': False}
{'id': 202730, 'full_name': 'Lavoy Allen', 'first_name': 'Lavoy', 'last_name': 'Allen', 'is_active': False}
{'id': 76027, 'full_name': 'Lucius Allen', 'first_name': 'Lucius', 'last_name': 'Allen', 'is_active': False}
{'id': 2124, 'full_name': 'Malik Allen', 'first_name': 'Malik', 'last_name': 'Allen', 'is_active': False}
{'id': 76025, 'full_name': 'Randy Allen', 'first_name': 'Randy', 'last_name': 'Allen', 'is_active': False}
{'id': 951, 'full_name': 'Ray Allen', 'first_name': 'Ray', 'last_name': 'Allen', 'is_active': False}
{'id': 1641851, 'full_name': 'Timmy Allen', 'first_name': 'Timmy', 'last_name': 'Allen', 'is_active': False}
{'id': 2754, 'full_name': 'Tony Allen', 'first_name': 'Tony', 'last_name': 'Allen', 'is_active': False}
{'id': 76029, 'full_name': 'Odis Allison', 'first_name': 'Odis', 'last_name': 'Allison', 'is_active': False}
{'id': 200984, 'full_name': 'Lance Allred', 'first_name': 'Lance', 'last_name': 'Allred', 'is_active': False}
{'id': 76030, 'full_name': 'Darrell Allums', 'first_name': 'Darrell', 'last_name': 'Allums', 'is_active': False}
{'id': 201165, 'full_name': 'Morris Almond', 'first_name': 'Morris', 'last_name': 'Almond', 'is_active': False}
{'id': 308, 'full_name': 'Derrick Alston', 'first_name': 'Derrick', 'last_name': 'Alston', 'is_active': False}
{'id': 1747, 'full_name': 'Rafer Alston', 'first_name': 'Rafer', 'last_name': 'Alston', 'is_active': False}
{'id': 1824, 'full_name': 'Peter Aluma', 'first_name': 'Peter', 'last_name': 'Aluma', 'is_active': False}
{'id': 1630631, 'full_name': 'Jose Alvarado', 'first_name': 'Jose', 'last_name': 'Alvarado', 'is_active': True}
{'id': 680, 'full_name': 'John Amaechi', 'first_name': 'John', 'last_name': 'Amaechi', 'is_active': False}
{'id': 732, 'full_name': 'Ashraf Amaya', 'first_name': 'Ashraf', 'last_name': 'Amaya', 'is_active': False}
{'id': 202329, 'full_name': 'Al-Farouq Aminu', 'first_name': 'Al-Farouq', 'last_name': 'Aminu', 'is_active': False}
{'id': 200811, 'full_name': 'Lou Amundson', 'first_name': 'Lou', 'last_name': 'Amundson', 'is_active': False}
{'id': 76034, 'full_name': 'Bob Anderegg', 'first_name': 'Bob', 'last_name': 'Anderegg', 'is_active': False}
{'id': 2365, 'full_name': 'Chris Andersen', 'first_name': 'Chris', 'last_name': 'Andersen', 'is_active': False}
{'id': 2431, 'full_name': 'David Andersen', 'first_name': 'David', 'last_name': 'Andersen', 'is_active': False}
{'id': 101187, 'full_name': 'Alan Anderson', 'first_name': 'Alan', 'last_name': 'Anderson', 'is_active': False}
{'id': 202079, 'full_name': 'Antonio Anderson', 'first_name': 'Antonio', 'last_name': 'Anderson', 'is_active': False}
{'id': 76035, 'full_name': 'Cliff Anderson', 'first_name': 'Cliff', 'last_name': 'Anderson', 'is_active': False}
{'id': 76036, 'full_name': 'Daniel Anderson', 'first_name': 'Daniel', 'last_name': 'Anderson', 'is_active': False}
{'id': 1507, 'full_name': 'Derek Anderson', 'first_name': 'Derek', 'last_name': 'Anderson', 'is_active': False}
{'id': 76037, 'full_name': 'Dwight Anderson', 'first_name': 'Dwight', 'last_name': 'Anderson', 'is_active': False}
{'id': 944, 'full_name': 'Eric Anderson', 'first_name': 'Eric', 'last_name': 'Anderson', 'is_active': False}
{'id': 246, 'full_name': 'Greg Anderson', 'first_name': 'Greg', 'last_name': 'Anderson', 'is_active': False}
{'id': 202341, 'full_name': 'James Anderson', 'first_name': 'James', 'last_name': 'Anderson', 'is_active': False}
{'id': 76040, 'full_name': 'Jerome Anderson', 'first_name': 'Jerome', 'last_name': 'Anderson', 'is_active': False}
{'id': 1626147, 'full_name': 'Justin Anderson', 'first_name': 'Justin', 'last_name': 'Anderson', 'is_active': False}
{'id': 72, 'full_name': 'Kenny Anderson', 'first_name': 'Kenny', 'last_name': 'Anderson', 'is_active': False}
{'id': 76041, 'full_name': 'Kim Anderson', 'first_name': 'Kim', 'last_name': 'Anderson', 'is_active': False}
{'id': 203937, 'full_name': 'Kyle Anderson', 'first_name': 'Kyle', 'last_name': 'Anderson', 'is_active': True}
{'id': 76042, 'full_name': 'Michael Anderson', 'first_name': 'Michael', 'last_name': 'Anderson', 'is_active': False}
{'id': 76043, 'full_name': 'Mitchell Anderson', 'first_name': 'Mitchell', 'last_name': 'Anderson', 'is_active': False}
{'id': 98, 'full_name': 'Nick Anderson', 'first_name': 'Nick', 'last_name': 'Anderson', 'is_active': False}
{'id': 76045, 'full_name': 'Richard Anderson', 'first_name': 'Richard', 'last_name': 'Anderson', 'is_active': False}
{'id': 76046, 'full_name': 'Ron Anderson', 'first_name': 'Ron', 'last_name': 'Anderson', 'is_active': False}
{'id': 201583, 'full_name': 'Ryan Anderson', 'first_name': 'Ryan', 'last_name': 'Anderson', 'is_active': False}
{'id': 1000, 'full_name': 'Shandon Anderson', 'first_name': 'Shandon', 'last_name': 'Anderson', 'is_active': False}
{'id': 335, 'full_name': 'Willie Anderson', 'first_name': 'Willie', 'last_name': 'Anderson', 'is_active': False}
{'id': 76048, 'full_name': 'Wally Anderzunas', 'first_name': 'Wally', 'last_name': 'Anderzunas', 'is_active': False}
{'id': 101149, 'full_name': 'Martynas Andriuskevicius', 'first_name': 'Martynas', 'last_name': 'Andriuskevicius', 'is_active': False}
{'id': 76049, 'full_name': 'Don Anielak', 'first_name': 'Don', 'last_name': 'Anielak', 'is_active': False}
{'id': 1628387, 'full_name': 'Ike Anigbogu', 'first_name': 'Ike', 'last_name': 'Anigbogu', 'is_active': False}
{'id': 76050, 'full_name': 'Michael Ansley', 'first_name': 'Michael', 'last_name': 'Ansley', 'is_active': False}
{'id': 1512, 'full_name': 'Chris Anstey', 'first_name': 'Chris', 'last_name': 'Anstey', 'is_active': False}
{'id': 1630828, 'full_name': 'Alex Antetokounmpo', 'first_name': 'Alex', 'last_name': 'Antetokounmpo', 'is_active': True}
{'id': 203507, 'full_name': 'Giannis Antetokounmpo', 'first_name': 'Giannis', 'last_name': 'Antetokounmpo', 'is_active': True}
{'id': 1628961, 'full_name': 'Kostas Antetokounmpo', 'first_name': 'Kostas', 'last_name': 'Antetokounmpo', 'is_active': False}
{'id': 203648, 'full_name': 'Thanasis Antetokounmpo', 'first_name': 'Thanasis', 'last_name': 'Antetokounmpo', 'is_active': True}
{'id': 2546, 'full_name': 'Carmelo Anthony', 'first_name': 'Carmelo', 'last_name': 'Anthony', 'is_active': False}
{'id': 1630175, 'full_name': 'Cole Anthony', 'first_name': 'Cole', 'last_name': 'Anthony', 'is_active': True}
{'id': 21, 'full_name': 'Greg Anthony', 'first_name': 'Greg', 'last_name': 'Anthony', 'is_active': False}
{'id': 201202, 'full_name': 'Joel Anthony', 'first_name': 'Joel', 'last_name': 'Anthony', 'is_active': False}
{'id': 203544, 'full_name': 'Pero Antic', 'first_name': 'Pero', 'last_name': 'Antic', 'is_active': False}
{'id': 1628384, 'full_name': 'OG Anunoby', 'first_name': 'OG', 'last_name': 'Anunoby', 'is_active': True}
{'id': 203951, 'full_name': 'Keith Appling', 'first_name': 'Keith', 'last_name': 'Appling', 'is_active': False}
{'id': 2737, 'full_name': 'Rafael Araujo', 'first_name': 'Rafael', 'last_name': 'Araujo', 'is_active': False}
{'id': 76053, 'full_name': 'Stacey Arceneaux', 'first_name': 'Stacey', 'last_name': 'Arceneaux', 'is_active': False}
{'id': 76054, 'full_name': 'Nate Archibald', 'first_name': 'Nate', 'last_name': 'Archibald', 'is_active': False}
{'id': 2425, 'full_name': 'Robert Archibald', 'first_name': 'Robert', 'last_name': 'Archibald', 'is_active': False}
{'id': 1627853, 'full_name': 'Ryan Arcidiacono', 'first_name': 'Ryan', 'last_name': 'Arcidiacono', 'is_active': False}
{'id': 76055, 'full_name': 'Jim Ard', 'first_name': 'Jim', 'last_name': 'Ard', 'is_active': False}
{'id': 2240, 'full_name': 'Gilbert Arenas', 'first_name': 'Gilbert', 'last_name': 'Arenas', 'is_active': False}
{'id': 2772, 'full_name': 'Trevor Ariza', 'first_name': 'Trevor', 'last_name': 'Ariza', 'is_active': False}
{'id': 76056, 'full_name': 'Paul Arizin', 'first_name': 'Paul', 'last_name': 'Arizin', 'is_active': False}
{'id': 76057, 'full_name': 'Joe Arlauckas', 'first_name': 'Joe', 'last_name': 'Arlauckas', 'is_active': False}
{'id': 769, 'full_name': 'B.J. Armstrong', 'first_name': 'B.J.', 'last_name': 'Armstrong', 'is_active': False}
{'id': 76061, 'full_name': 'Bob Armstrong', 'first_name': 'Bob', 'last_name': 'Armstrong', 'is_active': False}
{'id': 2220, 'full_name': 'Brandon Armstrong', 'first_name': 'Brandon', 'last_name': 'Armstrong', 'is_active': False}
{'id': 353, 'full_name': 'Darrell Armstrong', 'first_name': 'Darrell', 'last_name': 'Armstrong', 'is_active': False}
{'id': 200756, 'full_name': 'Hilton Armstrong', 'first_name': 'Hilton', 'last_name': 'Armstrong', 'is_active': False}
{'id': 76060, 'full_name': 'Paul Armstrong', 'first_name': 'Paul', 'last_name': 'Armstrong', 'is_active': False}
{'id': 1642379, 'full_name': 'Taran Armstrong', 'first_name': 'Taran', 'last_name': 'Armstrong', 'is_active': False}
{'id': 76059, 'full_name': 'Tate Armstrong', 'first_name': 'Tate', 'last_name': 'Armstrong', 'is_active': False}
{'id': 76062, 'full_name': 'Jesse Arnelle', 'first_name': 'Jesse', 'last_name': 'Arnelle', 'is_active': False}
{'id': 76063, 'full_name': 'Jay Arnette', 'first_name': 'Jay', 'last_name': 'Arnette', 'is_active': False}
{'id': 76064, 'full_name': 'Bob Arnzen', 'first_name': 'Bob', 'last_name': 'Arnzen', 'is_active': False}
{'id': 2306, 'full_name': 'Carlos Arroyo', 'first_name': 'Carlos', 'last_name': 'Arroyo', 'is_active': False}
{'id': 201589, 'full_name': 'Darrell Arthur', 'first_name': 'Darrell', 'last_name': 'Arthur', 'is_active': False}
{'id': 76065, 'full_name': 'John Arthurs', 'first_name': 'John', 'last_name': 'Arthurs', 'is_active': False}
{'id': 1628503, 'full_name': 'Jamel Artis', 'first_name': 'Jamel', 'last_name': 'Artis', 'is_active': False}
{'id': 201600, 'full_name': 'Omer Asik', 'first_name': 'Omer', 'last_name': 'Asik', 'is_active': False}
{'id': 355, 'full_name': 'Vincent Askew', 'first_name': 'Vincent', 'last_name': 'Askew', 'is_active': False}
{'id': 173, 'full_name': 'Keith Askins', 'first_name': 'Keith', 'last_name': 'Askins', 'is_active': False}
{'id': 76068, 'full_name': 'Don Asmonga', 'first_name': 'Don', 'last_name': 'Asmonga', 'is_active': False}
{'id': 76069, 'full_name': 'Richard Atha', 'first_name': 'Richard', 'last_name': 'Atha', 'is_active': False}
{'id': 1088, 'full_name': 'Chucky Atkins', 'first_name': 'Chucky', 'last_name': 'Atkins', 'is_active': False}
{'id': 76070, 'full_name': 'Alvin Attles', 'first_name': 'Alvin', 'last_name': 'Attles', 'is_active': False}
{'id': 76071, 'full_name': 'Chet Aubuchon', 'first_name': 'Chet', 'last_name': 'Aubuchon', 'is_active': False}
{'id': 278, 'full_name': 'Stacey Augmon', 'first_name': 'Stacey', 'last_name': 'Augmon', 'is_active': False}
{'id': 201571, 'full_name': 'D.J. Augustin', 'first_name': 'D.J.', 'last_name': 'Augustin', 'is_active': False}
{'id': 200788, 'full_name': 'James Augustine', 'first_name': 'James', 'last_name': 'Augustine', 'is_active': False}
{'id': 1134, 'full_name': 'Ike Austin', 'first_name': 'Ike', 'last_name': 'Austin', 'is_active': False}
{'id': 76073, 'full_name': 'John Austin', 'first_name': 'John', 'last_name': 'Austin', 'is_active': False}
{'id': 76074, 'full_name': 'Ken Austin', 'first_name': 'Ken', 'last_name': 'Austin', 'is_active': False}
{'id': 1630166, 'full_name': 'Deni Avdija', 'first_name': 'Deni', 'last_name': 'Avdija', 'is_active': True}
{'id': 138, 'full_name': 'Anthony Avent', 'first_name': 'Anthony', 'last_name': 'Avent', 'is_active': False}
{'id': 76076, 'full_name': 'William Averitt', 'first_name': 'William', 'last_name': 'Averitt', 'is_active': False}
{'id': 1895, 'full_name': 'William Avery', 'first_name': 'William', 'last_name': 'Avery', 'is_active': False}
{'id': 76078, 'full_name': 'Dennis Awtrey', 'first_name': 'Dennis', 'last_name': 'Awtrey', 'is_active': False}
{'id': 1630555, 'full_name': 'Joel Ayayi', 'first_name': 'Joel', 'last_name': 'Ayayi', 'is_active': False}
{'id': 202970, 'full_name': 'Gustavo Ayon', 'first_name': 'Gustavo', 'last_name': 'Ayon', 'is_active': False}
{'id': 201965, 'full_name': 'Jeff Ayres', 'first_name': 'Jeff', 'last_name': 'Ayres', 'is_active': False}
{'id': 1629028, 'full_name': 'Deandre Ayton', 'first_name': 'Deandre', 'last_name': 'Ayton', 'is_active': True}
{'id': 101235, 'full_name': 'Kelenna Azubuike', 'first_name': 'Kelenna', 'last_name': 'Azubuike', 'is_active': False}
{'id': 1628962, 'full_name': 'Udoka Azubuike', 'first_name': 'Udoka', 'last_name': 'Azubuike', 'is_active': False}
{'id': 203569, 'full_name': 'Chris Babb', 'first_name': 'Chris', 'last_name': 'Babb', 'is_active': False}
{'id': 202337, 'full_name': 'Luke Babbitt', 'first_name': 'Luke', 'last_name': 'Babbitt', 'is_active': False}
{'id': 76079, 'full_name': 'Milos Babic', 'first_name': 'Milos', 'last_name': 'Babic', 'is_active': False}
{'id': 76080, 'full_name': 'Johnny Bach', 'first_name': 'Johnny', 'last_name': 'Bach', 'is_active': False}
{'id': 1628407, 'full_name': 'Dwayne Bacon', 'first_name': 'Dwayne', 'last_name': 'Bacon', 'is_active': False}

In [3]:
with open("raw_data/all_players.json", "w") as f:
    json.dump(all_players, f, indent=4)

In [4]:
from nba_api.stats.endpoints import commonplayerinfo

player = commonplayerinfo.CommonPlayerInfo(player_id='76003')

In [5]:
player.common_player_info.get_dict()

{'headers': ['PERSON_ID',
  'FIRST_NAME',
  'LAST_NAME',
  'DISPLAY_FIRST_LAST',
  'DISPLAY_LAST_COMMA_FIRST',
  'DISPLAY_FI_LAST',
  'PLAYER_SLUG',
  'BIRTHDATE',
  'SCHOOL',
  'COUNTRY',
  'LAST_AFFILIATION',
  'HEIGHT',
  'WEIGHT',
  'SEASON_EXP',
  'JERSEY',
  'POSITION',
  'ROSTERSTATUS',
  'GAMES_PLAYED_CURRENT_SEASON_FLAG',
  'TEAM_ID',
  'TEAM_NAME',
  'TEAM_ABBREVIATION',
  'TEAM_CODE',
  'TEAM_CITY',
  'PLAYERCODE',
  'FROM_YEAR',
  'TO_YEAR',
  'DLEAGUE_FLAG',
  'NBA_FLAG',
  'GAMES_PLAYED_FLAG',
  'DRAFT_YEAR',
  'DRAFT_ROUND',
  'DRAFT_NUMBER',
  'GREATEST_75_FLAG'],
 'data': [[76003,
   'Kareem',
   'Abdul-Jabbar',
   'Kareem Abdul-Jabbar',
   'Abdul-Jabbar, Kareem',
   'K. Abdul-Jabbar',
   'kareem-abdul-jabbar',
   '1947-04-16T00:00:00',
   'UCLA',
   'USA',
   'UCLA/USA',
   '7-2',
   '225',
   20,
   '33',
   'Center',
   'Inactive',
   'N',
   1610612747,
   'Lakers',
   'LAL',
   'lakers',
   'Los Angeles',
   'HISTADD_kareem_abdul-jabbar',
   1969,
   1988,
   'N',
   'Y',
   'Y',
   '1969',
   '1',
   '1',
   'Y']]}

In [6]:
career = playercareerstats.PlayerCareerStats(player_id='203999')
json.loads(career.get_json())

{'resource': 'playercareerstats',
 'parameters': {'PerMode': 'Totals', 'PlayerID': 203999, 'LeagueID': '00'},
 'resultSets': [{'name': 'SeasonTotalsRegularSeason',
   'headers': ['PLAYER_ID',
    'SEASON_ID',
    'LEAGUE_ID',
    'TEAM_ID',
    'TEAM_ABBREVIATION',
    'PLAYER_AGE',
    'GP',
    'GS',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PTS'],
   'rowSet': [[203999,
     '2015-16',
     '00',
     1610612743,
     'DEN',
     21.0,
     80,
     55,
     1733,
     307,
     600,
     0.512,
     28,
     84,
     0.333,
     154,
     190,
     0.811,
     181,
     379,
     560,
     189,
     79,
     50,
     104,
     208,
     796],
    [203999,
     '2016-17',
     '00',
     1610612743,
     'DEN',
     22.0,
     73,
     59,
     2038,
     494,
     854,
     0.578,
     45,
     139,
     0.324,
     188,
     228,
     0.825,
     212,
     506,
     718,
     359,
     61,
     55,
     171,
     214,
     1221],
    [203999,
     '2017-18',
     '00',
     1610612743,
     'DEN',
     23.0,
     75,
     73,
     2443,
     504,
     1010,
     0.499,
     111,
     280,
     0.396,
     266,
     313,
     0.85,
     195,
     608,
     803,
     458,
     90,
     61,
     210,
     212,
     1385],
    [203999,
     '2018-19',
     '00',
     1610612743,
     'DEN',
     24.0,
     80,
     80,
     2504,
     616,
     1206,
     0.511,
     83,
     270,
     0.307,
     289,
     352,
     0.821,
     228,
     637,
     865,
     580,
     108,
     55,
     248,
     228,
     1604],
    [203999,
     '2019-20',
     '00',
     1610612743,
     'DEN',
     25.0,
     73,
     73,
     2335,
     565,
     1071,
     0.528,
     80,
     255,
     0.314,
     246,
     301,
     0.817,
     166,
     545,
     711,
     512,
     85,
     44,
     226,
     222,
     1456],
    [203999,
     '2020-21',
     '00',
     1610612743,
     'DEN',
     26.0,
     72,
     72,
     2488,
     732,
     1293,
     0.566,
     92,
     237,
     0.388,
     342,
     394,
     0.868,
     205,
     575,
     780,
     599,
     95,
     48,
     222,
     192,
     1898],
    [203999,
     '2021-22',
     '00',
     1610612743,
     'DEN',
     27.0,
     74,
     74,
     2476,
     764,
     1311,
     0.583,
     97,
     288,
     0.337,
     379,
     468,
     0.81,
     206,
     813,
     1019,
     584,
     109,
     63,
     281,
     191,
     2004],
    [203999,
     '2022-23',
     '00',
     1610612743,
     'DEN',
     28.0,
     69,
     69,
     2323,
     646,
     1022,
     0.632,
     57,
     149,
     0.383,
     341,
     415,
     0.822,
     167,
     650,
     817,
     678,
     87,
     47,
     247,
     174,
     1690],
    [203999,
     '2023-24',
     '00',
     1610612743,
     'DEN',
     29.0,
     79,
     79,
     2737,
     822,
     1411,
     0.583,
     83,
     231,
     0.359,
     358,
     438,
     0.817,
     223,
     753,
     976,
     708,
     108,
     68,
     237,
     194,
     2085],
    [203999,
     '2024-25',
     '00',
     1610612743,
     'DEN',
     30.0,
     70,
     70,
     2571,
     786,
     1364,
     0.576,
     138,
     331,
     0.417,
     361,
     451,
     0.8,
     200,
     692,
     892,
     716,
     127,
     45,
     230,
     160,
     2071],
    [203999,
     '2025-26',
     '00',
     1610612743,
     'DEN',
     31.0,
     65,
     65,
     2265,
     644,
     1132,
     0.569,
     112,
     295,
     0.38,
     399,
     480,
     0.831,
     192,
     644,
     836,
     697,
     92,
     53,
     243,
     173,
     1799]]},
  {'name': 'CareerTotalsRegularSeason',
   'headers': ['PLAYER_ID',
    'LEAGUE_ID',
    'TEAM_ID',
    'GP',
    'GS',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PTS'],
   'rowSet': [[203999,
     '00',
     0,
     810,
     769,
     25910,
     6880,
     12274,
     0.560534463092,
     926,
     2559,
     0.361860101602,
     3323,
     4030,
     0.824565756823,
     2175,
     6802,
     8977,
     6080,
     1041,
     589,
     2419,
     2168,
     18009]]},
  {'name': 'SeasonTotalsPostSeason',
   'headers': ['PLAYER_ID',
    'SEASON_ID',
    'LEAGUE_ID',
    'TEAM_ID',
    'TEAM_ABBREVIATION',
    'PLAYER_AGE',
    'GP',
    'GS',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PTS'],
   'rowSet': [[203999,
     '2018-19',
     '00',
     1610612743,
     'DEN',
     24.0,
     14,
     14,
     556,
     132,
     261,
     0.506,
     22,
     56,
     0.393,
     66,
     78,
     0.846,
     54,
     128,
     182,
     118,
     16,
     13,
     36,
     54,
     352],
    [203999,
     '2019-20',
     '00',
     1610612743,
     'DEN',
     25.0,
     19,
     19,
     694,
     178,
     343,
     0.519,
     42,
     98,
     0.429,
     66,
     79,
     0.835,
     37,
     150,
     187,
     109,
     20,
     15,
     62,
     68,
     464],
    [203999,
     '2020-21',
     '00',
     1610612743,
     'DEN',
     26.0,
     10,
     10,
     345,
     116,
     228,
     0.509,
     20,
     53,
     0.377,
     46,
     55,
     0.836,
     37,
     79,
     116,
     50,
     6,
     9,
     24,
     23,
     298],
    [203999,
     '2021-22',
     '00',
     1610612743,
     'DEN',
     27.0,
     5,
     5,
     171,
     61,
     106,
     0.575,
     5,
     18,
     0.278,
     28,
     33,
     0.848,
     17,
     49,
     66,
     29,
     8,
     5,
     24,
     20,
     155],
    [203999,
     '2022-23',
     '00',
     1610612743,
     'DEN',
     28.0,
     20,
     20,
     789,
     227,
     414,
     0.548,
     35,
     76,
     0.461,
     111,
     139,
     0.799,
     69,
     200,
     269,
     190,
     21,
     20,
     70,
     69,
     600],
    [203999,
     '2023-24',
     '00',
     1610612743,
     'DEN',
     29.0,
     12,
     12,
     482,
     133,
     244,
     0.545,
     14,
     53,
     0.264,
     64,
     71,
     0.901,
     43,
     118,
     161,
     104,
     17,
     8,
     40,
     32,
     344],
    [203999,
     '2024-25',
     '00',
     1610612743,
     'DEN',
     30.0,
     14,
     14,
     563,
     131,
     268,
     0.489,
     27,
     71,
     0.38,
     78,
     101,
     0.772,
     29,
     149,
     178,
     112,
     28,
     12,
     55,
     48,
     367],
    [203999,
     '2025-26',
     '00',
     1610612743,
     'DEN',
     31.0,
     6,
     6,
     237,
     54,
     121,
     0.446,
     7,
     36,
     0.194,
     40,
     43,
     0.93,
     9,
     70,
     79,
     57,
     6,
     5,
     23,
     21,
     155]]},
  {'name': 'CareerTotalsPostSeason',
   'headers': ['PLAYER_ID',
    'LEAGUE_ID',
    'TEAM_ID',
    'GP',
    'GS',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PTS'],
   'rowSet': [[203999,
     '00',
     0,
     100,
     100,
     3838,
     1032,
     1985,
     0.519899244332,
     172,
     461,
     0.373101952277,
     499,
     599,
     0.833055091819,
     295,
     943,
     1238,
     769,
     122,
     87,
     334,
     335,
     2735]]},
  {'name': 'SeasonTotalsAllStarSeason',
   'headers': ['PLAYER_ID',
    'SEASON_ID',
    'LEAGUE_ID',
    'TEAM_ID',
    'TEAM_ABBREVIATION',
    'PLAYER_AGE',
    'GP',
    'GS',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PTS'],
   'rowSet': [[203999,
     '2018-19',
     '00',
     1610616833,
     'GNS',
     24.0,
     1,
     0,
     13,
     3,
     4,
     0.75,
     0,
     0,
     0.0,
     0,
     0,
     0.0,
     3,
     6,
     9,
     0,
     0,
     0,
     1,
     1,
     6],
    [203999,
     '2019-20',
     '00',
     1610616834,
     'LBN',
     25.0,
     1,
     0,
     12,
     2,
     4,
     0.5,
     1,
     3,
     0.333,
     0,
     0,
     0.0,
     0,
     2,
     2,
     1,
     1,
     0,
     0,
     1,
     5],
    [203999,
     '2020-21',
     '00',
     1610616834,
     'LBN',
     26.0,
     1,
     1,
     19,
     3,
     4,
     0.75,
     0,
     0,
     0.0,
     0,
     0,
     0.0,
     0,
     7,
     7,
     5,
     0,
     1,
     2,
     1,
     6],
    [203999,
     '2021-22',
     '00',
     1610616834,
     'LBN',
     27.0,
     1,
     1,
     21,
     4,
     5,
     0.8,
     2,
     3,
     0.667,
     0,
     0,
     0.0,
     3,
     6,
     9,
     8,
     1,
     0,
     1,
     0,
     10],
    [203999,
     '2022-23',
     '00',
     1610616834,
     'LBN',
     28.0,
     1,
     1,
     20,
     2,
     4,
     0.5,
     0,
     1,
     0.0,
     0,
     0,
     0.0,
     3,
     2,
     5,
     6,
     2,
     0,
     2,
     0,
     4],
    [203999,
     '2023-24',
     '00',
     1610616834,
     'WST',
     29.0,
     1,
     1,
     23,
     6,
     8,
     0.75,
     1,
     1,
     1.0,
     0,
     0,
     0.0,
     3,
     1,
     4,
     9,
     2,
     0,
     1,
     1,
     13],
    [203999,
     '2024-25',
     '00',
     1610616851,
     'CHK',
     30.0,
     2,
     2,
     16,
     2,
     4,
     0.5,
     0,
     2,
     0.0,
     0,
     2,
     0.0,
     2,
     3,
     5,
     5,
     0,
     0,
     3,
     0,
     4],
    [203999,
     '2025-26',
     '00',
     1610616861,
     'WLD',
     31.0,
     1,
     1,
     5,
     0,
     1,
     0.0,
     0,
     0,
     0.0,
     0,
     0,
     0.0,
     0,
     2,
     2,
     0,
     0,
     0,
     0,
     0,
     0]]},
  {'name': 'CareerTotalsAllStarSeason',
   'headers': ['PLAYER_ID',
    'LEAGUE_ID',
    'TEAM_ID',
    'GP',
    'GS',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PTS'],
   'rowSet': [[203999,
     '00',
     0,
     9,
     7,
     130,
     22,
     34,
     0.647058823529,
     4,
     10,
     0.4,
     0,
     2,
     0.0,
     14,
     29,
     43,
     34,
     6,
     1,
     10,
     4,
     48]]},
  {'name': 'SeasonTotalsCollegeSeason',
   'headers': ['PLAYER_ID',
    'SEASON_ID',
    'LEAGUE_ID',
    'ORGANIZATION_ID',
    'SCHOOL_NAME',
    'PLAYER_AGE',
    'GP',
    'GS',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PTS'],
   'rowSet': []},
  {'name': 'CareerTotalsCollegeSeason',
   'headers': ['PLAYER_ID',
    'LEAGUE_ID',
    'ORGANIZATION_ID',
    'GP',
    'GS',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PTS'],
   'rowSet': []},
  {'name': 'SeasonTotalsShowcaseSeason',
   'headers': ['PLAYER_ID',
    'SEASON_ID',
    'LEAGUE_ID',
    'TEAM_ID',
    'TEAM_ABBREVIATION',
    'PLAYER_AGE',
    'GP',
    'GS',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PTS'],
   'rowSet': []},
  {'name': 'CareerTotalsShowcaseSeason',
   'headers': ['PLAYER_ID',
    'LEAGUE_ID',
    'TEAM_ID',
    'GP',
    'GS',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PTS'],
   'rowSet': []},
  {'name': 'SeasonRankingsRegularSeason',
   'headers': ['PLAYER_ID',
    'SEASON_ID',
    'LEAGUE_ID',
    'TEAM_ID',
    'TEAM_ABBREVIATION',
    'PLAYER_AGE',
    'GP',
    'GS',
    'RANK_MIN',
    'RANK_FGM',
    'RANK_FGA',
    'RANK_FG_PCT',
    'RANK_FG3M',
    'RANK_FG3A',
    'RANK_FG3_PCT',
    'RANK_FTM',
    'RANK_FTA',
    'RANK_FT_PCT',
    'RANK_OREB',
    'RANK_DREB',
    'RANK_REB',
    'RANK_AST',
    'RANK_STL',
    'RANK_BLK',
    'RANK_TOV',
    'RANK_PTS',
    'RANK_EFF'],
   'rowSet': [[203999,
     '2015-16',
     '00',
     1610612743,
     'DEN',
     'NR',
     'NR',
     'NR',
     152,
     112,
     135,
     18,
     223,
     227,
     None,
     90,
     104,
     58,
     24,
     45,
     38,
     82,
     61,
     68,
     115,
     120,
     50],
    [203999,
     '2016-17',
     '00',
     1610612743,
     'DEN',
     'NR',
     'NR',
     'NR',
     108,
     34,
     68,
     6,
     192,
     188,
     None,
     61,
     65,
     46,
     12,
     17,
     13,
     31,
     106,
     51,
     32,
     41,
     17],
    [203999,
     '2017-18',
     '00',
     1610612743,
     'DEN',
     'NR',
     'NR',
     'NR',
     40,
     29,
     36,
     29,
     88,
     99,
     35,
     25,
     30,
     26,
     10,
     8,
     7,
     12,
     38,
     47,
     16,
     26,
     8],
    [203999,
     '2018-19',
     '00',
     1610612743,
     'DEN',
     'NR',
     'NR',
     'NR',
     34,
     19,
     25,
     31,
     128,
     107,
     128,
     28,
     34,
     52,
     10,
     9,
     8,
     6,
     19,
     53,
     9,
     22,
     4],
    [203999,
     '2019-20',
     '00',
     1610612743,
     'DEN',
     'NR',
     'NR',
     'NR',
     11,
     11,
     21,
     19,
     127,
     102,
     142,
     29,
     30,
     56,
     14,
     8,
     8,
     6,
     25,
     63,
     8,
     18,
     3],
    [203999,
     '2020-21',
     '00',
     1610612743,
     'DEN',
     'NR',
     'NR',
     'NR',
     3,
     1,
     8,
     14,
     117,
     132,
     75,
     12,
     14,
     26,
     8,
     7,
     5,
     3,
     11,
     55,
     5,
     3,
     1],
    [203999,
     '2021-22',
     '00',
     1610612743,
     'DEN',
     'NR',
     'NR',
     'NR',
     18,
     2,
     8,
     8,
     121,
     110,
     120,
     9,
     8,
     63,
     13,
     1,
     1,
     6,
     10,
     34,
     5,
     5,
     1],
    [203999,
     '2022-23',
     '00',
     1610612743,
     'DEN',
     'NR',
     'NR',
     'NR',
     47,
     13,
     47,
     8,
     208,
     220,
     None,
     23,
     22,
     58,
     25,
     3,
     3,
     2,
     28,
     62,
     5,
     17,
     1],
    [203999,
     '2023-24',
     '00',
     1610612743,
     'DEN',
     'NR',
     'NR',
     'NR',
     9,
     2,
     11,
     10,
     156,
     158,
     114,
     15,
     15,
     60,
     9,
     2,
     3,
     2,
     8,
     32,
     9,
     5,
     1],
    [203999,
     '2024-25',
     '00',
     1610612743,
     'DEN',
     'NR',
     'NR',
     'NR',
     21,
     3,
     9,
     9,
     76,
     99,
     18,
     10,
     7,
     65,
     13,
     4,
     4,
     2,
     4,
     70,
     7,
     3,
     1],
    [203999,
     '2025-26',
     '00',
     1610612743,
     'DEN',
     'NR',
     'NR',
     'NR',
     43,
     9,
     24,
     10,
     101,
     106,
     67,
     9,
     9,
     45,
     12,
     2,
     4,
     1,
     28,
     53,
     7,
     10,
     1]]},
  {'name': 'SeasonRankingsPostSeason',
   'headers': ['PLAYER_ID',
    'SEASON_ID',
    'LEAGUE_ID',
    'TEAM_ID',
    'TEAM_ABBREVIATION',
    'PLAYER_AGE',
    'GP',
    'GS',
    'RANK_MIN',
    'RANK_FGM',
    'RANK_FGA',
    'RANK_FG_PCT',
    'RANK_FG3M',
    'RANK_FG3A',
    'RANK_FG3_PCT',
    'RANK_FTM',
    'RANK_FTA',
    'RANK_FT_PCT',
    'RANK_OREB',
    'RANK_DREB',
    'RANK_REB',
    'RANK_AST',
    'RANK_STL',
    'RANK_BLK',
    'RANK_TOV',
    'RANK_PTS',
    'RANK_EFF'],
   'rowSet': [[203999,
     '2018-19',
     '00',
     1610612743,
     'DEN',
     'NR',
     'NR',
     'NR',
     13,
     7,
     9,
     14,
     20,
     28,
     29,
     8,
     10,
     27,
     1,
     6,
     4,
     4,
     18,
     14,
     12,
     10,
     4],
    [203999,
     '2019-20',
     '00',
     1610612743,
     'DEN',
     'NR',
     'NR',
     'NR',
     6,
     4,
     4,
     12,
     10,
     16,
     19,
     10,
     10,
     31,
     4,
     2,
     4,
     4,
     11,
     8,
     2,
     5,
     3],
    [203999,
     '2020-21',
     '00',
     1610612743,
     'DEN',
     'NR',
     'NR',
     'NR',
     37,
     13,
     13,
     18,
     36,
     38,
     44,
     14,
     15,
     30,
     8,
     16,
     12,
     20,
     58,
     25,
     19,
     14,
     13],
    [203999,
     '2021-22',
     '00',
     1610612743,
     'DEN',
     'NR',
     'NR',
     'NR',
     85,
     32,
     44,
     7,
     97,
     90,
     79,
     32,
     34,
     21,
     26,
     38,
     35,
     44,
     51,
     53,
     27,
     38,
     37],
    [203999,
     '2022-23',
     '00',
     1610612743,
     'DEN',
     'NR',
     'NR',
     'NR',
     5,
     1,
     2,
     11,
     14,
     25,
     12,
     3,
     2,
     32,
     1,
     1,
     1,
     1,
     8,
     6,
     1,
     1,
     1],
    [203999,
     '2023-24',
     '00',
     1610612743,
     'DEN',
     'NR',
     'NR',
     'NR',
     21,
     8,
     9,
     10,
     46,
     36,
     80,
     7,
     10,
     9,
     3,
     3,
     3,
     5,
     10,
     31,
     6,
     8,
     3],
    [203999,
     '2024-25',
     '00',
     1610612743,
     'DEN',
     'NR',
     'NR',
     'NR',
     17,
     8,
     8,
     19,
     22,
     25,
     33,
     7,
     6,
     41,
     10,
     3,
     3,
     4,
     10,
     16,
     2,
     8,
     5],
    [203999,
     '2025-26',
     '00',
     1610612743,
     'DEN',
     'NR',
     'NR',
     'NR',
     24,
     10,
     9,
     46,
     66,
     26,
     88,
     5,
     11,
     7,
     35,
     1,
     1,
     2,
     41,
     32,
     8,
     9,
     2]]},
  {'name': 'SeasonHighs',
   'headers': ['PLAYER_ID',
    'GAME_ID',
    'GAME_DATE',
    'VS_TEAM_ID',
    'VS_TEAM_CITY',
    'VS_TEAM_NAME',
    'VS_TEAM_ABBREVIATION',
    'STAT',
    'STAT_VALUE',
    'STAT_ORDER',
    'DATE_EST'],
   'rowSet': [[203999,
     '0042500166',
     'Apr 30 2026',
     1610612750,
     'Minnesota',
     'Timberwolves',
     'MIN',
     'PTS',
     28,
     1,
     '2026-04-30T00:00:00'],
    [203999,
     '0042500164',
     'Apr 25 2026',
     1610612750,
     'Minnesota',
     'Timberwolves',
     'MIN',
     'REB',
     15,
     2,
     '2026-04-25T00:00:00'],
    [203999,
     '0042500163',
     'Apr 23 2026',
     1610612750,
     'Minnesota',
     'Timberwolves',
     'MIN',
     'REB',
     15,
     2,
     '2026-04-23T00:00:00'],
    [203999,
     '0042500162',
     'Apr 20 2026',
     1610612750,
     'Minnesota',
     'Timberwolves',
     'MIN',
     'REB',
     15,
     2,
     '2026-04-20T00:00:00'],
    [203999,
     '0042500164',
     'Apr 25 2026',
     1610612750,
     'Minnesota',
     'Timberwolves',
     'MIN',
     'OREB',
     5,
     3,
     '2026-04-25T00:00:00'],
    [203999,
     '0042500162',
     'Apr 20 2026',
     1610612750,
     'Minnesota',
     'Timberwolves',
     'MIN',
     'DREB',
     15,
     4,
     '2026-04-20T00:00:00'],
    [203999,
     '0042500165',
     'Apr 27 2026',
     1610612750,
     'Minnesota',
     'Timberwolves',
     'MIN',
     'AST',
     16,
     5,
     '2026-04-27T00:00:00'],

In [7]:
all_teams_list = teams.get_teams()

In [8]:
with open("raw_data/all_teams.json", "w") as f:
    json.dump(all_teams_list, f, indent=4)

In [9]:
count = 0
for team in all_teams_list:
    print(team)
    count+=1
print(count)

{'id': 1610612737, 'full_name': 'Atlanta Hawks', 'abbreviation': 'ATL', 'nickname': 'Hawks', 'city': 'Atlanta', 'state': 'Georgia', 'year_founded': 1949}
{'id': 1610612738, 'full_name': 'Boston Celtics', 'abbreviation': 'BOS', 'nickname': 'Celtics', 'city': 'Boston', 'state': 'Massachusetts', 'year_founded': 1946}
{'id': 1610612739, 'full_name': 'Cleveland Cavaliers', 'abbreviation': 'CLE', 'nickname': 'Cavaliers', 'city': 'Cleveland', 'state': 'Ohio', 'year_founded': 1970}
{'id': 1610612740, 'full_name': 'New Orleans Pelicans', 'abbreviation': 'NOP', 'nickname': 'Pelicans', 'city': 'New Orleans', 'state': 'Louisiana', 'year_founded': 2002}
{'id': 1610612741, 'full_name': 'Chicago Bulls', 'abbreviation': 'CHI', 'nickname': 'Bulls', 'city': 'Chicago', 'state': 'Illinois', 'year_founded': 1966}
{'id': 1610612742, 'full_name': 'Dallas Mavericks', 'abbreviation': 'DAL', 'nickname': 'Mavericks', 'city': 'Dallas', 'state': 'Texas', 'year_founded': 1980}
{'id': 1610612743, 'full_name': 'Denver Nuggets', 'abbreviation': 'DEN', 'nickname': 'Nuggets', 'city': 'Denver', 'state': 'Colorado', 'year_founded': 1976}
{'id': 1610612744, 'full_name': 'Golden State Warriors', 'abbreviation': 'GSW', 'nickname': 'Warriors', 'city': 'San Francisco', 'state': 'California', 'year_founded': 1946}
{'id': 1610612745, 'full_name': 'Houston Rockets', 'abbreviation': 'HOU', 'nickname': 'Rockets', 'city': 'Houston', 'state': 'Texas', 'year_founded': 1967}
{'id': 1610612746, 'full_name': 'Los Angeles Clippers', 'abbreviation': 'LAC', 'nickname': 'Clippers', 'city': 'Los Angeles', 'state': 'California', 'year_founded': 1970}
{'id': 1610612747, 'full_name': 'Los Angeles Lakers', 'abbreviation': 'LAL', 'nickname': 'Lakers', 'city': 'Los Angeles', 'state': 'California', 'year_founded': 1948}
{'id': 1610612748, 'full_name': 'Miami Heat', 'abbreviation': 'MIA', 'nickname': 'Heat', 'city': 'Miami', 'state': 'Florida', 'year_founded': 1988}
{'id': 1610612749, 'full_name': 'Milwaukee Bucks', 'abbreviation': 'MIL', 'nickname': 'Bucks', 'city': 'Milwaukee', 'state': 'Wisconsin', 'year_founded': 1968}
{'id': 1610612750, 'full_name': 'Minnesota Timberwolves', 'abbreviation': 'MIN', 'nickname': 'Timberwolves', 'city': 'Minnesota', 'state': 'Minnesota', 'year_founded': 1989}
{'id': 1610612751, 'full_name': 'Brooklyn Nets', 'abbreviation': 'BKN', 'nickname': 'Nets', 'city': 'Brooklyn', 'state': 'New York', 'year_founded': 1976}
{'id': 1610612752, 'full_name': 'New York Knicks', 'abbreviation': 'NYK', 'nickname': 'Knicks', 'city': 'New York', 'state': 'New York', 'year_founded': 1946}
{'id': 1610612753, 'full_name': 'Orlando Magic', 'abbreviation': 'ORL', 'nickname': 'Magic', 'city': 'Orlando', 'state': 'Florida', 'year_founded': 1989}
{'id': 1610612754, 'full_name': 'Indiana Pacers', 'abbreviation': 'IND', 'nickname': 'Pacers', 'city': 'Indiana', 'state': 'Indiana', 'year_founded': 1976}
{'id': 1610612755, 'full_name': 'Philadelphia 76ers', 'abbreviation': 'PHI', 'nickname': '76ers', 'city': 'Philadelphia', 'state': 'Pennsylvania', 'year_founded': 1949}
{'id': 1610612756, 'full_name': 'Phoenix Suns', 'abbreviation': 'PHX', 'nickname': 'Suns', 'city': 'Phoenix', 'state': 'Arizona', 'year_founded': 1968}
{'id': 1610612757, 'full_name': 'Portland Trail Blazers', 'abbreviation': 'POR', 'nickname': 'Trail Blazers', 'city': 'Portland', 'state': 'Oregon', 'year_founded': 1970}
{'id': 1610612758, 'full_name': 'Sacramento Kings', 'abbreviation': 'SAC', 'nickname': 'Kings', 'city': 'Sacramento', 'state': 'California', 'year_founded': 1948}
{'id': 1610612759, 'full_name': 'San Antonio Spurs', 'abbreviation': 'SAS', 'nickname': 'Spurs', 'city': 'San Antonio', 'state': 'Texas', 'year_founded': 1976}
{'id': 1610612760, 'full_name': 'Oklahoma City Thunder', 'abbreviation': 'OKC', 'nickname': 'Thunder', 'city': 'Oklahoma City', 'state': 'Oklahoma', 'year_founded': 1967}
{'id': 1610612761, 'full_name': 'Toronto Raptors', 'abbreviation': 'TOR', 'nickname': 'Raptors', 'city': 'Toronto', 'state': 'Ontario', 'year_founded': 1995}
{'id': 1610612762, 'full_name': 'Utah Jazz', 'abbreviation': 'UTA', 'nickname': 'Jazz', 'city': 'Utah', 'state': 'Utah', 'year_founded': 1974}
{'id': 1610612763, 'full_name': 'Memphis Grizzlies', 'abbreviation': 'MEM', 'nickname': 'Grizzlies', 'city': 'Memphis', 'state': 'Tennessee', 'year_founded': 1995}
{'id': 1610612764, 'full_name': 'Washington Wizards', 'abbreviation': 'WAS', 'nickname': 'Wizards', 'city': 'Washington', 'state': 'District of Columbia', 'year_founded': 1961}
{'id': 1610612765, 'full_name': 'Detroit Pistons', 'abbreviation': 'DET', 'nickname': 'Pistons', 'city': 'Detroit', 'state': 'Michigan', 'year_founded': 1948}
{'id': 1610612766, 'full_name': 'Charlotte Hornets', 'abbreviation': 'CHA', 'nickname': 'Hornets', 'city': 'Charlotte', 'state': 'North Carolina', 'year_founded': 1988}
30

In [10]:
from nba_api.stats.endpoints import leaguegamefinder

In [11]:
games = leaguegamefinder.LeagueGameFinder(season_nullable='1985-86')
data = json.loads(games.get_normalized_json())
json.loads(games.get_normalized_json())

{'LeagueGameFinderResults': [{'SEASON_ID': '41985',
   'TEAM_ID': 1610612745,
   'TEAM_ABBREVIATION': 'HOU',
   'TEAM_NAME': 'Houston Rockets',
   'GAME_ID': '0048500406',
   'GAME_DATE': '1986-06-08',
   'MATCHUP': 'HOU @ BOS',
   'WL': 'L',
   'MIN': 240,
   'PTS': 97,
   'FGM': 38,
   'FGA': 89,
   'FG_PCT': 0.427,
   'FG3M': 1,
   'FG3A': 5,
   'FG3_PCT': 0.2,
   'FTM': 20,
   'FTA': 28,
   'FT_PCT': 0.714,
   'OREB': 17,
   'DREB': 27,
   'REB': 44,
   'AST': 21,
   'STL': 10,
   'BLK': 3,
   'TOV': 17,
   'PF': 26,
   'PLUS_MINUS': None},
  {'SEASON_ID': '41985',
   'TEAM_ID': 1610612738,
   'TEAM_ABBREVIATION': 'BOS',
   'TEAM_NAME': 'Boston Celtics',
   'GAME_ID': '0048500406',
   'GAME_DATE': '1986-06-08',
   'MATCHUP': 'BOS vs. HOU',
   'WL': 'W',
   'MIN': 240,
   'PTS': 114,
   'FGM': 41,
   'FGA': 83,
   'FG_PCT': 0.494,
   'FG3M': 3,
   'FG3A': 4,
   'FG3_PCT': 0.75,
   'FTM': 29,
   'FTA': 44,
   'FT_PCT': 0.659,
   'OREB': 15,
   'DREB': 34,
   'REB': 49,
   'AST': 30,
   'STL': 9,
   'BLK': 8,
   'TOV': 14,
   'PF': 21,
   'PLUS_MINUS': None},
  {'SEASON_ID': '41985',
   'TEAM_ID': 1610612738,
   'TEAM_ABBREVIATION': 'BOS',
   'TEAM_NAME': 'Boston Celtics',
   'GAME_ID': '0048500068',
   'GAME_DATE': '1986-06-05',
   'MATCHUP': 'BOS @ HOU',
   'WL': 'L',
   'MIN': 240,
   'PTS': 96,
   'FGM': 34,
   'FGA': 84,
   'FG_PCT': 0.405,
   'FG3M': 1,
   'FG3A': 6,
   'FG3_PCT': 0.167,
   'FTM': 27,
   'FTA': 31,
   'FT_PCT': 0.871,
   'OREB': 10,
   'DREB': 27,
   'REB': 37,
   'AST': 20,
   'STL': 6,
   'BLK': 7,
   'TOV': 18,
   'PF': 22,
   'PLUS_MINUS': None},
  {'SEASON_ID': '41985',
   'TEAM_ID': 1610612745,
   'TEAM_ABBREVIATION': 'HOU',
   'TEAM_NAME': 'Houston Rockets',
   'GAME_ID': '0048500068',
   'GAME_DATE': '1986-06-05',
   'MATCHUP': 'HOU vs. BOS',
   'WL': 'W',
   'MIN': 240,
   'PTS': 111,
   'FGM': 49,
   'FGA': 101,
   'FG_PCT': 0.485,
   'FG3M': 1,
   'FG3A': 2,
   'FG3_PCT': 0.5,
   'FTM': 12,
   'FTA': 18,
   'FT_PCT': 0.667,
   'OREB': 23,
   'DREB': 33,
   'REB': 56,
   'AST': 32,
   'STL': 9,
   'BLK': 13,
   'TOV': 14,
   'PF': 23,
   'PLUS_MINUS': None},
  {'SEASON_ID': '41985',
   'TEAM_ID': 1610612738,
   'TEAM_ABBREVIATION': 'BOS',
   'TEAM_NAME': 'Boston Celtics',
   'GAME_ID': '0048500067',
   'GAME_DATE': '1986-06-03',
   'MATCHUP': 'BOS @ HOU',
   'WL': 'W',
   'MIN': 240,
   'PTS': 106,
   'FGM': 45,
   'FGA': 78,
   'FG_PCT': 0.577,
   'FG3M': 2,
   'FG3A': 6,
   'FG3_PCT': 0.333,
   'FTM': 14,
   'FTA': 17,
   'FT_PCT': 0.824,
   'OREB': 11,
   'DREB': 29,
   'REB': 40,
   'AST': 23,
   'STL': 8,
   'BLK': 6,
   'TOV': 15,
   'PF': 17,
   'PLUS_MINUS': None},
  {'SEASON_ID': '41985',
   'TEAM_ID': 1610612745,
   'TEAM_ABBREVIATION': 'HOU',
   'TEAM_NAME': 'Houston Rockets',
   'GAME_ID': '0048500067',
   'GAME_DATE': '1986-06-03',
   'MATCHUP': 'HOU vs. BOS',
   'WL': 'L',
   'MIN': 240,
   'PTS': 103,
   'FGM': 43,
   'FGA': 99,
   'FG_PCT': 0.434,
   'FG3M': 0,
   'FG3A': 3,
   'FG3_PCT': 0.0,
   'FTM': 17,
   'FTA': 20,
   'FT_PCT': 0.85,
   'OREB': 25,
   'DREB': 21,
   'REB': 46,
   'AST': 28,
   'STL': 6,
   'BLK': 6,
   'TOV': 9,
   'PF': 18,
   'PLUS_MINUS': None},
  {'SEASON_ID': '41985',
   'TEAM_ID': 1610612745,
   'TEAM_ABBREVIATION': 'HOU',
   'TEAM_NAME': 'Houston Rockets',
   'GAME_ID': '0048500066',
   'GAME_DATE': '1986-06-01',
   'MATCHUP': 'HOU vs. BOS',
   'WL': 'W',
   'MIN': 240,
   'PTS': 106,
   'FGM': 38,
   'FGA': 81,
   'FG_PCT': 0.469,
   'FG3M': 1,
   'FG3A': 2,
   'FG3_PCT': 0.5,
   'FTM': 29,
   'FTA': 39,
   'FT_PCT': 0.744,
   'OREB': 13,
   'DREB': 30,
   'REB': 43,
   'AST': 28,
   'STL': 9,
   'BLK': 7,
   'TOV': 17,
   'PF': 23,
   'PLUS_MINUS': None},
  {'SEASON_ID': '41985',
   'TEAM_ID': 1610612738,
   'TEAM_ABBREVIATION': 'BOS',
   'TEAM_NAME': 'Boston Celtics',
   'GAME_ID': '0048500066',
   'GAME_DATE': '1986-06-01',
   'MATCHUP': 'BOS @ HOU',
   'WL': 'L',
   'MIN': 240,
   'PTS': 104,
   'FGM': 42,
   'FGA': 96,
   'FG_PCT': 0.438,
   'FG3M': 1,
   'FG3A': 5,
   'FG3_PCT': 0.2,
   'FTM': 19,
   'FTA': 21,
   'FT_PCT': 0.905,
   'OREB': 22,
   'DREB': 31,
   'REB': 53,
   'AST': 28,
   'STL': 12,
   'BLK': 4,
   'TOV': 19,
   'PF': 27,
   'PLUS_MINUS': None},
  {'SEASON_ID': '41985',
   'TEAM_ID': 1610612745,
   'TEAM_ABBREVIATION': 'HOU',
   'TEAM_NAME': 'Houston Rockets',
   'GAME_ID': '0048500065',
   'GAME_DATE': '1986-05-29',
   'MATCHUP': 'HOU @ BOS',
   'WL': 'L',
   'MIN': 240,
   'PTS': 95,
   'FGM': 38,
   'FGA': 92,
   'FG_PCT': 0.413,
   'FG3M': 1,
   'FG3A': 3,
   'FG3_PCT': 0.333,
   'FTM': 18,
   'FTA': 27,
   'FT_PCT': 0.667,
   'OREB': 19,
   'DREB': 25,
   'REB': 44,
   'AST': 27,
   'STL': 9,
   'BLK': 4,
   'TOV': 13,
   'PF': 24,
   'PLUS_MINUS': None},
  {'SEASON_ID': '41985',
   'TEAM_ID': 1610612738,
   'TEAM_ABBREVIATION': 'BOS',
   'TEAM_NAME': 'Boston Celtics',
   'GAME_ID': '0048500065',
   'GAME_DATE': '1986-05-29',
   'MATCHUP': 'BOS vs. HOU',
   'WL': 'W',
   'MIN': 240,
   'PTS': 117,
   'FGM': 45,
   'FGA': 90,
   'FG_PCT': 0.5,
   'FG3M': 4,
   'FG3A': 9,
   'FG3_PCT': 0.444,
   'FTM': 23,
   'FTA': 24,
   'FT_PCT': 0.958,
   'OREB': 14,
   'DREB': 29,
   'REB': 43,
   'AST': 28,
   'STL': 9,
   'BLK': 8,
   'TOV': 12,
   'PF': 20,
   'PLUS_MINUS': None},
  {'SEASON_ID': '41985',
   'TEAM_ID': 1610612738,
   'TEAM_ABBREVIATION': 'BOS',
   'TEAM_NAME': 'Boston Celtics',
   'GAME_ID': '0048500064',
   'GAME_DATE': '1986-05-26',
   'MATCHUP': 'BOS vs. HOU',
   'WL': 'W',
   'MIN': 240,
   'PTS': 112,
   'FGM': 47,
   'FGA': 84,
   'FG_PCT': 0.56,
   'FG3M': 1,
   'FG3A': 4,
   'FG3_PCT': 0.25,
   'FTM': 17,
   'FTA': 27,
   'FT_PCT': 0.63,
   'OREB': 10,
   'DREB': 32,
   'REB': 42,
   'AST': 35,
   'STL': 15,
   'BLK': 5,
   'TOV': 17,
   'PF': 17,
   'PLUS_MINUS': None},
  {'SEASON_ID': '41985',
   'TEAM_ID': 1610612745,
   'TEAM_ABBREVIATION': 'HOU',
   'TEAM_NAME': 'Houston Rockets',
   'GAME_ID': '0048500064',
   'GAME_DATE': '1986-05-26',
   'MATCHUP': 'HOU @ BOS',
   'WL': 'L',
   'MIN': 240,
   'PTS': 100,
   'FGM': 45,
   'FGA': 95,
   'FG_PCT': 0.474,
   'FG3M': 1,
   'FG3A': 2,
   'FG3_PCT': 0.5,
   'FTM': 9,
   'FTA': 16,
   'FT_PCT': 0.563,
   'OREB': 14,
   'DREB': 26,
   'REB': 40,
   'AST': 27,
   'STL': 11,
   'BLK': 7,
   'TOV': 16,
   'PF': 19,
   'PLUS_MINUS': None},
  {'SEASON_ID': '41985',
   'TEAM_ID': 1610612745,
   'TEAM_ABBREVIATION': 'HOU',
   'TEAM_NAME': 'Houston Rockets',
   'GAME_ID': '0048500315',
   'GAME_DATE': '1986-05-21',
   'MATCHUP': 'HOU @ LAL',
   'WL': 'W',
   'MIN': 240,
   'PTS': 114,
   'FGM': 43,
   'FGA': 88,
   'FG_PCT': 0.489,
   'FG3M': 2,
   'FG3A': 4,
   'FG3_PCT': 0.5,
   'FTM': 26,
   'FTA': 34,
   'FT_PCT': 0.765,
   'OREB': 11,
   'DREB': 20,
   'REB': 31,
   'AST': 31,
   'STL': 16,
   'BLK': 6,
   'TOV': 14,
   'PF': 20,
   'PLUS_MINUS': None},
  {'SEASON_ID': '41985',
   'TEAM_ID': 1610612747,
   'TEAM_ABBREVIATION': 'LAL',
   'TEAM_NAME': 'Los Angeles Lakers',
   'GAME_ID': '0048500315',
   'GAME_DATE': '1986-05-21',
   'MATCHUP': 'LAL vs. HOU',
   'WL': 'L',
   'MIN': 240,
   'PTS': 112,
   'FGM': 47,
   'FGA': 92,
   'FG_PCT': 0.511,
   'FG3M': 1,
   'FG3A': 5,
   'FG3_PCT': 0.2,
   'FTM': 17,
   'FTA': 22,
   'FT_PCT': 0.773,
   'OREB': 19,
   'DREB': 32,
   'REB': 51,
   'AST': 33,
   'STL': 12,
   'BLK': 5,
   'TOV': 23,
   'PF': 27,
   'PLUS_MINUS': None},
  {'SEASON_ID': '41985',
   'TEAM_ID': 1610612747,
   'TEAM_ABBREVIATION': 'LAL',
   'TEAM_NAME': 'Los Angeles Lakers',
   'GAME_ID': '0048500314',
   'GAME_DATE': '1986-05-18',
   'MATCHUP': 'LAL @ HOU',
   'WL': 'L',
   'MIN': 240,
   'PTS': 95,
   'FGM': 40,
   'FGA': 86,
   'FG_PCT': 0.465,
   'FG3M': 1,
   'FG3A': 8,
   'FG3_PCT': 0.125,
   'FTM': 14,
   'FTA': 17,
   'FT_PCT': 0.824,
   'OREB': 9,
   'DREB': 29,
   'REB': 38,
   'AST': 27,
   'STL': 3,
   'BLK': 2,
   'TOV': 16,
   'PF': 29,
   'PLUS_MINUS': None},
  {'SEASON_ID': '41985',
   'TEAM_ID': 1610612749,
   'TEAM_ABBREVIATION': 'MIL',
   'TEAM_NAME': 'Milwaukee Bucks',
   'GAME_ID': '0048500304',
   'GAME_DATE': '1986-05-18',
   'MATCHUP': 'MIL vs. BOS',
   'WL': 'L',
   'MIN': 228,
   'PTS': 94,
   'FGM': 34,
   'FGA': 83,
   'FG_PCT': 0.41,
   'FG3M': 2,
   'FG3A': 8,
   'FG3_PCT': 0.25,
   'FTM': 24,
   'FTA': 28,
   'FT_PCT': 0.857,
   'OREB': 10,
   'DREB': 27,
   'REB': 37,
   'AST': 25,
   'STL': 10,
   'BLK': 1,
   'TOV': 6,
   'PF': 20,
   'PLUS_MINUS': None},
  {'SEASON_ID': '41985',
   'TEAM_ID': 1610612738,
   'TEAM_ABBREVIATION': 'BOS',
   'TEAM_NAME': 'Boston Celtics',
   'GAME_ID': '0048500304',
   'GAME_DATE': '1986-05-18',
   'MATCHUP': 'BOS @ MIL',
   'WL': 'W',
   'MIN': 240,
   'PTS': 111,
   'FGM': 40,
   'FGA': 80,
   'FG_PCT': 0.5,
   'FG3M': 8,
   'FG3A': 12,
   'FG3_PCT': 0.667,
   'FTM': 23,
   'FTA': 25,
   'FT_PCT': 0.92,
   'OREB': 7,
   'DREB': 40,
   'REB': 47,
   'AST': 17,
   'STL': 5,
   'BLK': 1,
   'TOV': 18,
   'PF': 26,
   'PLUS_MINUS': None},
  {'SEASON_ID': '41985',
   'TEAM_ID': 1610612745,
   'TEAM_ABBREVIATION': 'HOU',
   'TEAM_NAME': 'Houston Rockets',
   'GAME_ID': '0048500314',
   'GAME_DATE': '1986-05-18',
   'MATCHUP': 'HOU vs. LAL',
   'WL': 'W',
   'MIN': 240,
   'PTS': 105,
   'FGM': 39,
   'FGA': 85,
   'FG_PCT': 0.459,
   'FG3M': 0,
   'FG3A': 2,
   'FG3_PCT': 0.0,
   'FTM': 27,
   'FTA': 37,
   'FT_PCT': 0.73,
   'OREB': 15,
   'DREB': 34,
   'REB': 49,
   'AST': 20,
   'STL': 5,
   'BLK': 7,
   'TOV': 9,
   'PF': 21,
   'PLUS_MINUS': None},
  {'SEASON_ID': '41985',
   'TEAM_ID': 1610612749,
   'TEAM_ABBREVIATION': 'MIL',
   'TEAM_NAME': 'Milwaukee Bucks',
   'GAME_ID': '0048500303',
   'GAME_DATE': '1986-05-17',
   'MATCHUP': 'MIL vs. BOS',
   'WL': 'L',
   'MIN': 240,
   'PTS': 107,
   'FGM': 41,
   'FGA': 94,
   'FG_PCT': 0.436,
   'FG3M': 4,
   'FG3A': 9,
   'FG3_PCT': 0.444,
   'FTM': 21,
   'FTA': 30,
   'FT_PCT': 0.7,
   'OREB': 14,
   'DREB': 31,
   'REB': 45,
   'AST': 22,
   'STL': 7,
   'BLK': 5,
   'TOV': 17,
   'PF': 30,
   'PLUS_MINUS': None},
  {'SEASON_ID': '41985',
   'TEAM_ID': 1610612738,
   'TEAM_ABBREVIATION': 'BOS',
   'TEAM_NAME': 'Boston Celtics',
   'GAME_ID': '0048500303',
   'GAME_DATE': '1986-05-17',
   'MATCHUP': 'BOS @ MIL',
   'WL': 'W',
   'MIN': 240,
   'PTS': 111,
   'FGM': 41,
   'FGA': 89,
   'FG_PCT': 0.461,
   'FG3M': 2,
   'FG3A': 6,
   'FG3_PCT': 0.333,
   'FTM': 27,
   'FTA': 37,
   'FT_PCT': 0.73,
   'OREB': 18,
   'DREB': 29,
   'REB': 47,
   'AST': 30,
   'STL': 10,
   'BLK': 8,
   'TOV': 15,
   'PF': 24,
   'PLUS_MINUS': None},
  {'SEASON_ID': '41985',
   'TEAM_ID': 1610612745,
   'TEAM_ABBREVIATION': 'HOU',
   'TEAM_NAME': 'Houston Rockets',
   'GAME_ID': '0048500313',
   'GAME_DATE': '1986-05-16',
   'MATCHUP': 'HOU vs. LAL',
   'WL': 'W',
   'MIN': 240,
   'PTS': 117,
   'FGM': 46,
   'FGA': 96,
   'FG_PCT': 0.479,
   'FG3M': 0,
   'FG3A': 0,
   'FG3_PCT': None,
   'FTM': 25,
   'FTA': 31,
   'FT_PCT': 0.806,
   'OREB': 20,
   'DREB': 25,
   'REB': 45,
   'AST': 29,
   'STL': 6,
   'BLK': 3,
   'TOV': 10,
   'PF': 21,
   'PLUS_MINUS': None},
  {'SEASON_ID': '41985',
   'TEAM_ID': 1610612747,
   'TEAM_ABBREVIATION': 'LAL',
   'TEAM_NAME': 'Los Angeles Lakers',
   'GAME_ID': '0048500313',
   'GAME_DATE': '1986-05-16',
   'MATCHUP': 'LAL @ HOU',
   'WL': 'L',
   'MIN': 240,
   'PTS': 109,
   'FGM': 47,
   'FGA': 84,
   'FG_PCT': 0.56,
   'FG3M': 1,
   'FG3A': 9,
   'FG3_PCT': 0.111,
   'FTM': 14,
   'FTA': 18,
   'FT_PCT': 0.778,
   'OREB': 10,
   'DREB': 24,
   'REB': 34,
   'AST': 39,
   'STL': 7,
   'BLK': 6,
   'TOV': 19,
   'PF': 25,
   'PLUS_MINUS': None},
  {'SEASON_ID': '41985',
   'TEAM_ID': 1610612738,
   'TEAM_ABBREVIATION': 'BOS',
   'TEAM_NAME': 'Boston Celtics',
   'GAME_ID': '0048500302',
   'GAME_DATE': '1986-05-15',
   'MATCHUP': 'BOS vs. MIL',
   'WL': 'W',
   'MIN': 240,
   'PTS': 122,
   'FGM': 47,
   'FGA': 87,
   'FG_PCT': 0.54,
   'FG3M': 3,
   'FG3A': 11,
   'FG3_PCT': 0.273,
   'FTM': 25,
   'FTA': 30,
   'FT_PCT': 0.833,
   'OREB': 13,
   'DREB': 23,
   'REB': 36,
   'AST': 34,
   'STL': 11,
   'BLK': 5,
   'TOV': 14,
   'PF': 16,
   'PLUS_MINUS': None},
  {'SEASON_ID': '41985',
   'TEAM_ID': 1610612749,
   'TEAM_ABBREVIATION': 'MIL',
   'TEAM_NAME': 'Milwaukee Bucks',
   'GAME_ID': '0048500302',
   'GAME_DATE': '1986-05-15',
   'MATCHUP': 'MIL @ BOS',
   'WL': 'L',
   'MIN': 240,
   'PTS': 111,
   'FGM': 45,
   'FGA': 80,
   'FG_PCT': 0.563,
   'FG3M': 2,
   'FG3A': 7,
   'FG3_PCT': 0.286,
   'FTM': 19,
   'FTA': 24,
   'FT_PCT': 0.792,
   'OREB': 9,
   'DREB': 25,
   'REB': 34,
   'AST': 28,
   'STL': 10,
   'BLK': 7,
   'TOV': 20,
   'PF': 26,
   'PLUS_MINUS': None},
  {'SEASON_ID': '41985',
   'TEAM_ID': 1610612738,
   'TEAM_ABBREVIATION': 'BOS',
   'TEAM_NAME': 'Boston Celtics',
   'GAME_ID': '0048500301',
   'GAME_DATE': '1986-05-13',
   'MATCHUP': 'BOS vs. MIL',
   'WL': 'W',
   'MIN': 240,
   'PTS': 128,
   'FGM': 54,
   'FGA': 96,
   'FG_PCT': 0.563,
   'FG3M': 1,
   'FG3A': 6,
   'FG3_PCT': 0.167,
   'FTM': 19,
   'FTA': 24,
   'FT_PCT': 0.792,
   'OREB': 13,
   'DREB': 43,
   'REB': 56,
   'AST': 39,
   'STL': 7,
   'BLK': 10,
   'TOV': 15,
   'PF': 28,
   'PLUS_MINUS': None},
  {'SEASON_ID': '41985',
   'TEAM_ID': 1610612745,
   'TEAM_ABBREVIATION': 'HOU',
   'TEAM_NAME': 'Houston Rockets',
   'GAME_ID': '0048500322',
   'GAME_DATE': '1986-05-13',
   'MATCHUP': 'HOU @ LAL',
   'WL': 'W',
   'MIN': 240,
   'PTS': 112,
   'FGM': 46,
   'FGA': 91,
   'FG_PCT': 0.505,
   'FG3M': 0,
   'FG3A': 2,
   'FG3_PCT': 0.0,
   'FTM': 20,
   'FTA': 28,
   'FT_PCT': 0.714,
   'OREB': 14,
   'DREB': 37,
   'REB': 51,
   'AST': 39,
   'STL': 11,
   'BLK': 12,
   'TOV': 19,
   'PF': 21,
   'PLUS_MINUS': None},
  {'SEASON_ID': '41985',
   'TEAM_ID': 1610612747,
   'TEAM_ABBREVIATION': 'LAL',
   'TEAM_NAME': 'Los Angeles Lakers',
   'GAME_ID': '0048500322',
   'GAME_DATE': '1986-05-13',
   'MATCHUP': 'LAL vs. HOU',
   'WL': 'L',
   'MIN': 240,
   'PTS': 102,
   'FGM': 40,
   'FGA': 90,
   'FG_PCT': 0.444,
   'FG3M': 3,
   'FG3A': 6,
   'FG3_PCT': 0.5,
   'FTM': 19,
   'FTA': 25,
   'FT_PCT': 0.76,
   'OREB': 13,
   'DREB': 25,
   'REB': 38,
   'AST': 30,
   'STL': 13,
   'BLK': 3,
   'TOV': 18,
   'PF': 21,
   'PLUS_MINUS': None},
  {'SEASON_ID': '41985',
   'TEAM_ID': 1610612749,
   'TEAM_ABBREVIATION': 'MIL',
   'TEAM_NAME': 'Milwaukee Bucks',
   'GAME_ID': '0048500301',
   'GAME_DATE': '1986-05-13',
   'MATCHUP': 'MIL @ BOS',
   'WL': 'L',
   'MIN': 240,
   'PTS': 96,
   'FGM': 36,
   'FGA': 96,
   'FG_PCT': 0.375,
   'FG3M': 4,
   'FG3A': 8,
   'FG3_PCT': 0.5,
   'FTM': 20,
   'FTA': 31,
   'FT_PCT': 0.645,
   'OREB': 15,
   'DREB': 25,
   'REB': 40,
   'AST': 17,
   'STL': 6,
   'BLK': 7,
   'TOV': 13,
   'PF': 23,
   'PLUS_MINUS': None},
  {'SEASON_ID': '41985',
   'TEAM_ID': 1610612755,
   'TEAM_ABBREVIATION': 'PHL',
   'TEAM_NAME': 'Philadelphia 76ers',
   'GAME_ID': '0048500217',
   'GAME_DATE': '1986-05-11',
   'MATCHUP': 'PHL @ MIL',
   'WL': 'L',
   'MIN': 240,
   'PTS': 112,
   'FGM': 42,
   'FGA': 81,
   'FG_PCT': 0.519,
   'FG3M': 0,
   'FG3A': 2,
   'FG3_PCT': 0.0,
   'FTM': 28,
   'FTA': 35,
   'FT_PCT': 0.8,
   'OREB': 17,
   'DREB': 21,
   'REB': 38,
   'AST': 17,
   'STL': 12,
   'BLK': 1,
   'TOV': 18,
   'PF': 22,
   'PLUS_MINUS': None},
  {'SEASON_ID': '41985',
   'TEAM_ID': 1610612749,
   'TEAM_ABBREVIATION': 'MIL',
   'TEAM_NAME': 'Milwaukee Bucks',
   'GAME_ID': '0048500217',
   'GAME_DATE': '1986-05-11',
   'MATCHUP': 'MIL vs. PHL',
   'WL': 'W',
   'MIN': 240,
   'PTS': 113,
   'FGM': 44,
   'FGA': 80,
   'FG_PCT': 0.55,
   'FG3M': 1,
   'FG3A': 5,
   'FG3_PCT': 0.2,
   'FTM': 24,
   'FTA': 30,
   'FT_PCT': 0.8,
   'OREB': 13,
   'DREB': 20,
   'REB': 33,
   'AST': 26,
   'STL': 8,
   'BLK': 6,
   'TOV': 17,
   'PF': 26,
   'PLUS_MINUS': None},
  {'SEASON_ID': '41985',
   'TEAM_ID': 1610612745,
   'TEAM_ABBREVIATION': 'HOU',
   'TEAM_NAME': 'Houston Rockets',
   'GAME_ID': '0048500321',
   'GAME_DATE': '1986-05-10',
   'MATCHUP': 'HOU @ LAL',
   'WL': 'L',
   'MIN': 240,
   'PTS': 107,
   'FGM': 43,
   'FGA': 87,
   'FG_PCT': 0.494,
   'FG3M': 2,
   'FG3A': 6,
   'FG3_PCT': 0.333,
   'FTM': 19,
   'FTA': 26,
   'FT_PCT': 0.731,
   'OREB': 15,
   'DREB': 26,
   'REB': 41,
   'AST': 28,
   'STL': 8,
   'BLK': 8,
   'TOV': 21,
   'PF': 26,
   'PLUS_MINUS': None},
  {'SEASON_ID': '41985',
   'TEAM_ID': 1610612747,
   'TEAM_ABBREVIATION': 'LAL',
   'TEAM_NAME': 'Los Angeles Lakers',
   'GAME_ID': '0048500321',
   'GAME_DATE': '1986-05-10',
   'MATCHUP': 'LAL vs. HOU',
   'WL': 'W',
   'MIN': 240,
   'PTS': 119,
   'FGM': 46,
   'FGA': 87,
   'FG_PCT': 0.529,
   'FG3M': 2,
   'FG3A': 7,
   'FG3_PCT': 0.286,
   'FTM': 25,
   'FTA': 34,
   'FT_PCT': 0.735,
   'OREB': 10,
   'DREB': 25,
   'REB': 35,
   'AST': 33,
   'STL': 11,
   'BLK': 5,
   'TOV': 16,
   'PF': 20,
   'PLUS_MINUS': None},
  {'SEASON_ID': '41985',
   'TEAM_ID': 1610612755,
   'TEAM_ABBREVIATION': 'PHL',
   'TEAM_NAME': 'Philadelphia 76ers',
   'GAME_ID': '0048500216',
   'GAME_DATE': '1986-05-09',
   'MATCHUP': 'PHL vs. MIL',
   'WL': 'W',
   'MIN': 240,
   'PTS': 126,
   'FGM': 43,
   'FGA': 76,
   'FG_PCT': 0.566,
   'FG3M': 0,
   'FG3A': 0,
   'FG3_PCT': None,
   'FTM': 40,
   'FTA': 55,
   'FT_PCT': 0.727,
   'OREB': 14,
   'DREB': 42,
   'REB': 56,
   'AST': 27,
   'STL': 13,
   'BLK': 11,
   'TOV': 27,
   'PF': 21,
   'PLUS_MINUS': None},
  {'SEASON_ID': '41985',
   'TEAM_ID': 1610612749,
   'TEAM_ABBREVIATION': 'MIL',
   'TEAM_NAME': 'Milwaukee Bucks',
   'GAME_ID': '0048500216',
   'GAME_DATE': '1986-05-09',
   'MATCHUP': 'MIL @ PHL',
   'WL': 'L',
   'MIN': 240,
   'PTS': 108,
   'FGM': 39,
   'FGA': 90,
   'FG_PCT': 0.433,
   'FG3M': 5,
   'FG3A': 10,
   'FG3_PCT': 0.5,
   'FTM': 25,
   'FTA': 37,
   'FT_PCT': 0.676,
   'OREB': 13,
   'DREB': 21,
   'REB': 34,
   'AST': 24,
   'STL': 19,
   'BLK': 8,
   'TOV': 25,
   'PF': 34,
   'PLUS_MINUS': None},
  {'SEASON_ID': '41985',
   'TEAM_ID': 1610612745,
   'TEAM_ABBREVIATION': 'HOU',
   'TEAM_NAME': 'Houston Rockets',
   'GAME_ID': '0048500236',
   'GAME_DATE': '1986-05-08',
   'MATCHUP': 'HOU @ DEN',
   'WL': 'W',
   'MIN': 290,
   'PTS': 126,
   'FGM': 53,
   'FGA': 112,
   'FG_PCT': 0.473,
   'FG3M': 0,
   'FG3A': 3,
   'FG3_PCT': 0.0,
   'FTM': 20,
   'FTA': 32,
   'FT_PCT': 0.625,
   'OREB': 21,
   'DREB': 41,
   'REB': 62,
   'AST': 24,
   'STL': 2,
   'BLK': 8,
   'TOV': 16,
   'PF': 31,
   'PLUS_MINUS': None},
  {'SEASON_ID': '41985',
   'TEAM_ID': 1610612747,
   'TEAM_ABBREVIATION': 'LAL',
   'TEAM_NAME': 'Los Angeles Lakers',
   'GAME_ID': '0048500226',
   'GAME_DATE': '1986-05-08',
   'MATCHUP': 'LAL @ DAL',
   'WL': 'W',
   'MIN': 240,
   'PTS': 120,
   'FGM': 48,
   'FGA': 94,
   'FG_PCT': 0.511,
   'FG3M': 4,
   'FG3A': 7,
   'FG3_PCT': 0.571,
   'FTM': 20,
   'FTA': 25,
   'FT_PCT': 0.8,
   'OREB': 10,
   'DREB': 32,
   'REB': 42,
   'AST': 32,
   'STL': 9,
   'BLK': 5,
   'TOV': 12,
   'PF': 26,
   'PLUS_MINUS': None},
  {'SEASON_ID': '41985',
   'TEAM_ID': 1610612742,
   'TEAM_ABBREVIATION': 'DAL',
   'TEAM_NAME': 'Dallas Mavericks',
   'GAME_ID': '0048500226',
   'GAME_DATE': '1986-05-08',
   'MATCHUP': 'DAL vs. LAL',
   'WL': 'L',
   'MIN': 240,
   'PTS': 107,
   'FGM': 42,
   'FGA': 90,
   'FG_PCT': 0.467,
   'FG3M': 3,
   'FG3A': 8,
   'FG3_PCT': 0.375,
   'FTM': 20,
   'FTA': 25,
   'FT_PCT': 0.8,
   'OREB': 13,
   'DREB': 27,
   'REB': 40,
   'AST': 24,
   'STL': 7,
   'BLK': 0,
   'TOV': 16,
   'PF': 22,
   'PLUS_MINUS': None},
  {'SEASON_ID': '41985',
   'TEAM_ID': 1610612743,
   'TEAM_ABBREVIATION': 'DEN',
   'TEAM_NAME': 'Denver Nuggets',
   'GAME_ID': '0048500236',
   'GAME_DATE': '1986-05-08',
   'MATCHUP': 'DEN vs. HOU',
   'WL': 'L',
   'MIN': 290,
   'PTS': 122,
   'FGM': 44,
   'FGA': 109,
   'FG_PCT': 0.404,
   'FG3M': 0,
   'FG3A': 3,
   'FG3_PCT': 0.0,
   'FTM': 34,
   'FTA': 42,
   'FT_PCT': 0.81,
   'OREB': 23,
   'DREB': 36,
   'REB': 59,
   'AST': 25,
   'STL': 8,
   'BLK': 5,
   'TOV': 13,
   'PF': 32,

In [12]:
with open("raw_data/games/games_1985_86.json", "w") as f:
    json.dump(data, f, indent=4)

In [13]:
from nba_api.stats.endpoints import commonteamroster

res = commonteamroster.CommonTeamRoster(team_id='1610612747', season='2010-11')
json.loads(res.get_json())

{'resource': 'commonteamroster',
 'parameters': {'TeamID': 1610612747, 'LeagueID': '00', 'Season': '2010-11'},
 'resultSets': [{'name': 'CommonTeamRoster',
   'headers': ['TeamID',
    'SEASON',
    'LeagueID',
    'PLAYER',
    'NICKNAME',
    'PLAYER_SLUG',
    'NUM',
    'POSITION',
    'HEIGHT',
    'WEIGHT',
    'BIRTH_DATE',
    'AGE',
    'EXP',
    'SCHOOL',
    'PLAYER_ID',
    'HOW_ACQUIRED'],
   'rowSet': [[1610612747,
     '2010',
     '00',
     'Joe Smith',
     'Joe',
     'joe-smith',
     '1',
     'F-C',
     '6-10',
     '225',
     'JUL 26, 1975',
     35.0,
     '15',
     'Maryland',
     693,
     None],
    [1610612747,
     '2010',
     '00',
     'Derek Fisher',
     'Derek',
     'derek-fisher',
     '2',
     'G',
     '6-1',
     '210',
     'AUG 09, 1974',
     36.0,
     '14',
     'Arkansas-Little Rock',
     965,
     None],
    [1610612747,
     '2010',
     '00',
     'Devin Ebanks',
     'Devin',
     'devin-ebanks',
     '3',
     'F',
     '6-9',
     '215',
     'OCT 28, 1989',
     21.0,
     'R',
     'West Virginia',
     202365,
     None],
    [1610612747,
     '2010',
     '00',
     'Luke Walton',
     'Luke',
     'luke-walton',
     '4',
     'F',
     '6-8',
     '235',
     'MAR 28, 1980',
     31.0,
     '7',
     'Arizona',
     2575,
     None],
    [1610612747,
     '2010',
     '00',
     'Steve Blake',
     'Steve',
     'steve-blake',
     '5',
     'G',
     '6-3',
     '172',
     'FEB 26, 1980',
     31.0,
     '7',
     'Maryland',
     2581,
     None],
    [1610612747,
     '2010',
     '00',
     'Lamar Odom',
     'Lamar',
     'lamar-odom',
     '7',
     'F',
     '6-10',
     '230',
     'NOV 06, 1979',
     31.0,
     '11',
     'Rhode Island',
     1885,
     None],
    [1610612747,
     '2010',
     '00',
     'Matt Barnes',
     'Matt',
     'matt-barnes',
     '9',
     'F',
     '6-7',
     '226',
     'MAR 09, 1980',
     31.0,
     '7',
     'UCLA',
     2440,
     None],
    [1610612747,
     '2010',
     '00',
     'Trey Johnson',
     'Trey',
     'trey-johnson',
     '10',
     'G-F',
     '6-5',
     '218',
     'AUG 30, 1984',
     26.0,
     '1',
     'Jackson State',
     201234,
     None],
    [1610612747,
     '2010',
     '00',
     'Shannon Brown',
     'Shannon',
     'shannon-brown',
     '12',
     'G',
     '6-4',
     '210',
     'NOV 29, 1985',
     25.0,
     '4',
     'Michigan State',
     200769,
     None],
    [1610612747,
     '2010',
     '00',
     'Metta World Peace',
     'Metta',
     'metta-world-peace',
     '15',
     'F',
     '6-7',
     '260',
     'NOV 13, 1979',
     31.0,
     '11',
     "St. John's (NY)",
     1897,
     None],
    [1610612747,
     '2010',
     '00',
     'Pau Gasol',
     'Pau',
     'pau-gasol',
     '16',
     'F-C',
     '7-0',
     '250',
     'JUL 06, 1980',
     30.0,
     '9',
     'FC Barcelona',
     2200,
     None],
    [1610612747,
     '2010',
     '00',
     'Andrew Bynum',
     'Andrew',
     'andrew-bynum',
     '17',
     'C',
     '7-0',
     '285',
     'OCT 27, 1987',
     23.0,
     '5',
     'No College',
     101115,
     None],
    [1610612747,
     '2010',
     '00',
     'Kobe Bryant',
     'Kobe',
     'kobe-bryant',
     '24',
     'G',
     '6-6',
     '205',
     'AUG 23, 1978',
     32.0,
     '14',
     'Lower Merion HS (PA)',
     977,
     None],
    [1610612747,
     '2010',
     '00',
     'Derrick Caracter',
     'Derrick',
     'derrick-caracter',
     '45',
     'F',
     '6-9',
     '275',
     'MAY 04, 1988',
     23.0,
     'R',
     'Texas-El Paso',
     202382,
     None],
    [1610612747,
     '2010',
     '00',
     'Theo Ratliff',
     'Theo',
     'theo-ratliff',
     '50',
     'C',
     '6-10',
     '235',
     'APR 17, 1973',
     38.0,
     '15',
     'Wyoming',
     689,
     None]]},
  {'name': 'Coaches',
   'headers': ['TEAM_ID',
    'SEASON',
    'COACH_ID',
    'FIRST_NAME',
    'LAST_NAME',
    'COACH_NAME',
    'IS_ASSISTANT',
    'COACH_TYPE',
    'SORT_SEQUENCE',
    'SUB_SORT_SEQUENCE'],
   'rowSet': [[1610612747,
     '2010',
     1219,
     'Phil',
     'Jackson',
     'Phil Jackson',
     1,
     'Head Coach',
     None,
     1],
    [1610612747,
     '2010',
     1221,
     'Frank',
     'Hamblen',
     'Frank Hamblen',
     2,
     'Assistant Coach',
     None,
     5],
    [1610612747,
     '2010',
     1230,
     'Jim',
     'Cleamons',
     'Jim Cleamons',
     2,
     'Assistant Coach',
     None,
     5],
    [1610612747,
     '2010',
     2888,
     'Brian',
     'Shaw',
     'Brian Shaw',
     2,
     'Assistant Coach',
     None,
     5],
    [1610612747,
     '2010',
     101172,
     'Chuck',
     'Person',
     'Chuck Person',
     2,
     'Assistant Coach',
     None,
     5],
    [1610612747,
     '2010',
     1273,
     'Gary',
     'Vitti',
     'Gary Vitti',
     3,
     'Trainer',
     None,
     7]]}]}

In [14]:
from nba_api.stats.endpoints import leaguegamelog

logs = leaguegamelog.LeagueGameLog(season='1985-86')
json.loads(logs.get_json())

{'resource': 'leaguegamelog',
 'parameters': {'LeagueID': '00',
  'Season': '1985-86',
  'SeasonType': 'Regular Season',
  'PlayerOrTeam': 'T',
  'Counter': 0,
  'Sorter': 'DATE',
  'Direction': 'ASC',
  'DateFrom': '',
  'DateTo': ''},
 'resultSets': [{'name': 'LeagueGameLog',
   'headers': ['SEASON_ID',
    'TEAM_ID',
    'TEAM_ABBREVIATION',
    'TEAM_NAME',
    'GAME_ID',
    'GAME_DATE',
    'MATCHUP',
    'WL',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PTS',
    'PLUS_MINUS',
    'VIDEO_AVAILABLE'],
   'rowSet': [['21985',
     1610612737,
     'ATL',
     'Atlanta Hawks',
     '0028500005',
     '1985-10-25',
     'ATL vs. WAS',
     'L',
     240,
     41,
     92,
     0.446,
     0,
     3,
     0.0,
     9,
     18,
     0.5,
     16,
     28,
     44,
     25,
     8,
     5,
     16,
     23,
     91,
     -9,
     0],
    ['21985',
     1610612738,
     'BOS',
     'Boston Celtics',
     '0028500004',
     '1985-10-25',
     'BOS @ NJN',
     'L',
     265,
     40,
     84,
     0.476,
     2,
     7,
     0.286,
     27,
     32,
     0.844,
     9,
     34,
     43,
     27,
     14,
     5,
     28,
     27,
     109,
     -4,
     0],
    ['21985',
     1610612739,
     'CLE',
     'Cleveland Cavaliers',
     '0028500007',
     '1985-10-25',
     'CLE @ CHI',
     'L',
     265,
     45,
     93,
     0.484,
     2,
     3,
     0.667,
     23,
     32,
     0.719,
     16,
     31,
     47,
     24,
     8,
     8,
     20,
     34,
     115,
     -1,
     0],
    ['21985',
     1610612741,
     'CHI',
     'Chicago Bulls',
     '0028500007',
     '1985-10-25',
     'CHI vs. CLE',
     'W',
     265,
     43,
     95,
     0.453,
     1,
     4,
     0.25,
     29,
     41,
     0.707,
     21,
     32,
     53,
     29,
     8,
     8,
     20,
     33,
     116,
     1,
     0],
    ['21985',
     1610612743,
     'DEN',
     'Denver Nuggets',
     '0028500008',
     '1985-10-25',
     'DEN @ GOS',
     'W',
     240,
     42,
     88,
     0.477,
     1,
     3,
     0.333,
     34,
     43,
     0.791,
     13,
     31,
     44,
     26,
     11,
     3,
     22,
     40,
     119,
     14,
     0],
    ['21985',
     1610612744,
     'GOS',
     'Golden State Warriors',
     '0028500008',
     '1985-10-25',
     'GOS vs. DEN',
     'L',
     240,
     36,
     91,
     0.396,
     0,
     4,
     0.0,
     33,
     52,
     0.635,
     18,
     29,
     47,
     17,
     3,
     7,
     28,
     37,
     105,
     -14,
     0],
    ['21985',
     1610612745,
     'HOU',
     'Houston Rockets',
     '0028500011',
     '1985-10-25',
     'HOU @ UTH',
     'W',
     240,
     44,
     89,
     0.494,
     0,
     0,
     None,
     24,
     34,
     0.706,
     17,
     30,
     47,
     23,
     10,
     7,
     19,
     28,
     112,
     4,
     0],
    ['21985',
     1610612746,
     'LAC',
     'Los Angeles Clippers',
     '0028500006',
     '1985-10-25',
     'LAC @ SAC',
     'W',
     240,
     39,
     80,
     0.488,
     0,
     0,
     None,
     30,
     40,
     0.75,
     11,
     31,
     42,
     19,
     7,
     7,
     18,
     32,
     108,
     4,
     0],
    ['21985',
     1610612749,
     'MIL',
     'Milwaukee Bucks',
     '0028500010',
     '1985-10-25',
     'MIL @ DET',
     'L',
     240,
     42,
     88,
     0.477,
     2,
     5,
     0.4,
     30,
     45,
     0.667,
     13,
     28,
     41,
     27,
     10,
     7,
     20,
     32,
     116,
     -2,
     0],
    ['21985',
     1610612751,
     'NJN',
     'New Jersey Nets',
     '0028500004',
     '1985-10-25',
     'NJN vs. BOS',
     'W',
     265,
     44,
     101,
     0.436,
     0,
     1,
     0.0,
     25,
     31,
     0.806,
     19,
     33,
     52,
     17,
     14,
     3,
     24,
     30,
     113,
     4,
     0],
    ['21985',
     1610612756,
     'PHX',
     'Phoenix Suns',
     '0028500009',
     '1985-10-25',
     'PHX @ POR',
     'L',
     265,
     47,
     102,
     0.461,
     2,
     10,
     0.2,
     27,
     42,
     0.643,
     22,
     32,
     54,
     32,
     13,
     7,
     27,
     37,
     123,
     -5,
     0],
    ['21985',
     1610612757,
     'POR',
     'Portland Trail Blazers',
     '0028500009',
     '1985-10-25',
     'POR vs. PHX',
     'W',
     265,
     47,
     110,
     0.427,
     0,
     1,
     0.0,
     34,
     38,
     0.895,
     23,
     31,
     54,
     28,
     17,
     9,
     21,
     33,
     128,
     5,
     0],
    ['21985',
     1610612758,
     'SAC',
     'Sacramento Kings',
     '0028500006',
     '1985-10-25',
     'SAC vs. LAC',
     'L',
     240,
     39,
     88,
     0.443,
     0,
     2,
     0.0,
     26,
     41,
     0.634,
     20,
     28,
     48,
     17,
     5,
     2,
     20,
     34,
     104,
     -4,
     0],
    ['21985',
     1610612762,
     'UTH',
     'Utah Jazz',
     '0028500011',
     '1985-10-25',
     'UTH vs. HOU',
     'L',
     240,
     42,
     82,
     0.512,
     0,
     2,
     0.0,
     24,
     38,
     0.632,
     10,
     24,
     34,
     30,
     10,
     9,
     16,
     27,
     108,
     -4,
     0],
    ['21985',
     1610612764,
     'WAS',
     'Washington Bullets',
     '0028500005',
     '1985-10-25',
     'WAS @ ATL',
     'W',
     240,
     40,
     78,
     0.513,
     0,
     2,
     0.0,
     20,
     26,
     0.769,
     11,
     29,
     40,
     21,
     11,
     7,
     17,
     19,
     100,
     9,
     0],
    ['21985',
     1610612765,
     'DET',
     'Detroit Pistons',
     '0028500010',
     '1985-10-25',
     'DET vs. MIL',
     'W',
     240,
     39,
     88,
     0.443,
     0,
     1,
     0.0,
     40,
     49,
     0.816,
     17,
     40,
     57,
     23,
     11,
     0,
     22,
     32,
     118,
     2,
     0],
    ['21985',
     1610612737,
     'ATL',
     'Atlanta Hawks',
     '0028500013',
     '1985-10-26',
     'ATL @ MIL',
     'L',
     240,
     27,
     70,
     0.386,
     0,
     2,
     0.0,
     37,
     52,
     0.712,
     12,
     24,
     36,
     14,
     9,
     7,
     27,
     34,
     91,
     -26,
     0],
    ['21985',
     1610612738,
     'BOS',
     'Boston Celtics',
     '0028500016',
     '1985-10-26',
     'BOS @ CLE',
     'W',
     240,
     36,
     86,
     0.419,
     0,
     3,
     0.0,
     33,
     45,
     0.733,
     21,
     33,
     54,
     22,
     3,
     2,
     14,
     24,
     105,
     5,
     0],
    ['21985',
     1610612739,
     'CLE',
     'Cleveland Cavaliers',
     '0028500016',
     '1985-10-26',
     'CLE vs. BOS',
     'L',
     240,
     39,
     89,
     0.438,
     3,
     7,
     0.429,
     19,
     33,
     0.576,
     13,
     27,
     40,
     20,
     4,
     7,
     11,
     32,
     100,
     -5,
     0],
    ['21985',
     1610612741,
     'CHI',
     'Chicago Bulls',
     '0028500014',
     '1985-10-26',
     'CHI vs. DET',
     'W',
     240,
     40,
     87,
     0.46,
     2,
     3,
     0.667,
     39,
     45,
     0.867,
     17,
     29,
     46,
     18,
     6,
     11,
     20,
     33,
     121,
     3,
     0],
    ['21985',
     1610612742,
     'DAL',
     'Dallas Mavericks',
     '0028500017',
     '1985-10-26',
     'DAL vs. SEA',
     'W',
     240,
     34,
     83,
     0.41,
     0,
     2,
     0.0,
     33,
     41,
     0.805,
     11,
     31,
     42,
     18,
     6,
     4,
     15,
     17,
     101,
     6,
     0],
    ['21985',
     1610612743,
     'DEN',
     'Denver Nuggets',
     '0028500018',
     '1985-10-26',
     'DEN vs. SAC',
     'W',
     240,
     51,
     103,
     0.495,
     0,
     2,
     0.0,
     21,
     31,
     0.677,
     16,
     21,
     37,
     27,
     17,
     8,
     13,
     22,
     123,
     11,
     0],
    ['21985',
     1610612745,
     'HOU',
     'Houston Rockets',
     '0028500015',
     '1985-10-26',
     'HOU @ LAC',
     'L',
     290,
     56,
     122,
     0.459,
     0,
     4,
     0.0,
     17,
     24,
     0.708,
     24,
     34,
     58,
     36,
     7,
     3,
     21,
     34,
     129,
     -1,
     0],
    ['21985',
     1610612746,
     'LAC',
     'Los Angeles Clippers',
     '0028500015',
     '1985-10-26',
     'LAC vs. HOU',
     'W',
     290,
     48,
     102,
     0.471,
     0,
     2,
     0.0,
     34,
     47,
     0.723,
     14,
     36,
     50,
     21,
     12,
     4,
     19,
     32,
     130,
     1,
     0],
    ['21985',
     1610612747,
     'LAL',
     'Los Angeles Lakers',
     '0028500019',
     '1985-10-26',
     'LAL @ SAN',
     'W',
     290,
     49,
     99,
     0.495,
     1,
     6,
     0.167,
     22,
     27,
     0.815,
     15,
     38,
     53,
     30,
     8,
     5,
     22,
     28,
     121,
     5,
     0],
    ['21985',
     1610612749,
     'MIL',
     'Milwaukee Bucks',
     '0028500013',
     '1985-10-26',
     'MIL vs. ATL',
     'W',
     240,
     44,
     85,
     0.518,
     2,
     5,
     0.4,
     27,
     30,
     0.9,
     12,
     30,
     42,
     28,
     11,
     3,
     22,
     40,
     117,
     26,
     0],
    ['21985',
     1610612751,
     'NJN',
     'New Jersey Nets',
     '0028500020',
     '1985-10-26',
     'NJN @ IND',
     'L',
     240,
     31,
     79,
     0.392,
     0,
     2,
     0.0,
     30,
     45,
     0.667,
     9,
     23,
     32,
     19,
     10,
     0,
     19,
     28,
     92,
     -27,
     0],
    ['21985',
     1610612752,
     'NYK',
     'New York Knicks',
     '0028500012',
     '1985-10-26',
     'NYK vs. PHL',
     'L',
     240,
     36,
     92,
     0.391,
     1,
     3,
     0.333,
     16,
     25,
     0.64,
     10,
     19,
     29,
     19,
     12,
     5,
     13,
     28,
     89,
     -10,
     0],
    ['21985',
     1610612754,
     'IND',
     'Indiana Pacers',
     '0028500020',
     '1985-10-26',
     'IND vs. NJN',
     'W',
     240,
     44,
     74,
     0.595,
     0,
     0,
     None,
     31,
     34,
     0.912,
     6,
     42,
     48,
     27,
     8,
     4,
     27,
     27,
     119,
     27,
     0],
    ['21985',
     1610612755,
     'PHL',
     'Philadelphia 76ers',
     '0028500012',
     '1985-10-26',
     'PHL @ NYK',
     'W',
     240,
     33,
     81,
     0.407,
     0,
     3,
     0.0,
     33,
     39,
     0.846,
     22,
     37,
     59,
     20,
     9,
     6,
     23,
     26,
     99,
     10,
     0],
    ['21985',
     1610612758,
     'SAC',
     'Sacramento Kings',
     '0028500018',
     '1985-10-26',
     'SAC @ DEN',
     'L',
     240,
     45,
     83,
     0.542,
     0,
     2,
     0.0,
     22,
     30,
     0.733,
     13,
     37,
     50,
     14,
     9,
     8,
     26,
     26,
     112,
     -11,
     0],
    ['21985',
     1610612759,
     'SAN',
     'San Antonio Spurs',
     '0028500019',
     '1985-10-26',
     'SAN vs. LAL',
     'L',
     290,
     50,
     108,
     0.463,
     0,
     2,
     0.0,
     16,
     26,
     0.615,
     16,
     35,
     51,
     32,
     18,
     5,
     20,
     33,
     116,
     -5,
     0],
    ['21985',
     1610612760,
     'SEA',
     'Seattle SuperSonics',
     '0028500017',
     '1985-10-26',
     'SEA @ DAL',
     'L',
     240,
     42,
     88,
     0.477,
     2,
     5,
     0.4,
     9,
     11,
     0.818,
     7,
     31,
     38,
     30,
     7,
     5,
     18,
     34,
     95,
     -6,
     0],
    ['21985',
     1610612765,
     'DET',
     'Detroit Pistons',
     '0028500014',
     '1985-10-26',
     'DET @ CHI',
     'L',
     240,
     42,
     91,
     0.462,
     0,
     2,
     0.0,
     34,
     46,
     0.739,
     23,
     24,
     47,
     21,
     9,
     7,
     20,
     32,
     118,
     -3,
     0],
    ['21985',
     1610612744,
     'GOS',
     'Golden State Warriors',
     '0028500021',
     '1985-10-27',
     'GOS @ POR',
     'L',
     240,
     36,
     83,
     0.434,
     1,
     3,
     0.333,
     26,
     33,
     0.788,
     18,
     23,
     41,
     24,
     11,
     6,
     29,
     31,
     99,
     -17,
     0],
    ['21985',
     1610612757,
     'POR',
     'Portland Trail Blazers',
     '0028500021',
     '1985-10-27',
     'POR vs. GOS',
     'W',
     240,
     47,
     89,
     0.528,
     2,
     2,
     1.0,
     20,
     23,
     0.87,
     15,
     26,
     41,
     34,
     14,
     6,
     26,
     29,
     116,
     17,
     0],
    ['21985',
     1610612737,
     'ATL',
     'Atlanta Hawks',
     '0028500030',
     '1985-10-29',
     'ATL vs. NYK',
     'W',
     240,
     37,
     86,
     0.43,
     1,
     3,
     0.333,
     27,
     38,
     0.711,
     24,
     36,
     60,
     21,
     9,
     7,
     12,
     25,
     102,
     15,
     0],
    ['21985',
     1610612739,
     'CLE',
     'Cleveland Cavaliers',
     '0028500197',
     '1985-10-29',
     'CLE vs. WAS',
     'L',
     240,
     33,
     87,
     0.379,
     3,
     8,
     0.375,
     21,
     29,
     0.724,
     12,
     26,
     38,
     22,
     10,
     4,
     10,
     27,
     90,
     -7,
     0],
    ['21985',
     1610612741,
     'CHI',
     'Chicago Bulls',
     '0028500023',
     '1985-10-29',
     'CHI @ GOS',
     'W',
     240,
     45,
     92,
     0.489,
     0,
     1,
     0.0,
     21,
     26,
     0.808,
     13,
     33,
     46,
     24,
     6,
     5,
     14,
     27,
     111,
     6,
     0],
    ['21985',
     1610612742,
     'DAL',
     'Dallas Mavericks',
     '0028500024',
     '1985-10-29',
     'DAL vs. LAL',
     'L',
     240,
     43,
     99,
     0.434,
     1,
     4,
     0.25,
     28,
     35,
     0.8,
     11,
     20,
     31,
     29,
     8,
     2,
     12,
     20,
     115,
     -18,
     0],
    ['21985',
     1610612743,
     'DEN',
     'Denver Nuggets',
     '0028500026',
     '1985-10-29',
     'DEN @ PHX',
     'W',
     240,
     49,
     108,
     0.454,
     1,
     4,
     0.25,
     43,
     54,
     0.796,
     24,
     27,
     51,
     26,
     20,
     7,
     30,
     39,
     142,
     15,
     0],
    ['21985',
     1610612744,
     'GOS',
     'Golden State Warriors',
     '0028500023',
     '1985-10-29',
     'GOS vs. CHI',
     'L',
     240,
     40,
     89,
     0.449,
     4,
     6,
     0.667,
     21,
     28,
     0.75,
     13,
     38,
     51,
     23,
     3,
     3,
     21,
     25,
     105,
     -6,
     0],
    ['21985',
     1610612745,
     'HOU',
     'Houston Rockets',
     '0028500022',
     '1985-10-29',
     'HOU vs. SEA',
     'W',
     240,
     43,
     82,
     0.524,
     0,
     0,
     None,
     25,
     30,
     0.833,
     14,
     30,
     44,
     26,
     9,
     6,
     23,
     20,
     111,
     12,
     0],
    ['21985',
     1610612746,
     'LAC',
     'Los Angeles Clippers',
     '0028500025',
     '1985-10-29',
     'LAC vs. POR',
     'W',
     240,
     46,
     91,
     0.505,
     0,
     1,
     0.0,
     27,
     36,
     0.75,
     15,
     26,
     41,
     35,
     7,
     4,
     14,
     23,
     119,
     6,
     0],
    ['21985',
     1610612747,
     'LAL',
     'Los Angeles Lakers',
     '0028500024',
     '1985-10-29',
     'LAL @ DAL',
     'W',
     240,
     58,
     101,
     0.574,
     2,
     6,
     0.333,
     15,
     18,
     0.833,
     16,
     44,
     60,
     35,
     6,
     3,
     19,
     32,
     133,
     18,
     0],
    ['21985',
     1610612749,
     'MIL',
     'Milwaukee Bucks',
     '0028500028',
     '1985-10-29',
     'MIL vs. PHL',
     'W',
     240,
     51,
     86,
     0.593,
     3,
     6,
     0.5,
     14,
     20,
     0.7,
     9,
     22,
     31,
     32,
     8,
     5,
     18,
     29,
     119,
     2,
     0],
    ['21985',
     1610612751,
     'NJN',
     'New Jersey Nets',
     '0028500029',
     '1985-10-29',
     'NJN @ DET',
     'L',
     240,
     40,
     98,
     0.408,
     1,
     5,
     0.2,
     26,
     35,
     0.743,
     18,
     41,
     59,
     22,
     6,
     4,
     20,
     39,
     107,
     -17,
     0],
    ['21985',
     1610612752,
     'NYK',
     'New York Knicks',
     '0028500030',
     '1985-10-29',
     'NYK @ ATL',
     'L',
     240,
     31,
     84,
     0.369,
     0,
     3,
     0.0,
     25,
     36,
     0.694,
     19,
     25,
     44,
     15,
     8,
     3,
     12,
     26,
     87,
     -15,
     0],
    ['21985',
     1610612755,
     'PHL',
     'Philadelphia 76ers',
     '0028500028',
     '1985-10-29',
     'PHL @ MIL',
     'L',
     240,
     46,
     93,
     0.495,
     1,
     5,
     0.2,
     24,
     36,
     0.667,
     20,
     29,
     49,
     26,
     10,
     4,
     18,
     20,
     117,
     -2,
     0],
    ['21985',
     1610612756,
     'PHX',
     'Phoenix Suns',
     '0028500026',
     '1985-10-29',
     'PHX vs. DEN',
     'L',
     240,
     44,
     85,
     0.518,
     0,
     1,
     0.0,
     39,
     57,
     0.684,
     14,
     30,
     44,
     30,
     13,
     6,
     39,
     41,
     127,
     -15,
     0],
    ['21985',
     1610612757,
     'POR',
     'Portland Trail Blazers',
     '0028500025',
     '1985-10-29',
     'POR @ LAC',
     'L',
     240,
     48,
     99,
     0.485,
     1,
     6,
     0.167,
     16,
     24,
     0.667,
     18,
     28,
     46,
     33,
     9,
     4,
     18,
     27,
     113,
     -6,
     0],
    ['21985',
     1610612759,
     'SAN',
     'San Antonio Spurs',
     '0028500027',
     '1985-10-29',
     'SAN vs. UTH',
     'W',
     240,
     43,
     89,
     0.483,
     0,
     1,
     0.0,
     38,
     49,
     0.776,
     24,
     33,
     57,
     26,
     10,
     6,
     18,
     31,
     124,
     12,
     0],
    ['21985',
     1610612760,
     'SEA',
     'Seattle SuperSonics',
     '0028500022',
     '1985-10-29',
     'SEA @ HOU',
     'L',
     240,
     39,
     87,
     0.448,
     3,
     6,
     0.5,
     18,
     24,
     0.75,
     12,
     20,
     32,
     21,
     16,
     5,
     20,
     24,
     99,
     -12,
     0],
    ['21985',
     1610612762,
     'UTH',
     'Utah Jazz',
     '0028500027',
     '1985-10-29',
     'UTH @ SAN',
     'L',
     240,
     43,
     90,
     0.478,
     0,
     0,
     None,
     26,
     40,
     0.65,
     12,
     25,
     37,
     27,
     7,
     8,
     18,
     33,
     112,
     -12,
     0],
    ['21985',
     1610612764,
     'WAS',
     'Washington Bullets',
     '0028500197',
     '1985-10-29',
     'WAS @ CLE',
     'W',
     240,
     39,
     79,
     0.494,
     0,
     3,
     0.0,
     19,
     30,
     0.633,
     8,
     34,
     42,
     24,
     3,
     7,
     16,
     21,
     97,
     7,
     0],
    ['21985',
     1610612765,
     'DET',
     'Detroit Pistons',
     '0028500029',
     '1985-10-29',
     'DET vs. NJN',
     'W',
     240,
     42,
     87,
     0.483,
     2,
     3,
     0.667,
     38,
     56,
     0.679,
     14,
     36,
     50,
     25,
     7,
     4,
     15,
     34,
     124,
     17,
     0],
    ['21985',
     1610612738,
     'BOS',
     'Boston Celtics',
     '0028500033',
     '1985-10-30',
     'BOS vs. MIL',
     'W',
     240,
     42,
     84,
     0.5,
     0,
     2,
     0.0,
     33,
     41,
     0.805,
     15,
     33,
     48,
     27,
     8,
     9,
     22,
     30,
     117,
     11,
     0],
    ['21985',
     1610612749,
     'MIL',
     'Milwaukee Bucks',
     '0028500033',
     '1985-10-30',
     'MIL @ BOS',
     'L',
     240,
     40,
     92,
     0.435,
     2,
     7,
     0.286,
     24,
     33,
     0.727,
     15,
     24,
     39,
     21,
     13,
     3,
     20,
     33,
     106,
     -11,
     0],
    ['21985',
     1610612751,
     'NJN',
     'New Jersey Nets',
     '0028500031',
     '1985-10-30',
     'NJN vs. IND',
     'W',
     315,
     55,
     121,
     0.455,
     0,

In [16]:
with open("raw_data/games/games_1987-88_regular_log.json") as f:
    games_log = json.load(f)

print(len(games_log["LeagueGameLog"]))

1886

In [17]:
games_ = games_log["LeagueGameLog"]
games_log["LeagueGameLog"]

[{'SEASON_ID': '21987',
  'TEAM_ID': 1610612737,
  'TEAM_ABBREVIATION': 'ATL',
  'TEAM_NAME': 'Atlanta Hawks',
  'GAME_ID': '0028700007',
  'GAME_DATE': '1987-11-06',
  'MATCHUP': 'ATL vs. WAS',
  'WL': 'W',
  'MIN': 240,
  'FGM': 45,
  'FGA': 86,
  'FG_PCT': 0.523,
  'FG3M': 1,
  'FG3A': 5,
  'FG3_PCT': 0.2,
  'FTM': 23,
  'FTA': 34,
  'FT_PCT': 0.676,
  'OREB': 19,
  'DREB': 39,
  'REB': 58,
  'AST': 30,
  'STL': 9,
  'BLK': 8,
  'TOV': 17,
  'PF': 33,
  'PTS': 114,
  'PLUS_MINUS': 17,
  'VIDEO_AVAILABLE': 0},
 {'SEASON_ID': '21987',
  'TEAM_ID': 1610612738,
  'TEAM_ABBREVIATION': 'BOS',
  'TEAM_NAME': 'Boston Celtics',
  'GAME_ID': '0028700008',
  'GAME_DATE': '1987-11-06',
  'MATCHUP': 'BOS vs. MIL',
  'WL': 'W',
  'MIN': 240,
  'FGM': 52,
  'FGA': 105,
  'FG_PCT': 0.495,
  'FG3M': 3,
  'FG3A': 11,
  'FG3_PCT': 0.273,
  'FTM': 18,
  'FTA': 24,
  'FT_PCT': 0.75,
  'OREB': 23,
  'DREB': 34,
  'REB': 57,
  'AST': 38,
  'STL': 6,
  'BLK': 6,
  'TOV': 16,
  'PF': 26,
  'PTS': 125,
  'PLUS_MINUS': 17,
  'VIDEO_AVAILABLE': 0},
 {'SEASON_ID': '21987',
  'TEAM_ID': 1610612743,
  'TEAM_ABBREVIATION': 'DEN',
  'TEAM_NAME': 'Denver Nuggets',
  'GAME_ID': '0028700005',
  'GAME_DATE': '1987-11-06',
  'MATCHUP': 'DEN vs. LAC',
  'WL': 'W',
  'MIN': 240,
  'FGM': 53,
  'FGA': 103,
  'FG_PCT': 0.515,
  'FG3M': 1,
  'FG3A': 1,
  'FG3_PCT': 1.0,
  'FTM': 32,
  'FTA': 37,
  'FT_PCT': 0.865,
  'OREB': 12,
  'DREB': 45,
  'REB': 57,
  'AST': 37,
  'STL': 12,
  'BLK': 7,
  'TOV': 17,
  'PF': 25,
  'PTS': 139,
  'PLUS_MINUS': 46,
  'VIDEO_AVAILABLE': 0},
 {'SEASON_ID': '21987',
  'TEAM_ID': 1610612745,
  'TEAM_ABBREVIATION': 'HOU',
  'TEAM_NAME': 'Houston Rockets',
  'GAME_ID': '0028700009',
  'GAME_DATE': '1987-11-06',
  'MATCHUP': 'HOU vs. SAN',
  'WL': 'W',
  'MIN': 240,
  'FGM': 45,
  'FGA': 93,
  'FG_PCT': 0.484,
  'FG3M': 0,
  'FG3A': 5,
  'FG3_PCT': 0.0,
  'FTM': 18,
  'FTA': 25,
  'FT_PCT': 0.72,
  'OREB': 14,
  'DREB': 27,
  'REB': 41,
  'AST': 25,
  'STL': 12,
  'BLK': 4,
  'TOV': 20,
  'PF': 20,
  'PTS': 108,
  'PLUS_MINUS': 6,
  'VIDEO_AVAILABLE': 0},
 {'SEASON_ID': '21987',
  'TEAM_ID': 1610612751,
  'TEAM_ABBREVIATION': 'NJN',
  'TEAM_NAME': 'New Jersey Nets',
  'GAME_ID': '0028700006',
  'GAME_DATE': '1987-11-06',
  'MATCHUP': 'NJN vs. CLE',
  'WL': 'L',
  'MIN': 240,
  'FGM': 40,
  'FGA': 97,
  'FG_PCT': 0.412,
  'FG3M': 0,
  'FG3A': 4,
  'FG3_PCT': 0.0,
  'FTM': 28,
  'FTA': 41,
  'FT_PCT': 0.683,
  'OREB': 23,
  'DREB': 28,
  'REB': 51,
  'AST': 22,
  'STL': 12,
  'BLK': 11,
  'TOV': 19,
  'PF': 25,
  'PTS': 108,
  'PLUS_MINUS': -6,
  'VIDEO_AVAILABLE': 0},
 {'SEASON_ID': '21987',
  'TEAM_ID': 1610612755,
  'TEAM_ABBREVIATION': 'PHL',
  'TEAM_NAME': 'Philadelphia 76ers',
  'GAME_ID': '0028700003',
  'GAME_DATE': '1987-11-06',
  'MATCHUP': 'PHL vs. IND',
  'WL': 'W',
  'MIN': 240,
  'FGM': 43,
  'FGA': 79,
  'FG_PCT': 0.544,
  'FG3M': 1,
  'FG3A': 2,
  'FG3_PCT': 0.5,
  'FTM': 21,
  'FTA': 32,
  'FT_PCT': 0.656,
  'OREB': 16,
  'DREB': 29,
  'REB': 45,
  'AST': 25,
  'STL': 13,
  'BLK': 5,
  'TOV': 17,
  'PF': 15,
  'PTS': 108,
  'PLUS_MINUS': 13,
  'VIDEO_AVAILABLE': 0},
 {'SEASON_ID': '21987',
  'TEAM_ID': 1610612756,
  'TEAM_ABBREVIATION': 'PHX',
  'TEAM_NAME': 'Phoenix Suns',
  'GAME_ID': '0028700011',
  'GAME_DATE': '1987-11-06',
  'MATCHUP': 'PHX @ POR',
  'WL': 'L',
  'MIN': 240,
  'FGM': 42,
  'FGA': 84,
  'FG_PCT': 0.5,
  'FG3M': 0,
  'FG3A': 4,
  'FG3_PCT': 0.0,
  'FTM': 20,
  'FTA': 24,
  'FT_PCT': 0.833,
  'OREB': 11,
  'DREB': 27,
  'REB': 38,
  'AST': 29,
  'STL': 12,
  'BLK': 2,
  'TOV': 27,
  'PF': 31,
  'PTS': 104,
  'PLUS_MINUS': -14,
  'VIDEO_AVAILABLE': 0},
 {'SEASON_ID': '21987',
  'TEAM_ID': 1610612757,
  'TEAM_ABBREVIATION': 'POR',
  'TEAM_NAME': 'Portland Trail Blazers',
  'GAME_ID': '0028700011',
  'GAME_DATE': '1987-11-06',
  'MATCHUP': 'POR vs. PHX',
  'WL': 'W',
  'MIN': 240,
  'FGM': 44,
  'FGA': 72,
  'FG_PCT': 0.611,
  'FG3M': 2,
  'FG3A': 4,
  'FG3_PCT': 0.5,
  'FTM': 28,
  'FTA': 42,
  'FT_PCT': 0.667,
  'OREB': 8,
  'DREB': 27,
  'REB': 35,
  'AST': 30,
  'STL': 7,
  'BLK': 5,
  'TOV': 24,
  'PF': 21,
  'PTS': 118,
  'PLUS_MINUS': 14,
  'VIDEO_AVAILABLE': 0},
 {'SEASON_ID': '21987',
  'TEAM_ID': 1610612758,
  'TEAM_ABBREVIATION': 'SAC',
  'TEAM_NAME': 'Sacramento Kings',
  'GAME_ID': '0028700001',
  'GAME_DATE': '1987-11-06',
  'MATCHUP': 'SAC vs. GOS',
  'WL': 'W',
  'MIN': 240,
  'FGM': 50,
  'FGA': 87,
  'FG_PCT': 0.575,
  'FG3M': 0,
  'FG3A': 2,
  'FG3_PCT': 0.0,
  'FTM': 34,
  'FTA': 46,
  'FT_PCT': 0.739,
  'OREB': 15,
  'DREB': 42,
  'REB': 57,
  'AST': 18,
  'STL': 6,
  'BLK': 5,
  'TOV': 20,
  'PF': 20,
  'PTS': 134,
  'PLUS_MINUS': 28,
  'VIDEO_AVAILABLE': 0},
 {'SEASON_ID': '21987',
  'TEAM_ID': 1610612762,
  'TEAM_ABBREVIATION': 'UTH',
  'TEAM_NAME': 'Utah Jazz',
  'GAME_ID': '0028700002',
  'GAME_DATE': '1987-11-06',
  'MATCHUP': 'UTH @ DAL',
  'WL': 'L',
  'MIN': 240,
  'FGM': 38,
  'FGA': 85,
  'FG_PCT': 0.447,
  'FG3M': 1,
  'FG3A': 6,
  'FG3_PCT': 0.167,
  'FTM': 16,
  'FTA': 25,
  'FT_PCT': 0.64,
  'OREB': 13,
  'DREB': 37,
  'REB': 50,
  'AST': 27,
  'STL': 4,
  'BLK': 12,
  'TOV': 24,
  'PF': 29,
  'PTS': 93,
  'PLUS_MINUS': -2,
  'VIDEO_AVAILABLE': 0},
 {'SEASON_ID': '21987',
  'TEAM_ID': 1610612764,
  'TEAM_ABBREVIATION': 'WAS',
  'TEAM_NAME': 'Washington Bullets',
  'GAME_ID': '0028700007',
  'GAME_DATE': '1987-11-06',
  'MATCHUP': 'WAS @ ATL',
  'WL': 'L',
  'MIN': 240,
  'FGM': 32,
  'FGA': 80,
  'FG_PCT': 0.4,
  'FG3M': 1,
  'FG3A': 1,
  'FG3_PCT': 1.0,
  'FTM': 32,
  'FTA': 43,
  'FT_PCT': 0.744,
  'OREB': 12,
  'DREB': 25,
  'REB': 37,
  'AST': 17,
  'STL': 7,
  'BLK': 3,
  'TOV': 15,
  'PF': 28,
  'PTS': 97,
  'PLUS_MINUS': -17,
  'VIDEO_AVAILABLE': 0},
 {'SEASON_ID': '21987',
  'TEAM_ID': 1610612739,
  'TEAM_ABBREVIATION': 'CLE',
  'TEAM_NAME': 'Cleveland Cavaliers',
  'GAME_ID': '0028700006',
  'GAME_DATE': '1987-11-06',
  'MATCHUP': 'CLE @ NJN',
  'WL': 'W',
  'MIN': 240,
  'FGM': 47,
  'FGA': 82,
  'FG_PCT': 0.573,
  'FG3M': 2,
  'FG3A': 3,
  'FG3_PCT': 0.667,
  'FTM': 18,
  'FTA': 32,
  'FT_PCT': 0.563,
  'OREB': 11,
  'DREB': 35,
  'REB': 46,
  'AST': 27,
  'STL': 14,
  'BLK': 10,
  'TOV': 27,
  'PF': 35,
  'PTS': 114,
  'PLUS_MINUS': 6,
  'VIDEO_AVAILABLE': 0},
 {'SEASON_ID': '21987',
  'TEAM_ID': 1610612742,
  'TEAM_ABBREVIATION': 'DAL',
  'TEAM_NAME': 'Dallas Mavericks',
  'GAME_ID': '0028700002',
  'GAME_DATE': '1987-11-06',
  'MATCHUP': 'DAL vs. UTH',
  'WL': 'W',
  'MIN': 240,
  'FGM': 33,
  'FGA': 95,
  'FG_PCT': 0.347,
  'FG3M': 1,
  'FG3A': 6,
  'FG3_PCT': 0.167,
  'FTM': 28,
  'FTA': 39,
  'FT_PCT': 0.718,
  'OREB': 20,
  'DREB': 32,
  'REB': 52,
  'AST': 20,
  'STL': 9,
  'BLK': 7,
  'TOV': 14,
  'PF': 27,
  'PTS': 95,
  'PLUS_MINUS': 2,
  'VIDEO_AVAILABLE': 0},
 {'SEASON_ID': '21987',
  'TEAM_ID': 1610612744,
  'TEAM_ABBREVIATION': 'GOS',
  'TEAM_NAME': 'Golden State Warriors',
  'GAME_ID': '0028700001',
  'GAME_DATE': '1987-11-06',
  'MATCHUP': 'GOS @ SAC',
  'WL': 'L',
  'MIN': 240,
  'FGM': 44,
  'FGA': 104,
  'FG_PCT': 0.423,
  'FG3M': 0,
  'FG3A': 0,
  'FG3_PCT': None,
  'FTM': 18,
  'FTA': 19,
  'FT_PCT': 0.947,
  'OREB': 11,
  'DREB': 25,
  'REB': 36,
  'AST': 14,
  'STL': 13,
  'BLK': 2,
  'TOV': 12,
  'PF': 33,
  'PTS': 106,
  'PLUS_MINUS': -28,
  'VIDEO_AVAILABLE': 0},
 {'SEASON_ID': '21987',
  'TEAM_ID': 1610612746,
  'TEAM_ABBREVIATION': 'LAC',
  'TEAM_NAME': 'Los Angeles Clippers',
  'GAME_ID': '0028700005',
  'GAME_DATE': '1987-11-06',
  'MATCHUP': 'LAC @ DEN',
  'WL': 'L',
  'MIN': 240,
  'FGM': 36,
  'FGA': 94,
  'FG_PCT': 0.383,
  'FG3M': 3,
  'FG3A': 7,
  'FG3_PCT': 0.429,
  'FTM': 18,
  'FTA': 28,
  'FT_PCT': 0.643,
  'OREB': 12,
  'DREB': 25,
  'REB': 37,
  'AST': 22,
  'STL': 7,
  'BLK': 7,
  'TOV': 25,
  'PF': 33,
  'PTS': 93,
  'PLUS_MINUS': -46,
  'VIDEO_AVAILABLE': 0},
 {'SEASON_ID': '21987',
  'TEAM_ID': 1610612747,
  'TEAM_ABBREVIATION': 'LAL',
  'TEAM_NAME': 'Los Angeles Lakers',
  'GAME_ID': '0028700004',
  'GAME_DATE': '1987-11-06',
  'MATCHUP': 'LAL vs. SEA',
  'WL': 'W',
  'MIN': 240,
  'FGM': 37,
  'FGA': 76,
  'FG_PCT': 0.487,
  'FG3M': 2,
  'FG3A': 5,
  'FG3_PCT': 0.4,
  'FTM': 37,
  'FTA': 45,
  'FT_PCT': 0.822,
  'OREB': 12,
  'DREB': 33,
  'REB': 45,
  'AST': 21,
  'STL': 9,
  'BLK': 4,
  'TOV': 23,
  'PF': 20,
  'PTS': 113,
  'PLUS_MINUS': 4,
  'VIDEO_AVAILABLE': 0},
 {'SEASON_ID': '21987',
  'TEAM_ID': 1610612749,
  'TEAM_ABBREVIATION': 'MIL',
  'TEAM_NAME': 'Milwaukee Bucks',
  'GAME_ID': '0028700008',
  'GAME_DATE': '1987-11-06',
  'MATCHUP': 'MIL @ BOS',
  'WL': 'L',
  'MIN': 240,
  'FGM': 37,
  'FGA': 85,
  'FG_PCT': 0.435,
  'FG3M': 2,
  'FG3A': 7,
  'FG3_PCT': 0.286,
  'FTM': 32,
  'FTA': 37,
  'FT_PCT': 0.865,
  'OREB': 7,
  'DREB': 24,
  'REB': 31,
  'AST': 18,
  'STL': 8,
  'BLK': 5,
  'TOV': 12,
  'PF': 28,
  'PTS': 108,
  'PLUS_MINUS': -17,
  'VIDEO_AVAILABLE': 0},
 {'SEASON_ID': '21987',
  'TEAM_ID': 1610612760,
  'TEAM_ABBREVIATION': 'SEA',
  'TEAM_NAME': 'Seattle SuperSonics',
  'GAME_ID': '0028700004',
  'GAME_DATE': '1987-11-06',
  'MATCHUP': 'SEA @ LAL',
  'WL': 'L',
  'MIN': 240,
  'FGM': 46,
  'FGA': 98,
  'FG_PCT': 0.469,
  'FG3M': 1,
  'FG3A': 6,
  'FG3_PCT': 0.167,
  'FTM': 16,
  'FTA': 22,
  'FT_PCT': 0.727,
  'OREB': 17,
  'DREB': 29,
  'REB': 46,
  'AST': 24,
  'STL': 15,
  'BLK': 4,
  'TOV': 19,
  'PF': 35,
  'PTS': 109,
  'PLUS_MINUS': -4,
  'VIDEO_AVAILABLE': 0},
 {'SEASON_ID': '21987',
  'TEAM_ID': 1610612765,
  'TEAM_ABBREVIATION': 'DET',
  'TEAM_NAME': 'Detroit Pistons',
  'GAME_ID': '0028700010',
  'GAME_DATE': '1987-11-06',
  'MATCHUP': 'DET vs. NYK',
  'WL': 'W',
  'MIN': 240,
  'FGM': 32,
  'FGA': 69,
  'FG_PCT': 0.464,
  'FG3M': 1,
  'FG3A': 2,
  'FG3_PCT': 0.5,
  'FTM': 45,
  'FTA': 58,
  'FT_PCT': 0.776,
  'OREB': 12,
  'DREB': 36,
  'REB': 48,
  'AST': 17,
  'STL': 12,
  'BLK': 5,
  'TOV': 26,
  'PF': 29,
  'PTS': 110,
  'PLUS_MINUS': 11,
  'VIDEO_AVAILABLE': 0},
 {'SEASON_ID': '21987',
  'TEAM_ID': 1610612752,
  'TEAM_ABBREVIATION': 'NYK',
  'TEAM_NAME': 'New York Knicks',
  'GAME_ID': '0028700010',
  'GAME_DATE': '1987-11-06',
  'MATCHUP': 'NYK @ DET',
  'WL': 'L',
  'MIN': 240,
  'FGM': 40,
  'FGA': 84,
  'FG_PCT': 0.476,
  'FG3M': 1,
  'FG3A': 3,
  'FG3_PCT': 0.333,
  'FTM': 18,
  'FTA': 25,
  'FT_PCT': 0.72,
  'OREB': 9,
  'DREB': 27,
  'REB': 36,
  'AST': 26,
  'STL': 10,
  'BLK': 4,
  'TOV': 30,
  'PF': 43,
  'PTS': 99,
  'PLUS_MINUS': -11,
  'VIDEO_AVAILABLE': 0},
 {'SEASON_ID': '21987',
  'TEAM_ID': 1610612754,
  'TEAM_ABBREVIATION': 'IND',
  'TEAM_NAME': 'Indiana Pacers',
  'GAME_ID': '0028700003',
  'GAME_DATE': '1987-11-06',
  'MATCHUP': 'IND @ PHL',
  'WL': 'L',
  'MIN': 240,
  'FGM': 41,
  'FGA': 85,
  'FG_PCT': 0.482,
  'FG3M': 3,
  'FG3A': 5,
  'FG3_PCT': 0.6,
  'FTM': 10,
  'FTA': 14,
  'FT_PCT': 0.714,
  'OREB': 13,
  'DREB': 28,
  'REB': 41,
  'AST': 26,
  'STL': 7,
  'BLK': 6,
  'TOV': 20,
  'PF': 26,
  'PTS': 95,
  'PLUS_MINUS': -13,
  'VIDEO_AVAILABLE': 0},
 {'SEASON_ID': '21987',
  'TEAM_ID': 1610612759,
  'TEAM_ABBREVIATION': 'SAN',
  'TEAM_NAME': 'San Antonio Spurs',
  'GAME_ID': '0028700009',
  'GAME_DATE': '1987-11-06',
  'MATCHUP': 'SAN @ HOU',
  'WL': 'L',
  'MIN': 240,
  'FGM': 45,
  'FGA': 89,
  'FG_PCT': 0.506,
  'FG3M': 0,
  'FG3A': 2,
  'FG3_PCT': 0.0,
  'FTM': 12,
  'FTA': 14,
  'FT_PCT': 0.857,
  'OREB': 13,
  'DREB': 30,
  'REB': 43,
  'AST': 23,
  'STL': 12,
  'BLK': 2,
  'TOV': 27,
  'PF': 25,
  'PTS': 102,
  'PLUS_MINUS': -6,
  'VIDEO_AVAILABLE': 0},
 {'SEASON_ID': '21987',
  'TEAM_ID': 1610612737,
  'TEAM_ABBREVIATION': 'ATL',
  'TEAM_NAME': 'Atlanta Hawks',
  'GAME_ID': '0028700014',
  'GAME_DATE': '1987-11-07',
  'MATCHUP': 'ATL vs. CLE',
  'WL': 'W',
  'MIN': 240,
  'FGM': 37,
  'FGA': 87,
  'FG_PCT': 0.425,
  'FG3M': 0,
  'FG3A': 2,
  'FG3_PCT': 0.0,
  'FTM': 39,
  'FTA': 50,
  'FT_PCT': 0.78,
  'OREB': 20,
  'DREB': 34,
  'REB': 54,
  'AST': 24,
  'STL': 10,
  'BLK': 5,
  'TOV': 22,
  'PF': 38,
  'PTS': 113,
  'PLUS_MINUS': 8,
  'VIDEO_AVAILABLE': 0},
 {'SEASON_ID': '21987',
  'TEAM_ID': 1610612738,
  'TEAM_ABBREVIATION': 'BOS',
  'TEAM_NAME': 'Boston Celtics',
  'GAME_ID': '0028700020',
  'GAME_DATE': '1987-11-07',
  'MATCHUP': 'BOS @ WAS',
  'WL': 'W',
  'MIN': 290,
  'FGM': 56,
  'FGA': 99,
  'FG_PCT': 0.566,
  'FG3M': 3,
  'FG3A': 7,
  'FG3_PCT': 0.429,
  'FTM': 25,
  'FTA': 33,
  'FT_PCT': 0.758,
  'OREB': 14,
  'DREB': 30,
  'REB': 44,
  'AST': 44,
  'STL': 7,
  'BLK': 5,
  'TOV': 26,
  'PF': 31,
  'PTS': 140,
  'PLUS_MINUS': 1,
  'VIDEO_AVAILABLE': 0},
 {'SEASON_ID': '21987',
  'TEAM_ID': 1610612742,
  'TEAM_ABBREVIATION': 'DAL',
  'TEAM_NAME': 'Dallas Mavericks',
  'GAME_ID': '0028700017',
  'GAME_DATE': '1987-11-07',
  'MATCHUP': 'DAL @ SAN',
  'WL': 'L',
  'MIN': 240,
  'FGM': 40,
  'FGA': 96,
  'FG_PCT': 0.417,
  'FG3M': 0,
  'FG3A': 3,
  'FG3_PCT': 0.0,
  'FTM': 26,
  'FTA': 31,
  'FT_PCT': 0.839,
  'OREB': 14,
  'DREB': 25,
  'REB': 39,
  'AST': 24,
  'STL': 10,
  'BLK': 10,
  'TOV': 17,
  'PF': 21,
  'PTS': 106,
  'PLUS_MINUS': -24,
  'VIDEO_AVAILABLE': 0},
 {'SEASON_ID': '21987',
  'TEAM_ID': 1610612743,
  'TEAM_ABBREVIATION': 'DEN',
  'TEAM_NAME': 'Denver Nuggets',
  'GAME_ID': '0028700019',
  'GAME_DATE': '1987-11-07',
  'MATCHUP': 'DEN @ GOS',
  'WL': 'W',
  'MIN': 240,
  'FGM': 38,
  'FGA': 85,
  'FG_PCT': 0.447,
  'FG3M': 0,
  'FG3A': 0,
  'FG3_PCT': None,
  'FTM': 27,
  'FTA': 37,
  'FT_PCT': 0.73,
  'OREB': 12,
  'DREB': 32,
  'REB': 44,
  'AST': 18,
  'STL': 12,
  'BLK': 4,
  'TOV': 17,
  'PF': 31,
  'PTS': 103,
  'PLUS_MINUS': 4,
  'VIDEO_AVAILABLE': 0},
 {'SEASON_ID': '21987',
  'TEAM_ID': 1610612744,
  'TEAM_ABBREVIATION': 'GOS',
  'TEAM_NAME': 'Golden State Warriors',
  'GAME_ID': '0028700019',
  'GAME_DATE': '1987-11-07',
  'MATCHUP': 'GOS vs. DEN',
  'WL': 'L',
  'MIN': 240,
  'FGM': 32,
  'FGA': 81,
  'FG_PCT': 0.395,
  'FG3M': 0,
  'FG3A': 4,
  'FG3_PCT': 0.0,
  'FTM': 35,
  'FTA': 42,
  'FT_PCT': 0.833,
  'OREB': 12,
  'DREB': 39,
  'REB': 51,
  'AST': 16,
  'STL': 8,
  'BLK': 2,
  'TOV': 20,
  'PF': 33,
  'PTS': 99,
  'PLUS_MINUS': -4,
  'VIDEO_AVAILABLE': 0},
 {'SEASON_ID': '21987',
  'TEAM_ID': 1610612754,
  'TEAM_ABBREVIATION': 'IND',
  'TEAM_NAME': 'Indiana Pacers',
  'GAME_ID': '0028700013',
  'GAME_DATE': '1987-11-07',
  'MATCHUP': 'IND vs. NYK',
  'WL': 'W',
  'MIN': 240,
  'FGM': 37,
  'FGA': 80,
  'FG_PCT': 0.463,
  'FG3M': 3,
  'FG3A': 6,
  'FG3_PCT': 0.5,
  'FTM': 31,
  'FTA': 33,
  'FT_PCT': 0.939,
  'OREB': 14,
  'DREB': 35,
  'REB': 49,
  'AST': 25,
  'STL': 9,
  'BLK': 8,
  'TOV': 25,
  'PF': 30,
  'PTS': 108,
  'PLUS_MINUS': 13,
  'VIDEO_AVAILABLE': 0},
 {'SEASON_ID': '21987',
  'TEAM_ID': 1610612755,
  'TEAM_ABBREVIATION': 'PHL',
  'TEAM_NAME': 'Philadelphia 76ers',
  'GAME_ID': '0028700016',
  'GAME_DATE': '1987-11-07',
  'MATCHUP': 'PHL @ CHI',
  'WL': 'L',
  'MIN': 240,
  'FGM': 38,
  'FGA': 78,
  'FG_PCT': 0.487,
  'FG3M': 2,
  'FG3A': 4,
  'FG3_PCT': 0.5,
  'FTM': 16,
  'FTA': 23,
  'FT_PCT': 0.696,
  'OREB': 14,
  'DREB': 22,
  'REB': 36,
  'AST': 17,
  'STL': 9,
  'BLK': 5,
  'TOV': 22,
  'PF': 22,
  'PTS': 94,
  'PLUS_MINUS': -10,
  'VIDEO_AVAILABLE': 0},
 {'SEASON_ID': '21987',
  'TEAM_ID': 1610612757,
  'TEAM_ABBREVIATION': 'POR',
  'TEAM_NAME': 'Portland Trail Blazers',
  'GAME_ID': '0028700015',
  'GAME_DATE': '1987-11-07',
  'MATCHUP': 'POR @ LAC',
  'WL': 'W',
  'MIN': 240,
  'FGM': 46,
  'FGA': 82,
  'FG_PCT': 0.561,
  'FG3M': 2,
  'FG3A': 2,
  'FG3_PCT': 1.0,
  'FTM': 30,
  'FTA': 44,
  'FT_PCT': 0.682,
  'OREB': 15,
  'DREB': 45,
  'REB': 60,
  'AST': 34,
  'STL': 5,
  'BLK': 7,
  'TOV': 22,
  'PF': 27,
  'PTS': 124,
  'PLUS_MINUS': 25,
  'VIDEO_AVAILABLE': 0},
 {'SEASON_ID': '21987',
  'TEAM_ID': 1610612759,
  'TEAM_ABBREVIATION': 'SAN',
  'TEAM_NAME': 'San Antonio Spurs',
  'GAME_ID': '0028700017',
  'GAME_DATE': '1987-11-07',
  'MATCHUP': 'SAN vs. DAL',
  'WL': 'W',
  'MIN': 240,
  'FGM': 55,
  'FGA': 102,
  'FG_PCT': 0.539,
  'FG3M': 0,
  'FG3A': 2,
  'FG3_PCT': 0.0,
  'FTM': 20,
  'FTA': 25,
  'FT_PCT': 0.8,
  'OREB': 15,
  'DREB': 40,
  'REB': 55,
  'AST': 42,
  'STL': 9,
  'BLK': 9,
  'TOV': 17,
  'PF': 23,
  'PTS': 130,
  'PLUS_MINUS': 24,
  'VIDEO_AVAILABLE': 0},
 {'SEASON_ID': '21987',
  'TEAM_ID': 1610612762,
  'TEAM_ABBREVIATION': 'UTH',
  'TEAM_NAME': 'Utah Jazz',
  'GAME_ID': '0028700021',
  'GAME_DATE': '1987-11-07',
  'MATCHUP': 'UTH vs. SAC',
  'WL': 'W',
  'MIN': 240,
  'FGM': 51,
  'FGA': 94,
  'FG_PCT': 0.543,
  'FG3M': 2,
  'FG3A': 4,
  'FG3_PCT': 0.5,
  'FTM': 17,
  'FTA': 21,
  'FT_PCT': 0.81,
  'OREB': 13,
  'DREB': 26,
  'REB': 39,
  'AST': 27,
  'STL': 16,
  'BLK': 10,
  'TOV': 22,
  'PF': 28,
  'PTS': 121,
  'PLUS_MINUS': 21,
  'VIDEO_AVAILABLE': 0},
 {'SEASON_ID': '21987',
  'TEAM_ID': 1610612764,
  'TEAM_ABBREVIATION': 'WAS',
  'TEAM_NAME': 'Washington Bullets',
  'GAME_ID': '0028700020',
  'GAME_DATE': '1987-11-07',
  'MATCHUP': 'WAS vs. BOS',
  'WL': 'L',
  'MIN': 290,
  'FGM': 53,
  'FGA': 105,
  'FG_PCT': 0.505,
  'FG3M': 0,
  'FG3A': 0,
  'FG3_PCT': None,
  'FTM': 33,
  'FTA': 41,
  'FT_PCT': 0.805,
  'OREB': 20,
  'DREB': 27,
  'REB': 47,
  'AST': 26,
  'STL': 13,
  'BLK': 2,
  'TOV': 22,
  'PF': 30,
  'PTS': 139,
  'PLUS_MINUS': -1,
  'VIDEO_AVAILABLE': 0},
 {'SEASON_ID': '21987',
  'TEAM_ID': 1610612741,
  'TEAM_ABBREVIATION': 'CHI',
  'TEAM_NAME': 'Chicago Bulls',
  'GAME_ID': '0028700016',
  'GAME_DATE': '1987-11-07',
  'MATCHUP': 'CHI vs. PHL',
  'WL': 'W',
  'MIN': 240,
  'FGM': 41,
  'FGA': 80,
  'FG_PCT': 0.513,
  'FG3M': 0,
  'FG3A': 0,
  'FG3_PCT': None,
  'FTM': 22,
  'FTA': 29,
  'FT_PCT': 0.759,
  'OREB': 15,
  'DREB': 27,
  'REB': 42,
  'AST': 25,
  'STL': 14,
  'BLK': 6,
  'TOV': 20,
  'PF': 23,
  'PTS': 104,
  'PLUS_MINUS': 10,
  'VIDEO_AVAILABLE': 0},
 {'SEASON_ID': '21987',
  'TEAM_ID': 1610612749,
  'TEAM_ABBREVIATION': 'MIL',
  'TEAM_NAME': 'Milwaukee Bucks',
  'GAME_ID': '0028700012',
  'GAME_DATE': '1987-11-07',
  'MATCHUP': 'MIL vs. DET',
  'WL': 'W',
  'MIN': 240,
  'FGM': 41,
  'FGA': 96,
  'FG_PCT': 0.427,
  'FG3M': 2,
  'FG3A': 7,
  'FG3_PCT': 0.286,
  'FTM': 35,
  'FTA': 43,
  'FT_PCT': 0.814,
  'OREB': 16,
  'DREB': 35,
  'REB': 51,
  'AST': 27,
  'STL': 5,
  'BLK': 4,
  'TOV': 11,
  'PF': 38,
  'PTS': 119,
  'PLUS_MINUS': 14,
  'VIDEO_AVAILABLE': 0},
 {'SEASON_ID': '21987',
  'TEAM_ID': 1610612752,
  'TEAM_ABBREVIATION': 'NYK',
  'TEAM_NAME': 'New York Knicks',
  'GAME_ID': '0028700013',
  'GAME_DATE': '1987-11-07',
  'MATCHUP': 'NYK @ IND',
  'WL': 'L',
  'MIN': 240,
  'FGM': 37,
  'FGA': 90,
  'FG_PCT': 0.411,
  'FG3M': 0,
  'FG3A': 2,
  'FG3_PCT': 0.0,
  'FTM': 21,
  'FTA': 30,
  'FT_PCT': 0.7,
  'OREB': 18,
  'DREB': 27,
  'REB': 45,
  'AST': 16,
  'STL': 12,
  'BLK': 5,
  'TOV': 24,
  'PF': 34,
  'PTS': 95,
  'PLUS_MINUS': -13,
  'VIDEO_AVAILABLE': 0},
 {'SEASON_ID': '21987',
  'TEAM_ID': 1610612756,
  'TEAM_ABBREVIATION': 'PHX',
  'TEAM_NAME': 'Phoenix Suns',
  'GAME_ID': '0028700018',
  'GAME_DATE': '1987-11-07',
  'MATCHUP': 'PHX @ SEA',
  'WL': 'L',
  'MIN': 240,
  'FGM': 41,
  'FGA': 93,
  'FG_PCT': 0.441,
  'FG3M': 1,
  'FG3A': 4,
  'FG3_PCT': 0.25,
  'FTM': 13,
  'FTA': 19,
  'FT_PCT': 0.684,
  'OREB': 14,
  'DREB': 24,
  'REB': 38,
  'AST': 25,
  'STL': 9,
  'BLK': 3,
  'TOV': 20,
  'PF': 33,
  'PTS': 96,
  'PLUS_MINUS': -16,
  'VIDEO_AVAILABLE': 0},
 {'SEASON_ID': '21987',
  'TEAM_ID': 1610612760,
  'TEAM_ABBREVIATION': 'SEA',
  'TEAM_NAME': 'Seattle SuperSonics',
  'GAME_ID': '0028700018',
  'GAME_DATE': '1987-11-07',
  'MATCHUP': 'SEA vs. PHX',
  'WL': 'W',
  'MIN': 240,
  'FGM': 42,
  'FGA': 89,
  'FG_PCT': 0.472,
  'FG3M': 0,
  'FG3A': 2,
  'FG3_PCT': 0.0,
  'FTM': 28,
  'FTA': 36,
  'FT_PCT': 0.778,
  'OREB': 18,
  'DREB': 36,
  'REB': 54,
  'AST': 27,
  'STL': 5,
  'BLK': 4,
  'TOV': 23,
  'PF': 22,
  'PTS': 112,
  'PLUS_MINUS': 16,
  'VIDEO_AVAILABLE': 0},
 {'SEASON_ID': '21987',
  'TEAM_ID': 1610612765,
  'TEAM_ABBREVIATION': 'DET',
  'TEAM_NAME': 'Detroit Pistons',
  'GAME_ID': '0028700012',
  'GAME_DATE': '1987-11-07',
  'MATCHUP': 'DET @ MIL',
  'WL': 'L',

In [18]:
unique_game_ids = list(set([game["GAME_ID"] for game in games_]))
len(unique_game_ids)

943

In [19]:
len(games_)

1886

In [20]:
from nba_api.stats.endpoints import boxscoretraditionalv3

box = boxscoretraditionalv3.BoxScoreTraditionalV3(game_id="0028500005")

data = box.get_data_frames()

In [21]:
data[0]

,gameId,teamId,teamCity,teamName,teamTricode,teamSlug,personId,firstName,familyName,nameI,...,reboundsOffensive,reboundsDefensive,reboundsTotal,assists,steals,blocks,turnovers,foulsPersonal,points,plusMinusPoints
0,0028500005,1610612737,Atlanta,Hawks,ATL,hawks,76384,Lorenzo,Charles,L. Charles,...,0,1,1,0,0,0,0,0,4,0.0
1,0028500005,1610612737,Atlanta,Hawks,ATL,hawks,76968,Scott,Hastings,S. Hastings,...,2,3,5,1,2,0,1,0,4,0.0
2,0028500005,1610612737,Atlanta,Hawks,ATL,hawks,402,Jon,Koncak,J. Koncak,...,1,0,1,0,0,0,0,4,3,0.0
3,0028500005,1610612737,Atlanta,Hawks,ATL,hawks,77377,Cliff,Levingston,C. Levingston,...,2,4,6,4,1,2,2,4,8,0.0
4,0028500005,1610612737,Atlanta,Hawks,ATL,hawks,78014,Tree,Rollins,T. Rollins,...,1,8,9,0,0,3,1,2,9,0.0
5,0028500005,1610612737,Atlanta,Hawks,ATL,hawks,78352,Sedric,Toney,S. Toney,...,0,2,2,0,0,0,3,3,0,0.0
6,0028500005,1610612737,Atlanta,Hawks,ATL,hawks,892,Spud,Webb,S. Webb,...,0,3,3,10,1,0,3,4,12,0.0
7,0028500005,1610612737,Atlanta,Hawks,ATL,hawks,1122,Dominique,Wilkins,D. Wilkins,...,5,1,6,4,3,0,5,2,32,0.0
8,0028500005,1610612737,Atlanta,Hawks,ATL,hawks,78571,Ray,Williams,R. Williams,...,0,0,0,3,1,0,0,1,0,0.0
9,0028500005,1610612737,Atlanta,Hawks,ATL,hawks,788,Kevin,Willis,K. Willis,...,3,5,8,0,0,0,1,3,13,0.0
10,0028500005,1610612737,Atlanta,Hawks,ATL,hawks,1456,Randy,Wittman,R. Wittman,...,2,1,3,3,0,0,0,0,6,0.0
11,0028500005,1610612764,Washington,Bullets,WAS,bullets,76195,Manute,Bol,M. Bol,...,0,0,0,0,0,0,0,2,0,0.0
12,0028500005,1610612764,Washington,Bullets,WAS,bullets,76231,Dudley,Bradley,D. Bradley,...,0,0,0,1,1,0,0,0,0,0.0
13,0028500005,1610612764,Washington,Bullets,WAS,bullets,76543,Darren,Daye,D. Daye,...,0,2,2,0,1,0,0,2,5,0.0
14,0028500005,1610612764,Washington,Bullets,WAS,bullets,279,Charles,Jones,C. Jones,...,2,6,8,2,0,4,1,2,4,0.0
15,0028500005,1610612764,Washington,Bullets,WAS,bullets,117,Jeff,Malone,J. Malone,...,0,2,2,1,0,0,2,2,18,0.0
16,0028500005,1610612764,Washington,Bullets,WAS,bullets,77553,Tom,McMillen,T. McMillen,...,0,0,0,0,0,0,0,1,2,0.0
17,0028500005,1610612764,Washington,Bullets,WAS,bullets,77654,Perry,Moss,P. Moss,...,0,0,0,1,2,0,1,2,7,0.0
18,0028500005,1610612764,Washington,Bullets,WAS,bullets,77986,Cliff T.,Robinson,C. Robinson,...,1,7,8,2,3,1,5,1,22,0.0
19,0028500005,1610612764,Washington,Bullets,WAS,bullets,78025,Dan,Roundfield,D. Roundfield,...,2,4,6,1,1,0,2,4,2,0.0
20,0028500005,1610612764,Washington,Bullets,WAS,bullets,78041,Jeff,Ruland,J. Ruland,...,6,8,14,9,1,2,5,3,19,0.0
21,0028500005,1610612764,Washington,Bullets,WAS,bullets,78549,Gus,Williams,G. Williams,...,0,0,0,4,2,0,1,0,21,0.0

In [22]:
data[0]["personId"].tolist()

[76384,
 76968,
 402,
 77377,
 78014,
 78352,
 892,
 1122,
 78571,
 788,
 1456,
 76195,
 76231,
 76543,
 279,
 117,
 77553,
 77654,
 77986,
 78025,
 78041,
 78549]

In [23]:
from nba_api.stats.endpoints import commonplayerinfo

player_info = commonplayerinfo.CommonPlayerInfo(player_id=2)

data = json.loads(player_info.get_normalized_json())

In [24]:
data["CommonPlayerInfo"][0]

{'PERSON_ID': 2,
 'FIRST_NAME': 'Byron',
 'LAST_NAME': 'Scott',
 'DISPLAY_FIRST_LAST': 'Byron Scott',
 'DISPLAY_LAST_COMMA_FIRST': 'Scott, Byron',
 'DISPLAY_FI_LAST': 'B. Scott',
 'PLAYER_SLUG': 'byron-scott',
 'BIRTHDATE': '1961-03-28T00:00:00',
 'SCHOOL': 'Arizona State',
 'COUNTRY': 'USA',
 'LAST_AFFILIATION': 'Arizona State/USA',
 'HEIGHT': '6-4',
 'WEIGHT': '205',
 'SEASON_EXP': 14,
 'JERSEY': '',
 'POSITION': 'Guard',
 'ROSTERSTATUS': 'Inactive',
 'GAMES_PLAYED_CURRENT_SEASON_FLAG': 'N',
 'TEAM_ID': 1610612747,
 'TEAM_NAME': 'Lakers',
 'TEAM_ABBREVIATION': 'LAL',
 'TEAM_CODE': 'lakers',
 'TEAM_CITY': 'Los Angeles',
 'PLAYERCODE': 'byron_scott',
 'FROM_YEAR': 1983,
 'TO_YEAR': 1996,
 'DLEAGUE_FLAG': 'N',
 'NBA_FLAG': 'Y',
 'GAMES_PLAYED_FLAG': 'Y',
 'DRAFT_YEAR': '1983',
 'DRAFT_ROUND': '1',
 'DRAFT_NUMBER': '4',
 'GREATEST_75_FLAG': 'N'}

In [25]:
import pandas as pd
from nba_api.stats.endpoints import commonplayerinfo

In [26]:
df = pd.read_csv("raw_data/unique_player_ids/unique_player_ids.csv")

player_ids = df["player_id"].tolist()
len(player_ids)

1038

In [40]:
from pyspark.sql import SparkSession


spark = (SparkSession.builder
         .master("local[*]")
         .appName("Load_Players")
         .config("spark.jars", "file:///C:/spark-jars/mssql-jdbc-13.4.0.jre11.jar")
         .getOrCreate()
)

In [28]:
df_1 = spark.read.format("json").option("multiline", True).option("path","raw_data/players_info/players_info.json").load()

In [29]:
df_1.show()

+-------------------+-----------+------------------+---------------+------------------------+------------+------------+-----------+----------+----------+---------+--------------------------------+-----------------+----------------+------+------+--------------------+----------+--------+---------+--------------------+----------------+-------------+------------+--------------------+----------+-----------------+------------+---------+----------+-------------+-------+------+
|          BIRTHDATE|    COUNTRY|DISPLAY_FIRST_LAST|DISPLAY_FI_LAST|DISPLAY_LAST_COMMA_FIRST|DLEAGUE_FLAG|DRAFT_NUMBER|DRAFT_ROUND|DRAFT_YEAR|FIRST_NAME|FROM_YEAR|GAMES_PLAYED_CURRENT_SEASON_FLAG|GAMES_PLAYED_FLAG|GREATEST_75_FLAG|HEIGHT|JERSEY|    LAST_AFFILIATION| LAST_NAME|NBA_FLAG|PERSON_ID|          PLAYERCODE|     PLAYER_SLUG|     POSITION|ROSTERSTATUS|              SCHOOL|SEASON_EXP|TEAM_ABBREVIATION|   TEAM_CITY|TEAM_CODE|   TEAM_ID|    TEAM_NAME|TO_YEAR|WEIGHT|
+-------------------+-----------+------------------+---------------+------------------------+------------+------------+-----------+----------+----------+---------+--------------------------------+-----------------+----------------+------+------+--------------------+----------+--------+---------+--------------------+----------------+-------------+------------+--------------------+----------+-----------------+------------+---------+----------+-------------+-------+------+
|1961-03-28T00:00:00|        USA|       Byron Scott|       B. Scott|            Scott, Byron|           N|           4|          1|      1983|     Byron|     1983|                               N|                Y|               N|   6-4|      |   Arizona State/USA|     Scott|       Y|        2|         byron_scott|     byron-scott|        Guard|    Inactive|       Arizona State|        14|              LAL| Los Angeles|   lakers|1610612747|       Lakers|   1996|   205|
|1966-03-12T00:00:00|        USA|        Grant Long|        G. Long|             Long, Grant|           N|          33|          2|      1988|     Grant|     1988|                               N|                Y|               N|   6-9|      |Eastern Michigan/USA|      Long|       Y|        3|          grant_long|      grant-long|      Forward|    Inactive|    Eastern Michigan|        16|                 |            |         |         0|             |   2002|   240|
|1959-05-10T00:00:00|        USA|       Dan Schayes|     D. Schayes|            Schayes, Dan|           N|          13|          1|      1981|       Dan|     1981|                               N|                Y|               N|  6-11|    24|        Syracuse/USA|   Schayes|       Y|        7|         dan_schayes|     dan-schayes|       Center|    Inactive|            Syracuse|        18|              DEN|      Denver|  nuggets|1610612743|      Nuggets|   1998|   260|
|1961-09-10T00:00:00|        USA|    Sedale Threatt|     S. Threatt|         Threatt, Sedale|           N|         139|          6|      1983|    Sedale|     1983|                               N|                Y|               N|   6-2|     2|West Virginia Tec...|   Threatt|       Y|        9|      sedale_threatt|  sedale-threatt|        Guard|    Inactive|  West Virginia Tech|        14|              LAL| Los Angeles|   lakers|1610612747|       Lakers|   1996|   185|
|1969-07-24T00:00:00|        USA|        Chris King|        C. King|             King, Chris|           N|          45|          2|      1992|     Chris|     1993|                               N|                Y|               N|   6-8|      |     Wake Forest/USA|      King|       Y|       12|          chris_king|      chris-king|      Forward|    Inactive|         Wake Forest|         3|                 |            |         |         0|             |   1998|   215|
|1962-02-22T00:00:00|        USA|      Jim Petersen|    J. Petersen|           Petersen, Jim|           N|          51|          3|      1984|       Jim|     1984|                               N|                Y|               N|  6-10|    43|       Minnesota/USA|  Petersen|       Y|    77839|HISTADD_jim_petersen|    jim-petersen|      Forward|    Inactive|           Minnesota|         8|              HOU|     Houston|  rockets|1610612745|      Rockets|   1991|   235|
|1970-09-30T00:00:00|        USA|   Eric Piatkowski|  E. Piatkowski|        Piatkowski, Eric|           N|          15|          1|      1994|      Eric|     1994|                               N|                Y|               N|   6-7|    52|        Nebraska/USA|Piatkowski|       Y|       15|     eric_piatkowski| eric-piatkowski|Guard-Forward|    Inactive|            Nebraska|        15|              LAC| Los Angeles| clippers|1610612746|     Clippers|   2007|   215|
|1962-06-22T00:00:00|        USA|     Clyde Drexler|     C. Drexler|          Drexler, Clyde|           N|          14|          1|      1983|     Clyde|     1983|                               N|                Y|               Y|   6-7|    22|         Houston/USA|   Drexler|       Y|       17|       clyde_drexler|   clyde-drexler|        Guard|    Inactive|             Houston|        15|              POR|    Portland|  blazers|1610612757|Trail Blazers|   1997|   222|
|1964-10-22T00:00:00|    Croatia|   Drazen Petrovic|    D. Petrovic|        Petrovic, Drazen|           N|          60|          3|      1986|    Drazen|     1989|                               N|                Y|               N|   6-5|     3| Real Madrid/Croatia|  Petrovic|       Y|    77845|HISTADD_drazen_pe...| drazen-petrovic|        Guard|    Inactive|         Real Madrid|         4|              NJN|  New Jersey|     nets|1610612751|         Nets|   1992|   195|
|1966-08-23T00:00:00|Netherlands|         Rik Smits|       R. Smits|              Smits, Rik|           N|           2|          1|      1988|       Rik|     1988|                               N|                Y|               N|   7-4|    45|  Marist/Netherlands|     Smits|       Y|       22|           rik_smits|       rik-smits|       Center|    Inactive|              Marist|        12|              IND|     Indiana|   pacers|1610612754|       Pacers|   1999|   265|
|1961-05-13T00:00:00|        USA|     Dennis Rodman|      D. Rodman|          Rodman, Dennis|           N|          27|          2|      1986|    Dennis|     1986|                               N|                Y|               Y|   6-7|    10|Southeastern Okla...|    Rodman|       Y|       23|       dennis_rodman|   dennis-rodman|      Forward|    Inactive|Southeastern Okla...|        14|              DET|     Detroit|  pistons|1610612765|      Pistons|   1999|   210|
|1967-11-15T00:00:00|        USA|      Greg Anthony|     G. Anthony|           Anthony, Greg|           N|          12|          1|      1991|      Greg|     1991|                               N|                Y|               N|   6-1|    50|            UNLV/USA|   Anthony|       Y|       21|        greg_anthony|    greg-anthony|        Guard|    Inactive|                UNLV|        11|              NYK|    New York|   knicks|1610612752|       Knicks|   2001|   180|
|1968-11-02T00:00:00|        USA|    Keith Jennings|    K. Jennings|         Jennings, Keith|           N|   Undrafted|  Undrafted| Undrafted|     Keith|     1992|                               N|                Y|               N|   5-7|     2|East Tennessee St...|  Jennings|       Y|       24|      keith_jennings|  keith-jennings|        Guard|    Inactive|East Tennessee State|         3|              GOS|Golden State| warriors|1610612744|     Warriors|   1994|   160|
|1969-01-19T00:00:00|  Australia|       Luc Longley|     L. Longley|            Longley, Luc|           N|           7|          1|      1991|       Luc|     1991|                               N|                Y|               N|      |      |New Mexico/Australia|   Longley|       Y|       26|         luc_longley|     luc-longley|       Center|    Inactive|          New Mexico|        10|                 |            |         |         0|             |   2000|      |
|1969-01-25T00:00:00|        USA|  Richard Petruska|    R. Petruska|       Petruska, Richard|           N|          46|          2|      1993|   Richard|     1993|                               N|                Y|               N|  6-10|     3|            UCLA/USA|  Petruska|       Y|    77846|HISTADD_richard_p...|richard-petruska|       Center|    Inactive|                UCLA|         1|              HOU|     Houston|  rockets|1610612745|      Rockets|   1993|   260|
|1961-10-03T00:00:00|        USA|       Mike Phelps|      M. Phelps|            Phelps, Mike|           N|         144|          7|      1985|      Mike|     1985|                               N|                Y|               N|   6-4|    14|    Alcorn State/USA|    Phelps|       Y|    77852| HISTADD_mike_phelps|     mike-phelps|        Guard|    Inactive|        Alcorn State|         3|              SEA|     Seattle|  thunder|1610612760|  SuperSonics|   1987|   180|
|1967-05-27T00:00:00|        USA|         Doug West|        D. West|              West, Doug|           N|          38|          2|      1989|      Doug|     1989|                               N|                Y|               N|      |      |       Villanova/USA|      West|       Y|       28|           doug_west|       doug-west|        Guard|    Inactive|           Villanova|        12|                 |            |         |         0|             |   2000|      |
|1969-05-19T00:00:00|        USA|     Richard Dumas|       R. Dumas|          Dumas, Richard|           N|          46|          2|      1991|   Richard|     1992|                               N|                Y|               N|   6-7|     7|  Oklahoma State/USA|     Dumas|       Y|       30|       richard_dumas|   richard-dumas|      Forward|    Inactive|      Oklahoma State|         3|              PHX|     Phoenix|     suns|1610612756|         Suns|   1995|   225|
|1969-07-15T00:00:00|        USA|  Lorenzo Williams|    L. Williams|       Williams, Lorenzo|           N|   Undrafted|  Undrafted| Undrafted|   Lorenzo|     1992|                               N|                Y|               N|   6-9|      |         Stetson/USA|  Williams|       Y|       31|    lorenzo_williams|lorenzo-williams|      Forward|    Inactive|             Stetson|         7|                 |            |         |         0|             |   1999|   200|
|1972-10-31T00:00:00|        USA|   Clifford Rozier|      C. Rozier|        Rozier, Clifford|           N|          16|          1|      1994|  Clifford|     1994|                               N|                Y|               N|  6-11|      |      Louisville/USA|    Rozier|       Y|       32|     clifford_rozier| clifford-rozier|       Center|    Inactive|          Louisville|         4|                 |            |         |         0|             |   1997|   245|
+-------------------+-----------+------------------+---------------+------------------------+------------+------------+-----------+----------+----------+---------+--------------------------------+-----------------+----------------+------+------+--------------------+----------+--------+---------+--------------------+----------------+-------------+------------+--------------------+----------+-----------------+------------+---------+----------+-------------+-------+------+
only showing top 20 rows

In [30]:
df_2 = spark.read.format("json").option("multiline", True).option("path","raw_data/all_players.json").load()

In [31]:
df_2.show()

+----------+-------------------+-------+---------+------------+
|first_name|          full_name|     id|is_active|   last_name|
+----------+-------------------+-------+---------+------------+
|      Alaa|     Alaa Abdelnaby|  76001|    false|   Abdelnaby|
|      Zaid|    Zaid Abdul-Aziz|  76002|    false|  Abdul-Aziz|
|    Kareem|Kareem Abdul-Jabbar|  76003|    false|Abdul-Jabbar|
|   Mahmoud| Mahmoud Abdul-Rauf|     51|    false|  Abdul-Rauf|
|     Tariq|  Tariq Abdul-Wahad|   1505|    false| Abdul-Wahad|
|   Shareef|Shareef Abdur-Rahim|    949|    false| Abdur-Rahim|
|       Tom|      Tom Abernethy|  76005|    false|   Abernethy|
|    Forest|        Forest Able|  76006|    false|        Able|
|      John|     John Abramovic|  76007|    false|   Abramovic|
|      Alex|       Alex Abrines| 203518|    false|     Abrines|
|  Precious|   Precious Achiuwa|1630173|     true|     Achiuwa|
|      Alex|         Alex Acker| 101165|    false|       Acker|
|    Donald|    Donald Ackerman|  76008|    false|    Ackerman|
|      Mark|         Mark Acres|  76009|    false|       Acres|
|   Charles|      Charles Acton|  76010|    false|       Acton|
|    Quincy|         Quincy Acy| 203112|    false|         Acy|
|     Alvan|        Alvan Adams|  76011|    false|       Adams|
|       Don|          Don Adams|  76012|    false|       Adams|
|    Hassan|       Hassan Adams| 200801|    false|       Adams|
|    Jaylen|       Jaylen Adams|1629121|    false|       Adams|
+----------+-------------------+-------+---------+------------+
only showing top 20 rows

In [32]:
joined = df_1.join(other=df_2, on=df_1.PERSON_ID==df_2.id, how="inner")

In [33]:
from pyspark.sql.functions import col
joined.show()

+-------------------+-----------+------------------+---------------+------------------------+------------+------------+-----------+----------+----------+---------+--------------------------------+-----------------+----------------+------+------+--------------------+----------+--------+---------+--------------------+----------------+-------------+------------+--------------------+----------+-----------------+------------+---------+----------+-------------+-------+------+----------+----------------+-----+---------+----------+
|          BIRTHDATE|    COUNTRY|DISPLAY_FIRST_LAST|DISPLAY_FI_LAST|DISPLAY_LAST_COMMA_FIRST|DLEAGUE_FLAG|DRAFT_NUMBER|DRAFT_ROUND|DRAFT_YEAR|FIRST_NAME|FROM_YEAR|GAMES_PLAYED_CURRENT_SEASON_FLAG|GAMES_PLAYED_FLAG|GREATEST_75_FLAG|HEIGHT|JERSEY|    LAST_AFFILIATION| LAST_NAME|NBA_FLAG|PERSON_ID|          PLAYERCODE|     PLAYER_SLUG|     POSITION|ROSTERSTATUS|              SCHOOL|SEASON_EXP|TEAM_ABBREVIATION|   TEAM_CITY|TEAM_CODE|   TEAM_ID|    TEAM_NAME|TO_YEAR|WEIGHT|first_name|       full_name|   id|is_active| last_name|
+-------------------+-----------+------------------+---------------+------------------------+------------+------------+-----------+----------+----------+---------+--------------------------------+-----------------+----------------+------+------+--------------------+----------+--------+---------+--------------------+----------------+-------------+------------+--------------------+----------+-----------------+------------+---------+----------+-------------+-------+------+----------+----------------+-----+---------+----------+
|1961-03-28T00:00:00|        USA|       Byron Scott|       B. Scott|            Scott, Byron|           N|           4|          1|      1983|     Byron|     1983|                               N|                Y|               N|   6-4|      |   Arizona State/USA|     Scott|       Y|        2|         byron_scott|     byron-scott|        Guard|    Inactive|       Arizona State|        14|              LAL| Los Angeles|   lakers|1610612747|       Lakers|   1996|   205|     Byron|     Byron Scott|    2|    false|     Scott|
|1966-03-12T00:00:00|        USA|        Grant Long|        G. Long|             Long, Grant|           N|          33|          2|      1988|     Grant|     1988|                               N|                Y|               N|   6-9|      |Eastern Michigan/USA|      Long|       Y|        3|          grant_long|      grant-long|      Forward|    Inactive|    Eastern Michigan|        16|                 |            |         |         0|             |   2002|   240|     Grant|      Grant Long|    3|    false|      Long|
|1959-05-10T00:00:00|        USA|       Dan Schayes|     D. Schayes|            Schayes, Dan|           N|          13|          1|      1981|       Dan|     1981|                               N|                Y|               N|  6-11|    24|        Syracuse/USA|   Schayes|       Y|        7|         dan_schayes|     dan-schayes|       Center|    Inactive|            Syracuse|        18|              DEN|      Denver|  nuggets|1610612743|      Nuggets|   1998|   260|       Dan|     Dan Schayes|    7|    false|   Schayes|
|1961-09-10T00:00:00|        USA|    Sedale Threatt|     S. Threatt|         Threatt, Sedale|           N|         139|          6|      1983|    Sedale|     1983|                               N|                Y|               N|   6-2|     2|West Virginia Tec...|   Threatt|       Y|        9|      sedale_threatt|  sedale-threatt|        Guard|    Inactive|  West Virginia Tech|        14|              LAL| Los Angeles|   lakers|1610612747|       Lakers|   1996|   185|    Sedale|  Sedale Threatt|    9|    false|   Threatt|
|1969-07-24T00:00:00|        USA|        Chris King|        C. King|             King, Chris|           N|          45|          2|      1992|     Chris|     1993|                               N|                Y|               N|   6-8|      |     Wake Forest/USA|      King|       Y|       12|          chris_king|      chris-king|      Forward|    Inactive|         Wake Forest|         3|                 |            |         |         0|             |   1998|   215|     Chris|      Chris King|   12|    false|      King|
|1962-02-22T00:00:00|        USA|      Jim Petersen|    J. Petersen|           Petersen, Jim|           N|          51|          3|      1984|       Jim|     1984|                               N|                Y|               N|  6-10|    43|       Minnesota/USA|  Petersen|       Y|    77839|HISTADD_jim_petersen|    jim-petersen|      Forward|    Inactive|           Minnesota|         8|              HOU|     Houston|  rockets|1610612745|      Rockets|   1991|   235|       Jim|    Jim Petersen|77839|    false|  Petersen|
|1970-09-30T00:00:00|        USA|   Eric Piatkowski|  E. Piatkowski|        Piatkowski, Eric|           N|          15|          1|      1994|      Eric|     1994|                               N|                Y|               N|   6-7|    52|        Nebraska/USA|Piatkowski|       Y|       15|     eric_piatkowski| eric-piatkowski|Guard-Forward|    Inactive|            Nebraska|        15|              LAC| Los Angeles| clippers|1610612746|     Clippers|   2007|   215|      Eric| Eric Piatkowski|   15|    false|Piatkowski|
|1962-06-22T00:00:00|        USA|     Clyde Drexler|     C. Drexler|          Drexler, Clyde|           N|          14|          1|      1983|     Clyde|     1983|                               N|                Y|               Y|   6-7|    22|         Houston/USA|   Drexler|       Y|       17|       clyde_drexler|   clyde-drexler|        Guard|    Inactive|             Houston|        15|              POR|    Portland|  blazers|1610612757|Trail Blazers|   1997|   222|     Clyde|   Clyde Drexler|   17|    false|   Drexler|
|1964-10-22T00:00:00|    Croatia|   Drazen Petrovic|    D. Petrovic|        Petrovic, Drazen|           N|          60|          3|      1986|    Drazen|     1989|                               N|                Y|               N|   6-5|     3| Real Madrid/Croatia|  Petrovic|       Y|    77845|HISTADD_drazen_pe...| drazen-petrovic|        Guard|    Inactive|         Real Madrid|         4|              NJN|  New Jersey|     nets|1610612751|         Nets|   1992|   195|    Drazen| Drazen Petrovic|77845|    false|  Petrovic|
|1966-08-23T00:00:00|Netherlands|         Rik Smits|       R. Smits|              Smits, Rik|           N|           2|          1|      1988|       Rik|     1988|                               N|                Y|               N|   7-4|    45|  Marist/Netherlands|     Smits|       Y|       22|           rik_smits|       rik-smits|       Center|    Inactive|              Marist|        12|              IND|     Indiana|   pacers|1610612754|       Pacers|   1999|   265|       Rik|       Rik Smits|   22|    false|     Smits|
|1961-05-13T00:00:00|        USA|     Dennis Rodman|      D. Rodman|          Rodman, Dennis|           N|          27|          2|      1986|    Dennis|     1986|                               N|                Y|               Y|   6-7|    10|Southeastern Okla...|    Rodman|       Y|       23|       dennis_rodman|   dennis-rodman|      Forward|    Inactive|Southeastern Okla...|        14|              DET|     Detroit|  pistons|1610612765|      Pistons|   1999|   210|    Dennis|   Dennis Rodman|   23|    false|    Rodman|
|1967-11-15T00:00:00|        USA|      Greg Anthony|     G. Anthony|           Anthony, Greg|           N|          12|          1|      1991|      Greg|     1991|                               N|                Y|               N|   6-1|    50|            UNLV/USA|   Anthony|       Y|       21|        greg_anthony|    greg-anthony|        Guard|    Inactive|                UNLV|        11|              NYK|    New York|   knicks|1610612752|       Knicks|   2001|   180|      Greg|    Greg Anthony|   21|    false|   Anthony|
|1968-11-02T00:00:00|        USA|    Keith Jennings|    K. Jennings|         Jennings, Keith|           N|   Undrafted|  Undrafted| Undrafted|     Keith|     1992|                               N|                Y|               N|   5-7|     2|East Tennessee St...|  Jennings|       Y|       24|      keith_jennings|  keith-jennings|        Guard|    Inactive|East Tennessee State|         3|              GOS|Golden State| warriors|1610612744|     Warriors|   1994|   160|     Keith|  Keith Jennings|   24|    false|  Jennings|
|1969-01-19T00:00:00|  Australia|       Luc Longley|     L. Longley|            Longley, Luc|           N|           7|          1|      1991|       Luc|     1991|                               N|                Y|               N|      |      |New Mexico/Australia|   Longley|       Y|       26|         luc_longley|     luc-longley|       Center|    Inactive|          New Mexico|        10|                 |            |         |         0|             |   2000|      |       Luc|     Luc Longley|   26|    false|   Longley|
|1969-01-25T00:00:00|        USA|  Richard Petruska|    R. Petruska|       Petruska, Richard|           N|          46|          2|      1993|   Richard|     1993|                               N|                Y|               N|  6-10|     3|            UCLA/USA|  Petruska|       Y|    77846|HISTADD_richard_p...|richard-petruska|       Center|    Inactive|                UCLA|         1|              HOU|     Houston|  rockets|1610612745|      Rockets|   1993|   260|   Richard|Richard Petruska|77846|    false|  Petruska|
|1961-10-03T00:00:00|        USA|       Mike Phelps|      M. Phelps|            Phelps, Mike|           N|         144|          7|      1985|      Mike|     1985|                               N|                Y|               N|   6-4|    14|    Alcorn State/USA|    Phelps|       Y|    77852| HISTADD_mike_phelps|     mike-phelps|        Guard|    Inactive|        Alcorn State|         3|              SEA|     Seattle|  thunder|1610612760|  SuperSonics|   1987|   180|      Mike|     Mike Phelps|77852|    false|    Phelps|
|1967-05-27T00:00:00|        USA|         Doug West|        D. West|              West, Doug|           N|          38|          2|      1989|      Doug|     1989|                               N|                Y|               N|      |      |       Villanova/USA|      West|       Y|       28|           doug_west|       doug-west|        Guard|    Inactive|           Villanova|        12|                 |            |         |         0|             |   2000|      |      Doug|       Doug West|   28|    false|      West|
|1969-05-19T00:00:00|        USA|     Richard Dumas|       R. Dumas|          Dumas, Richard|           N|          46|          2|      1991|   Richard|     1992|                               N|                Y|               N|   6-7|     7|  Oklahoma State/USA|     Dumas|       Y|       30|       richard_dumas|   richard-dumas|      Forward|    Inactive|      Oklahoma State|         3|              PHX|     Phoenix|     suns|1610612756|         Suns|   1995|   225|   Richard|   Richard Dumas|   30|    false|     Dumas|
|1969-07-15T00:00:00|        USA|  Lorenzo Williams|    L. Williams|       Williams, Lorenzo|           N|   Undrafted|  Undrafted| Undrafted|   Lorenzo|     1992|                               N|                Y|               N|   6-9|      |         Stetson/USA|  Williams|       Y|       31|    lorenzo_williams|lorenzo-williams|      Forward|    Inactive|             Stetson|         7|                 |            |         |         0|             |   1999|   200|   Lorenzo|Lorenzo Williams|   31|    false|  Williams|
|1972-10-31T00:00:00|        USA|   Clifford Rozier|      C. Rozier|        Rozier, Clifford|           N|          16|          1|      1994|  Clifford|     1994|                               N|                Y|               N|  6-11|      |      Louisville/USA|    Rozier|       Y|       32|     clifford_rozier| clifford-rozier|       Center|    Inactive|          Louisville|         4|                 |            |         |         0|             |   1997|   245|  Clifford| Clifford Rozier|   32|    false|    Rozier|
+-------------------+-----------+------------------+---------------+------------------------+------------+------------+-----------+----------+----------+---------+--------------------------------+-----------------+----------------+------+------+--------------------+----------+--------+---------+--------------------+----------------+-------------+------------+--------------------+----------+-----------------+------------+---------+----------+-------------+-------+------+----------+----------------+-----+---------+----------+
only showing top 20 rows

In [34]:
from pyspark.sql.types import *
final_df = joined.select(col("id").alias("source_player_id"),
              col("full_name"),
              col("BIRTHDATE").try_cast(DateType()).alias("birthdate"),
              col("is_active").alias("is_active"),
              col("HEIGHT").alias("height"),
              col("WEIGHT").try_cast(IntegerType()).alias("weight"),
              col("SEASON_EXP").alias("season_experience"),
              col("POSITION").alias("position"),
              col("FROM_YEAR").try_cast(StringType()).alias("from_year"),
              col("TO_YEAR").try_cast(StringType()).alias("to_year"),
              col("DRAFT_YEAR").alias("draft_year"),
              col("DRAFT_ROUND").alias("draft_round"),
              col("DRAFT_NUMBER").alias("draft_number"),
              col("SCHOOL").alias("school"),
              col("COUNTRY").alias("country")
              )

In [35]:
final_df.show()

+----------------+----------------+----------+---------+------+------+-----------------+-------------+---------+-------+----------+-----------+------------+--------------------+-----------+
|source_player_id|       full_name| birthdate|is_active|height|weight|season_experience|     position|from_year|to_year|draft_year|draft_round|draft_number|              school|    country|
+----------------+----------------+----------+---------+------+------+-----------------+-------------+---------+-------+----------+-----------+------------+--------------------+-----------+
|               2|     Byron Scott|1961-03-28|    false|   6-4|   205|               14|        Guard|     1983|   1996|      1983|          1|           4|       Arizona State|        USA|
|               3|      Grant Long|1966-03-12|    false|   6-9|   240|               16|      Forward|     1988|   2002|      1988|          2|          33|    Eastern Michigan|        USA|
|               7|     Dan Schayes|1959-05-10|    false|  6-11|   260|               18|       Center|     1981|   1998|      1981|          1|          13|            Syracuse|        USA|
|               9|  Sedale Threatt|1961-09-10|    false|   6-2|   185|               14|        Guard|     1983|   1996|      1983|          6|         139|  West Virginia Tech|        USA|
|              12|      Chris King|1969-07-24|    false|   6-8|   215|                3|      Forward|     1993|   1998|      1992|          2|          45|         Wake Forest|        USA|
|           77839|    Jim Petersen|1962-02-22|    false|  6-10|   235|                8|      Forward|     1984|   1991|      1984|          3|          51|           Minnesota|        USA|
|              15| Eric Piatkowski|1970-09-30|    false|   6-7|   215|               15|Guard-Forward|     1994|   2007|      1994|          1|          15|            Nebraska|        USA|
|              17|   Clyde Drexler|1962-06-22|    false|   6-7|   222|               15|        Guard|     1983|   1997|      1983|          1|          14|             Houston|        USA|
|           77845| Drazen Petrovic|1964-10-22|    false|   6-5|   195|                4|        Guard|     1989|   1992|      1986|          3|          60|         Real Madrid|    Croatia|
|              22|       Rik Smits|1966-08-23|    false|   7-4|   265|               12|       Center|     1988|   1999|      1988|          1|           2|              Marist|Netherlands|
|              23|   Dennis Rodman|1961-05-13|    false|   6-7|   210|               14|      Forward|     1986|   1999|      1986|          2|          27|Southeastern Okla...|        USA|
|              21|    Greg Anthony|1967-11-15|    false|   6-1|   180|               11|        Guard|     1991|   2001|      1991|          1|          12|                UNLV|        USA|
|              24|  Keith Jennings|1968-11-02|    false|   5-7|   160|                3|        Guard|     1992|   1994| Undrafted|  Undrafted|   Undrafted|East Tennessee State|        USA|
|              26|     Luc Longley|1969-01-19|    false|      |  NULL|               10|       Center|     1991|   2000|      1991|          1|           7|          New Mexico|  Australia|
|           77846|Richard Petruska|1969-01-25|    false|  6-10|   260|                1|       Center|     1993|   1993|      1993|          2|          46|                UCLA|        USA|
|           77852|     Mike Phelps|1961-10-03|    false|   6-4|   180|                3|        Guard|     1985|   1987|      1985|          7|         144|        Alcorn State|        USA|
|              28|       Doug West|1967-05-27|    false|      |  NULL|               12|        Guard|     1989|   2000|      1989|          2|          38|           Villanova|        USA|
|              30|   Richard Dumas|1969-05-19|    false|   6-7|   225|                3|      Forward|     1992|   1995|      1991|          2|          46|      Oklahoma State|        USA|
|              31|Lorenzo Williams|1969-07-15|    false|   6-9|   200|                7|      Forward|     1992|   1999| Undrafted|  Undrafted|   Undrafted|             Stetson|        USA|
|              32| Clifford Rozier|1972-10-31|    false|  6-11|   245|                4|       Center|     1994|   1997|      1994|          1|          16|          Louisville|        USA|
+----------------+----------------+----------+---------+------+------+-----------------+-------------+---------+-------+----------+-----------+------------+--------------------+-----------+
only showing top 20 rows

In [36]:
print(f"df_1 count: {df_1.count()}")
print(f"df_2 count: {df_2.count()}")
print(f"joined count: {joined.count()}")

df_1 count: 1036
df_2 count: 5103
joined count: 1036

In [1]:

from pyspark.sql import SparkSession


spark = (SparkSession.builder
         .master("local[*]")
         .appName("SQLREAD")
         .config("spark.jars", "file:///C:/spark-jars/mssql-jdbc-13.4.0.jre11.jar")
         .getOrCreate()
)


server = "localhost:1433"
database = "Basketball"
url = f"jdbc:sqlserver://{server};databaseName={database};trustServerCertificate=true"

properties = {
    "user": "spark_user2",
    "password": "1234",
    "driver": "com.microsoft.sqlserver.jdbc.SQLServerDriver"
}


players_df = spark.read.jdbc(url=url, table="player", properties=properties)


players_df.show(5)

+---------+----------------+--------------+----------+---------+------+------+-----------------+--------+---------+-------+----------+-----------+------------+------------------+-------+
|player_id|source_player_id|     full_name| birthdate|is_active|height|weight|season_experience|position|from_year|to_year|draft_year|draft_round|draft_number|            school|country|
+---------+----------------+--------------+----------+---------+------+------+-----------------+--------+---------+-------+----------+-----------+------------+------------------+-------+
|        1|               2|   Byron Scott|1961-03-28|    false|   6-4|   205|               14|   Guard|     1983|   1996|      1983|          1|           4|     Arizona State|    USA|
|        2|               3|    Grant Long|1966-03-12|    false|   6-9|   240|               16| Forward|     1988|   2002|      1988|          2|          33|  Eastern Michigan|    USA|
|        3|               7|   Dan Schayes|1959-05-10|    false|  6-11|   260|               18|  Center|     1981|   1998|      1981|          1|          13|          Syracuse|    USA|
|        4|               9|Sedale Threatt|1961-09-10|    false|   6-2|   185|               14|   Guard|     1983|   1996|      1983|          6|         139|West Virginia Tech|    USA|
|        5|              12|    Chris King|1969-07-24|    false|   6-8|   215|                3| Forward|     1993|   1998|      1992|          2|          45|       Wake Forest|    USA|
+---------+----------------+--------------+----------+---------+------+------+-----------------+--------+---------+-------+----------+-----------+------------+------------------+-------+
only showing top 5 rows

In [23]:
players_df = spark.read.jdbc(url=url, table="player", properties=properties)

In [2]:
import pandas as pd

In [15]:
all_players_info = spark.read.format("json").option("multiline", True).option("path","raw_data/players_info/players_info.json").load()
all_players = spark.read.format("json").option("multiline", True).option("path","raw_data/all_players.json").load()

In [24]:
all_players_info.count()

5103

In [25]:
all_players.count()

5103

In [26]:
joined_source_df = all_players_info.join(other=all_players, on=all_players_info["PERSON_ID"] == all_players["id"],how="inner")

In [16]:
joined_source_df.show(5)

+-------------------+-------+-------------------+---------------+------------------------+------------+------------+-----------+----------+----------+---------+--------------------------------+-----------------+----------------+------+------+--------------------+------------+--------+---------+--------------------+-------------------+-------------+------------+---------------+----------+-----------------+-----------+---------+----------+-------------+-------+------+----------+-------------------+-----+---------+------------+
|          BIRTHDATE|COUNTRY| DISPLAY_FIRST_LAST|DISPLAY_FI_LAST|DISPLAY_LAST_COMMA_FIRST|DLEAGUE_FLAG|DRAFT_NUMBER|DRAFT_ROUND|DRAFT_YEAR|FIRST_NAME|FROM_YEAR|GAMES_PLAYED_CURRENT_SEASON_FLAG|GAMES_PLAYED_FLAG|GREATEST_75_FLAG|HEIGHT|JERSEY|    LAST_AFFILIATION|   LAST_NAME|NBA_FLAG|PERSON_ID|          PLAYERCODE|        PLAYER_SLUG|     POSITION|ROSTERSTATUS|         SCHOOL|SEASON_EXP|TEAM_ABBREVIATION|  TEAM_CITY|TEAM_CODE|   TEAM_ID|    TEAM_NAME|TO_YEAR|WEIGHT|first_name|          full_name|   id|is_active|   last_name|
+-------------------+-------+-------------------+---------------+------------------------+------------+------------+-----------+----------+----------+---------+--------------------------------+-----------------+----------------+------+------+--------------------+------------+--------+---------+--------------------+-------------------+-------------+------------+---------------+----------+-----------------+-----------+---------+----------+-------------+-------+------+----------+-------------------+-----+---------+------------+
|1968-06-24T00:00:00|    USA|     Alaa Abdelnaby|   A. Abdelnaby|         Abdelnaby, Alaa|           N|          25|          1|      1990|      Alaa|     1990|                               N|                Y|               N|  6-10|    30|            Duke/USA|   Abdelnaby|       Y|    76001|HISTADD_alaa_abde...|     alaa-abdelnaby|      Forward|    Inactive|           Duke|         5|              POR|   Portland|  blazers|1610612757|Trail Blazers|   1994|   240|      Alaa|     Alaa Abdelnaby|76001|    false|   Abdelnaby|
|1946-04-07T00:00:00|    USA|    Zaid Abdul-Aziz|  Z. Abdul-Aziz|        Abdul-Aziz, Zaid|           N|           5|          1|      1968|      Zaid|     1968|                               N|                Y|               N|   6-9|    54|      Iowa State/USA|  Abdul-Aziz|       Y|    76002|HISTADD_zaid_abdu...|    zaid-abdul-aziz|       Center|    Inactive|     Iowa State|        10|              HOU|    Houston|  rockets|1610612745|      Rockets|   1977|   235|      Zaid|    Zaid Abdul-Aziz|76002|    false|  Abdul-Aziz|
|1947-04-16T00:00:00|    USA|Kareem Abdul-Jabbar|K. Abdul-Jabbar|    Abdul-Jabbar, Kareem|           N|           1|          1|      1969|    Kareem|     1969|                               N|                Y|               Y|   7-2|    33|            UCLA/USA|Abdul-Jabbar|       Y|    76003|HISTADD_kareem_ab...|kareem-abdul-jabbar|       Center|    Inactive|           UCLA|        20|              LAL|Los Angeles|   lakers|1610612747|       Lakers|   1988|   225|    Kareem|Kareem Abdul-Jabbar|76003|    false|Abdul-Jabbar|
|1969-03-09T00:00:00|    USA| Mahmoud Abdul-Rauf|  M. Abdul-Rauf|     Abdul-Rauf, Mahmoud|           N|           3|          1|      1990|   Mahmoud|     1990|                               N|                Y|               N|   6-1|     1| Louisiana State/USA|  Abdul-Rauf|       Y|       51|  mahmoud_abdul-rauf| mahmoud-abdul-rauf|        Guard|    Inactive|Louisiana State|         9|              DEN|     Denver|  nuggets|1610612743|      Nuggets|   2000|   162|   Mahmoud| Mahmoud Abdul-Rauf|   51|    false|  Abdul-Rauf|
|1974-11-03T00:00:00| France|  Tariq Abdul-Wahad| T. Abdul-Wahad|      Abdul-Wahad, Tariq|           N|          11|          1|      1997|     Tariq|     1997|                               N|                Y|               N|   6-6|     9|San Jose State/Fr...| Abdul-Wahad|       Y|     1505|   tariq_abdul-wahad|  tariq-abdul-wahad|Forward-Guard|    Inactive| San Jose State|         7|              SAC| Sacramento|    kings|1610612758|        Kings|   2003|   235|     Tariq|  Tariq Abdul-Wahad| 1505|    false| Abdul-Wahad|
+-------------------+-------+-------------------+---------------+------------------------+------------+------------+-----------+----------+----------+---------+--------------------------------+-----------------+----------------+------+------+--------------------+------------+--------+---------+--------------------+-------------------+-------------+------------+---------------+----------+-----------------+-----------+---------+----------+-------------+-------+------+----------+-------------------+-----+---------+------------+
only showing top 5 rows

In [27]:
joined_source_df.count()

5103

In [28]:
players_df.count()

5103

In [29]:
src = joined_source_df.join(other=players_df,on=joined_source_df["id"] == players_df["source_player_id"],how="leftanti")

In [27]:
from pyspark.sql.functions import col
from pyspark.sql.types import *

In [30]:
src.count()

0

In [36]:
from nba_api.stats.endpoints import teaminfocommon, teamdetails, boxscoretraditionalv3, boxscoresummaryv3
import json

In [32]:
teaminfo = teaminfocommon.TeamInfoCommon(team_id=1610612744)

In [35]:
team_data = teaminfo.get_data_frames()
team_data[0]

,TEAM_ID,SEASON_YEAR,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CONFERENCE,TEAM_DIVISION,TEAM_CODE,TEAM_SLUG,W,L,PCT,CONF_RANK,DIV_RANK,MIN_YEAR,MAX_YEAR
0,1610612744,2025-26,Golden State,Warriors,GSW,West,Pacific,warriors,warriors,37,45,0.451,10,4,1946,2026

In [37]:
src = teamdetails.TeamDetails(team_id=1610612744).get_data_frames()

In [49]:
game_info = boxscoretraditionalv3.BoxScoreTraditionalV3(game_id='0028500008')

In [50]:
df_game_info = game_info.get_data_frames()

In [53]:
df_game_info[2]

,gameId,teamId,teamCity,teamName,teamTricode,teamSlug,minutes,fieldGoalsMade,fieldGoalsAttempted,fieldGoalsPercentage,...,reboundsOffensive,reboundsDefensive,reboundsTotal,assists,steals,blocks,turnovers,foulsPersonal,points,plusMinusPoints
0,0028500008,1610612744,Golden State,Warriors,GOS,warriors,240:00,36,91,0.396,...,18,29,47,17,3,7,28,37,105,-14.0
1,0028500008,1610612743,Denver,Nuggets,DEN,nuggets,240:00,42,88,0.477,...,13,31,44,26,11,3,22,40,119,14.0

In [56]:
df_game_info[0]

,gameId,teamId,teamCity,teamName,teamTricode,teamSlug,personId,firstName,familyName,nameI,...,reboundsOffensive,reboundsDefensive,reboundsTotal,assists,steals,blocks,turnovers,foulsPersonal,points,plusMinusPoints
0,0028500008,1610612744,Golden State,Warriors,GOS,warriors,76353,Joe Barry,Carroll,J. Carroll,...,4,10,14,3,0,2,11,4,21,0.0
1,0028500008,1610612744,Golden State,Warriors,GOS,warriors,76431,Lester,Conner,L. Conner,...,1,2,3,3,0,0,1,0,5,0.0
2,0028500008,1610612744,Golden State,Warriors,GOS,warriors,76469,Ron,Crevier,R. Crevier,...,0,0,0,0,0,0,0,0,0,0.0
3,0028500008,1610612744,Golden State,Warriors,GOS,warriors,76726,Sleepy,Floyd,S. Floyd,...,1,1,2,9,2,0,12,4,32,0.0
4,0028500008,1610612744,Golden State,Warriors,GOS,warriors,77087,Geoff,Huston,G. Huston,...,0,0,0,1,1,0,1,0,2,0.0
5,0028500008,1610612744,Golden State,Warriors,GOS,warriors,78195,Larry,Smith,L. Smith,...,9,4,13,0,0,0,1,6,19,0.0
6,0028500008,1610612744,Golden State,Warriors,GOS,warriors,78304,Terry,Teagle,T. Teagle,...,0,1,1,0,0,2,2,1,9,0.0
7,0028500008,1610612744,Golden State,Warriors,GOS,warriors,78311,Peter,Thibeaux,P. Thibeaux,...,0,7,7,1,0,2,0,6,8,0.0
8,0028500008,1610612744,Golden State,Warriors,GOS,warriors,78414,Peter,Verhoeven,P. Verhoeven,...,1,0,1,0,0,0,0,6,2,0.0
9,0028500008,1610612744,Golden State,Warriors,GOS,warriors,78516,Jerome,Whitehead,J. Whitehead,...,2,1,3,0,0,0,0,4,6,0.0
10,0028500008,1610612744,Golden State,Warriors,GOS,warriors,78550,Guy,Williams,G. Williams,...,0,3,3,0,0,1,0,6,1,0.0
11,0028500008,1610612743,Denver,Nuggets,DEN,nuggets,76441,Wayne,Cooper,W. Cooper,...,2,4,6,1,0,1,1,5,9,0.0
12,0028500008,1610612743,Denver,Nuggets,DEN,nuggets,76618,T.R.,Dunn,T. Dunn,...,0,2,2,1,2,0,1,2,0,0.0
13,0028500008,1610612743,Denver,Nuggets,DEN,nuggets,76673,Alex,English,A. English,...,2,3,5,3,1,1,3,4,47,0.0
14,0028500008,1610612743,Denver,Nuggets,DEN,nuggets,76686,Mike,Evans,M. Evans,...,0,3,3,4,2,0,2,2,7,0.0
15,0028500008,1610612743,Denver,Nuggets,DEN,nuggets,76944,Bill,Hanzlik,B. Hanzlik,...,4,2,6,6,1,0,4,5,11,0.0
16,0028500008,1610612743,Denver,Nuggets,DEN,nuggets,77376,Lafayette,Lever,L. Lever,...,2,2,4,7,3,0,1,4,11,0.0
17,0028500008,1610612743,Denver,Nuggets,DEN,nuggets,77691,Calvin,Natt,C. Natt,...,0,4,4,2,1,0,3,4,21,0.0
18,0028500008,1610612743,Denver,Nuggets,DEN,nuggets,78656,Blair,Rasmussen,B. Rasmussen,...,2,5,7,0,1,0,2,4,7,0.0
19,0028500008,1610612743,Denver,Nuggets,DEN,nuggets,7,Dan,Schayes,D. Schayes,...,1,3,4,0,0,1,2,5,2,0.0
20,0028500008,1610612743,Denver,Nuggets,DEN,nuggets,78378,Elston,Turner,E. Turner,...,0,3,3,2,0,0,3,5,4,0.0

In [47]:
df_res = boxscoresummaryv3.BoxScoreSummaryV3(game_id='0049900002').get_data_frames()

In [48]:
df_res[0]

,gameId,gameCode,gameStatus,gameStatusText,period,gameClock,gameTimeUTC,gameEt,awayTeamId,homeTeamId,duration,attendance,sellout
0,0049900002,20000422/PHXSAS,3,Final,4,PT00M00.00S,2000-04-22T19:00:00Z,2000-04-22T15:00:00Z,1610612756,1610612759,2:26,21916,0

In [49]:
df_res[2]

,gameId,arenaId,arenaName,arenaCity,arenaState,arenaCountry,arenaTimezone
0,0049900002,1,Alamodome,San Antonio,TX,US,Central

In [70]:
seasons = [f"{year}-{str(year + 1)[-2:]}" for year in range(1996, 2026)]

In [4]:
from pyspark.sql import SparkSession
from pyspark.sql.types import *


spark = SparkSession.builder.master("local[*]").appName("Get_Arenas").getOrCreate()

df_games = spark.read.format("json").option("multiline",True).load("raw_data/games/games_*_regular_log.json")

In [9]:
from pyspark.sql.functions import col, explode

In [7]:
df_games.printSchema()

root
 |-- LeagueGameLog: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- AST: long (nullable = true)
 |    |    |-- BLK: long (nullable = true)
 |    |    |-- DREB: long (nullable = true)
 |    |    |-- FG3A: long (nullable = true)
 |    |    |-- FG3M: long (nullable = true)
 |    |    |-- FG3_PCT: double (nullable = true)
 |    |    |-- FGA: long (nullable = true)
 |    |    |-- FGM: long (nullable = true)
 |    |    |-- FG_PCT: double (nullable = true)
 |    |    |-- FTA: long (nullable = true)
 |    |    |-- FTM: long (nullable = true)
 |    |    |-- FT_PCT: double (nullable = true)
 |    |    |-- GAME_DATE: string (nullable = true)
 |    |    |-- GAME_ID: string (nullable = true)
 |    |    |-- MATCHUP: string (nullable = true)
 |    |    |-- MIN: long (nullable = true)
 |    |    |-- OREB: long (nullable = true)
 |    |    |-- PF: long (nullable = true)
 |    |    |-- PLUS_MINUS: long (nullable = true)
 |    |    |-- PTS: long (nullable = true)
 |    |    |-- REB: long (nullable = true)
 |    |    |-- SEASON_ID: string (nullable = true)
 |    |    |-- STL: long (nullable = true)
 |    |    |-- TEAM_ABBREVIATION: string (nullable = true)
 |    |    |-- TEAM_ID: long (nullable = true)
 |    |    |-- TEAM_NAME: string (nullable = true)
 |    |    |-- TOV: long (nullable = true)
 |    |    |-- VIDEO_AVAILABLE: long (nullable = true)
 |    |    |-- WL: string (nullable = true)

In [10]:
df_games = df_games.select(explode("LeagueGameLog").alias("game"))

In [13]:
df_games = df_games.select('game.*')

In [30]:
df_games.orderBy(col("GAME_DATE").asc()).where(col("MATCHUP").contains("vs")).count()#47242

47222

In [29]:
df_games.count()

94464

In [31]:
df_games.orderBy(col("GAME_DATE").asc()).where(col("MATCHUP").contains("vs")).show(5)

+---+---+----+----+----+-------+---+---+------+---+---+------+----------+----------+-----------+---+----+---+----------+---+---+---------+---+-----------------+----------+--------------------+---+---------------+---+
|AST|BLK|DREB|FG3A|FG3M|FG3_PCT|FGA|FGM|FG_PCT|FTA|FTM|FT_PCT| GAME_DATE|   GAME_ID|    MATCHUP|MIN|OREB| PF|PLUS_MINUS|PTS|REB|SEASON_ID|STL|TEAM_ABBREVIATION|   TEAM_ID|           TEAM_NAME|TOV|VIDEO_AVAILABLE| WL|
+---+---+----+----+----+-------+---+---+------+---+---+------+----------+----------+-----------+---+----+---+----------+---+---+---------+---+-----------------+----------+--------------------+---+---------------+---+
| 25|  5|  28|   3|   0|    0.0| 92| 41| 0.446| 18|  9|   0.5|1985-10-25|0028500005|ATL vs. WAS|240|  16| 23|        -9| 91| 44|    21985|  8|              ATL|1610612737|       Atlanta Hawks| 16|              0|  L|
| 17|  2|  28|   2|   0|    0.0| 88| 39| 0.443| 41| 26| 0.634|1985-10-25|0028500006|SAC vs. LAC|240|  20| 34|        -4|104| 48|    21985|  5|              SAC|1610612758|    Sacramento Kings| 20|              0|  L|
| 29|  8|  32|   4|   1|   0.25| 95| 43| 0.453| 41| 29| 0.707|1985-10-25|0028500007|CHI vs. CLE|265|  21| 33|         1|116| 53|    21985|  8|              CHI|1610612741|       Chicago Bulls| 20|              0|  W|
| 17|  7|  29|   4|   0|    0.0| 91| 36| 0.396| 52| 33| 0.635|1985-10-25|0028500008|GOS vs. DEN|240|  18| 37|       -14|105| 47|    21985|  3|              GOS|1610612744|Golden State Warr...| 28|              0|  L|
| 17|  3|  33|   1|   0|    0.0|101| 44| 0.436| 31| 25| 0.806|1985-10-25|0028500004|NJN vs. BOS|265|  19| 30|         4|113| 52|    21985| 14|              NJN|1610612751|     New Jersey Nets| 24|              0|  W|
+---+---+----+----+----+-------+---+---+------+---+---+------+----------+----------+-----------+---+----+---+----------+---+---+---------+---+-----------------+----------+--------------------+---+---------------+---+
only showing top 5 rows

In [60]:
wtf = df_games.where(col("MATCHUP").contains("vs")).select(col("GAME_ID"),col("SEASON_ID"),col("TEAM_ID")).collect()

In [61]:
wtf

[Row(GAME_ID='0022500002', SEASON_ID='22025', TEAM_ID=1610612747),
 Row(GAME_ID='0022500001', SEASON_ID='22025', TEAM_ID=1610612760),
 Row(GAME_ID='0022500080', SEASON_ID='22025', TEAM_ID=1610612766),
 Row(GAME_ID='0022500004', SEASON_ID='22025', TEAM_ID=1610612742),
 Row(GAME_ID='0022500082', SEASON_ID='22025', TEAM_ID=1610612737),
 Row(GAME_ID='0022500003', SEASON_ID='22025', TEAM_ID=1610612752),
 Row(GAME_ID='0022500089', SEASON_ID='22025', TEAM_ID=1610612757),
 Row(GAME_ID='0022500087', SEASON_ID='22025', TEAM_ID=1610612762),
 Row(GAME_ID='0022500081', SEASON_ID='22025', TEAM_ID=1610612753),
 Row(GAME_ID='0022500083', SEASON_ID='22025', TEAM_ID=1610612738),
 Row(GAME_ID='0022500088', SEASON_ID='22025', TEAM_ID=1610612756),
 Row(GAME_ID='0022500085', SEASON_ID='22025', TEAM_ID=1610612763),
 Row(GAME_ID='0022500086', SEASON_ID='22025', TEAM_ID=1610612749),
 Row(GAME_ID='0022500084', SEASON_ID='22025', TEAM_ID=1610612741),
 Row(GAME_ID='0022500005', SEASON_ID='22025', TEAM_ID=1610612754),
 Row(GAME_ID='0022500006', SEASON_ID='22025', TEAM_ID=1610612744),
 Row(GAME_ID='0022500098', SEASON_ID='22025', TEAM_ID=1610612758),
 Row(GAME_ID='0022500092', SEASON_ID='22025', TEAM_ID=1610612761),
 Row(GAME_ID='0022500099', SEASON_ID='22025', TEAM_ID=1610612746),
 Row(GAME_ID='0022500095', SEASON_ID='22025', TEAM_ID=1610612740),
 Row(GAME_ID='0022500096', SEASON_ID='22025', TEAM_ID=1610612742),
 Row(GAME_ID='0022500093', SEASON_ID='22025', TEAM_ID=1610612745),
 Row(GAME_ID='0022500090', SEASON_ID='22025', TEAM_ID=1610612753),
 Row(GAME_ID='0022500097', SEASON_ID='22025', TEAM_ID=1610612757),
 Row(GAME_ID='0022500018', SEASON_ID='22025', TEAM_ID=1610612752),
 Row(GAME_ID='0022500091', SEASON_ID='22025', TEAM_ID=1610612751),
 Row(GAME_ID='0022500094', SEASON_ID='22025', TEAM_ID=1610612763),
 Row(GAME_ID='0022500019', SEASON_ID='22025', TEAM_ID=1610612747),
 Row(GAME_ID='0022500103', SEASON_ID='22025', TEAM_ID=1610612763),
 Row(GAME_ID='0022500101', SEASON_ID='22025', TEAM_ID=1610612737),
 Row(GAME_ID='0022500100', SEASON_ID='22025', TEAM_ID=1610612753),
 Row(GAME_ID='0022500104', SEASON_ID='22025', TEAM_ID=1610612743),
 Row(GAME_ID='0022500102', SEASON_ID='22025', TEAM_ID=1610612755),
 Row(GAME_ID='0022500111', SEASON_ID='22025', TEAM_ID=1610612742),
 Row(GAME_ID='0022500107', SEASON_ID='22025', TEAM_ID=1610612739),
 Row(GAME_ID='0022500110', SEASON_ID='22025', TEAM_ID=1610612750),
 Row(GAME_ID='0022500112', SEASON_ID='22025', TEAM_ID=1610612746),
 Row(GAME_ID='0022500106', SEASON_ID='22025', TEAM_ID=1610612765),
 Row(GAME_ID='0022500105', SEASON_ID='22025', TEAM_ID=1610612759),
 Row(GAME_ID='0022500113', SEASON_ID='22025', TEAM_ID=1610612758),
 Row(GAME_ID='0022500109', SEASON_ID='22025', TEAM_ID=1610612764),
 Row(GAME_ID='0022500108', SEASON_ID='22025', TEAM_ID=1610612748),
 Row(GAME_ID='0022500120', SEASON_ID='22025', TEAM_ID=1610612762),
 Row(GAME_ID='0022500115', SEASON_ID='22025', TEAM_ID=1610612741),
 Row(GAME_ID='0022500007', SEASON_ID='22025', TEAM_ID=1610612765),
 Row(GAME_ID='0022500008', SEASON_ID='22025', TEAM_ID=1610612750),
 Row(GAME_ID='0022500122', SEASON_ID='22025', TEAM_ID=1610612747),
 Row(GAME_ID='0022500118', SEASON_ID='22025', TEAM_ID=1610612759),
 Row(GAME_ID='0022500116', SEASON_ID='22025', TEAM_ID=1610612745),
 Row(GAME_ID='0022500117', SEASON_ID='22025', TEAM_ID=1610612740),
 Row(GAME_ID='0022500114', SEASON_ID='22025', TEAM_ID=1610612755),
 Row(GAME_ID='0022500119', SEASON_ID='22025', TEAM_ID=1610612742),
 Row(GAME_ID='0022500121', SEASON_ID='22025', TEAM_ID=1610612744),
 Row(GAME_ID='0022500123', SEASON_ID='22025', TEAM_ID=1610612764),
 Row(GAME_ID='0022500127', SEASON_ID='22025', TEAM_ID=1610612744),
 Row(GAME_ID='0022500126', SEASON_ID='22025', TEAM_ID=1610612760),
 Row(GAME_ID='0022500124', SEASON_ID='22025', TEAM_ID=1610612748),
 Row(GAME_ID='0022500125', SEASON_ID='22025', TEAM_ID=1610612749),
 Row(GAME_ID='0022500129', SEASON_ID='22025', TEAM_ID=1610612765),
 Row(GAME_ID='0022500137', SEASON_ID='22025', TEAM_ID=1610612756),
 Row(GAME_ID='0022500131', SEASON_ID='22025', TEAM_ID=1610612761),
 Row(GAME_ID='0022500136', SEASON_ID='22025', TEAM_ID=1610612750),
 Row(GAME_ID='0022500135', SEASON_ID='22025', TEAM_ID=1610612762),
 Row(GAME_ID='0022500132', SEASON_ID='22025', TEAM_ID=1610612741),
 Row(GAME_ID='0022500130', SEASON_ID='22025', TEAM_ID=1610612751),
 Row(GAME_ID='0022500128', SEASON_ID='22025', TEAM_ID=1610612738),
 Row(GAME_ID='0022500134', SEASON_ID='22025', TEAM_ID=1610612743),
 Row(GAME_ID='0022500133', SEASON_ID='22025', TEAM_ID=1610612742),
 Row(GAME_ID='0022500138', SEASON_ID='22025', TEAM_ID=1610612766),
 Row(GAME_ID='0022500140', SEASON_ID='22025', TEAM_ID=1610612760),
 Row(GAME_ID='0022500141', SEASON_ID='22025', TEAM_ID=1610612759),
 Row(GAME_ID='0022500139', SEASON_ID='22025', TEAM_ID=1610612749),
 Row(GAME_ID='0022500024', SEASON_ID='22025', TEAM_ID=1610612763),
 Row(GAME_ID='0022500022', SEASON_ID='22025', TEAM_ID=1610612739),
 Row(GAME_ID='0022500027', SEASON_ID='22025', TEAM_ID=1610612746),
 Row(GAME_ID='0022500026', SEASON_ID='22025', TEAM_ID=1610612757),
 Row(GAME_ID='0022500021', SEASON_ID='22025', TEAM_ID=1610612755),
 Row(GAME_ID='0022500023', SEASON_ID='22025', TEAM_ID=1610612741),
 Row(GAME_ID='0022500025', SEASON_ID='22025', TEAM_ID=1610612756),
 Row(GAME_ID='0022500020', SEASON_ID='22025', TEAM_ID=1610612754),
 Row(GAME_ID='0022500143', SEASON_ID='22025', TEAM_ID=1610612766),
 Row(GAME_ID='0022500145', SEASON_ID='22025', TEAM_ID=1610612764),
 Row(GAME_ID='0022500144', SEASON_ID='22025', TEAM_ID=1610612754),
 Row(GAME_ID='0022500146', SEASON_ID='22025', TEAM_ID=1610612738),
 Row(GAME_ID='0022500142', SEASON_ID='22025', TEAM_ID=1610612749),
 Row(GAME_ID='0022500155', SEASON_ID='22025', TEAM_ID=1610612747),
 Row(GAME_ID='0022500149', SEASON_ID='22025', TEAM_ID=1610612751),
 Row(GAME_ID='0022500150', SEASON_ID='22025', TEAM_ID=1610612766),
 Row(GAME_ID='0022500153', SEASON_ID='22025', TEAM_ID=1610612752),
 Row(GAME_ID='0022500152', SEASON_ID='22025', TEAM_ID=1610612761),
 Row(GAME_ID='0022500154', SEASON_ID='22025', TEAM_ID=1610612756),
 Row(GAME_ID='0022500151', SEASON_ID='22025', TEAM_ID=1610612739),
 Row(GAME_ID='0022500148', SEASON_ID='22025', TEAM_ID=1610612760),
 Row(GAME_ID='0022500164', SEASON_ID='22025', TEAM_ID=1610612746),
 Row(GAME_ID='0022500159', SEASON_ID='22025', TEAM_ID=1610612752),
 Row(GAME_ID='0022500157', SEASON_ID='22025', TEAM_ID=1610612754),
 Row(GAME_ID='0022500156', SEASON_ID='22025', TEAM_ID=1610612751),
 Row(GAME_ID='0022500162', SEASON_ID='22025', TEAM_ID=1610612743),
 Row(GAME_ID='0022500160', SEASON_ID='22025', TEAM_ID=1610612745),
 Row(GAME_ID='0022500161', SEASON_ID='22025', TEAM_ID=1610612763),
 Row(GAME_ID='0022500163', SEASON_ID='22025', TEAM_ID=1610612757),
 Row(GAME_ID='0022500158', SEASON_ID='22025', TEAM_ID=1610612738),
 Row(GAME_ID='0022500166', SEASON_ID='22025', TEAM_ID=1610612737),
 Row(GAME_ID='0022500167', SEASON_ID='22025', TEAM_ID=1610612741),
 Row(GAME_ID='0022500165', SEASON_ID='22025', TEAM_ID=1610612761),
 Row(GAME_ID='0022500170', SEASON_ID='22025', TEAM_ID=1610612746),
 Row(GAME_ID='0022500168', SEASON_ID='22025', TEAM_ID=1610612740),
 Row(GAME_ID='0022500169', SEASON_ID='22025', TEAM_ID=1610612744),
 Row(GAME_ID='0022500178', SEASON_ID='22025', TEAM_ID=1610612743),
 Row(GAME_ID='0022500172', SEASON_ID='22025', TEAM_ID=1610612765),
 Row(GAME_ID='0022500176', SEASON_ID='22025', TEAM_ID=1610612763),
 Row(GAME_ID='0022500175', SEASON_ID='22025', TEAM_ID=1610612752),
 Row(GAME_ID='0022500181', SEASON_ID='22025', TEAM_ID=1610612758),
 Row(GAME_ID='0022500173', SEASON_ID='22025', TEAM_ID=1610612754),
 Row(GAME_ID='0022500171', SEASON_ID='22025', TEAM_ID=1610612739),
 Row(GAME_ID='0022500180', SEASON_ID='22025', TEAM_ID=1610612757),
 Row(GAME_ID='0022500177', SEASON_ID='22025', TEAM_ID=1610612742),
 Row(GAME_ID='0022500179', SEASON_ID='22025', TEAM_ID=1610612747),
 Row(GAME_ID='0022500174', SEASON_ID='22025', TEAM_ID=1610612738),
 Row(GAME_ID='0022500182', SEASON_ID='22025', TEAM_ID=1610612756),
 Row(GAME_ID='0022500030', SEASON_ID='22025', TEAM_ID=1610612737),
 Row(GAME_ID='0022500032', SEASON_ID='22025', TEAM_ID=1610612759),
 Row(GAME_ID='0022500038', SEASON_ID='22025', TEAM_ID=1610612758),
 Row(GAME_ID='0022500028', SEASON_ID='22025', TEAM_ID=1610612753),
 Row(GAME_ID='0022500037', SEASON_ID='22025', TEAM_ID=1610612743),
 Row(GAME_ID='0022500029', SEASON_ID='22025', TEAM_ID=1610612764),
 Row(GAME_ID='0022500035', SEASON_ID='22025', TEAM_ID=1610612749),
 Row(GAME_ID='0022500031', SEASON_ID='22025', TEAM_ID=1610612751),
 Row(GAME_ID='0022500033', SEASON_ID='22025', TEAM_ID=1610612748),
 Row(GAME_ID='0022500034', SEASON_ID='22025', TEAM_ID=1610612763),
 Row(GAME_ID='0022500036', SEASON_ID='22025', TEAM_ID=1610612750),
 Row(GAME_ID='0022500184', SEASON_ID='22025', TEAM_ID=1610612755),
 Row(GAME_ID='0022500186', SEASON_ID='22025', TEAM_ID=1610612739),
 Row(GAME_ID='0022500183', SEASON_ID='22025', TEAM_ID=1610612764),
 Row(GAME_ID='0022500185', SEASON_ID='22025', TEAM_ID=1610612737),
 Row(GAME_ID='0022500187', SEASON_ID='22025', TEAM_ID=1610612748),
 Row(GAME_ID='0022500188', SEASON_ID='22025', TEAM_ID=1610612759),
 Row(GAME_ID='0022500189', SEASON_ID='22025', TEAM_ID=1610612743),
 Row(GAME_ID='0022500190', SEASON_ID='22025', TEAM_ID=1610612746),
 Row(GAME_ID='0022500197', SEASON_ID='22025', TEAM_ID=1610612758),
 Row(GAME_ID='0022500192', SEASON_ID='22025', TEAM_ID=1610612752),
 Row(GAME_ID='0022500196', SEASON_ID='22025', TEAM_ID=1610612744),
 Row(GAME_ID='0022500195', SEASON_ID='22025', TEAM_ID=1610612755),
 Row(GAME_ID='0022500191', SEASON_ID='22025', TEAM_ID=1610612749),
 Row(GAME_ID='0022500193', SEASON_ID='22025', TEAM_ID=1610612753),
 Row(GAME_ID='0022500194', SEASON_ID='22025', TEAM_ID=1610612763),
 Row(GAME_ID='0022500200', SEASON_ID='22025', TEAM_ID=1610612753),
 Row(GAME_ID='0022500204', SEASON_ID='22025', TEAM_ID=1610612756),
 Row(GAME_ID='0022500206', SEASON_ID='22025', TEAM_ID=1610612746),
 Row(GAME_ID='0022500201', SEASON_ID='22025', TEAM_ID=1610612748),
 Row(GAME_ID='0022500198', SEASON_ID='22025', TEAM_ID=1610612766),
 Row(GAME_ID='0022500203', SEASON_ID='22025', TEAM_ID=1610612742),
 Row(GAME_ID='0022500205', SEASON_ID='22025', TEAM_ID=1610612762),
 Row(GAME_ID='0022500199', SEASON_ID='22025', TEAM_ID=1610612765),
 Row(GAME_ID='0022500202', SEASON_ID='22025', TEAM_ID=1610612741),
 Row(GAME_ID='0022500210', SEASON_ID='22025', TEAM_ID=1610612760),
 Row(GAME_ID='0022500212', SEASON_ID='22025', TEAM_ID=1610612758),
 Row(GAME_ID='0022500208', SEASON_ID='22025', TEAM_ID=1610612752),
 Row(GAME_ID='0022500209', SEASON_ID='22025', TEAM_ID=1610612755),
 Row(GAME_ID='0022500211', SEASON_ID='22025', TEAM_ID=1610612762),
 Row(GAME_ID='0022500207', SEASON_ID='22025', TEAM_ID=1610612751),
 Row(GAME_ID='0022500215', SEASON_ID='22025', TEAM_ID=1610612752),
 Row(GAME_ID='0022500222', SEASON_ID='22025', TEAM_ID=1610612760),
 Row(GAME_ID='0022500213', SEASON_ID='22025', TEAM_ID=1610612766),
 Row(GAME_ID='0022500219', SEASON_ID='22025', TEAM_ID=1610612740),
 Row(GAME_ID='0022500216', SEASON_ID='22025', TEAM_ID=1610612738),
 Row(GAME_ID='0022500218', SEASON_ID='22025', TEAM_ID=1610612745),
 Row(GAME_ID='0022500223', SEASON_ID='22025', TEAM_ID=1610612758),
 Row(GAME_ID='0022500214', SEASON_ID='22025', TEAM_ID=1610612765),
 Row(GAME_ID='0022500220', SEASON_ID='22025', TEAM_ID=1610612759),
 Row(GAME_ID='0022500217', SEASON_ID='22025', TEAM_ID=1610612748),
 Row(GAME_ID='0022500224', SEASON_ID='22025', TEAM_ID=1610612746),
 Row(GAME_ID='0022500221', SEASON_ID='22025', TEAM_ID=1610612742),
 Row(GAME_ID='0022500225', SEASON_ID='22025', TEAM_ID=1610612739),
 Row(GAME_ID='0022500227', SEASON_ID='22025', TEAM_ID=1610612762),
 Row(GAME_ID='0022500226', SEASON_ID='22025', TEAM_ID=1610612756),
 Row(GAME_ID='0022500042', SEASON_ID='22025', TEAM_ID=1610612745),
 Row(GAME_ID='0022500046', SEASON_ID='22025', TEAM_ID=1610612742),
 Row(GAME_ID='0022500045', SEASON_ID='22025', TEAM_ID=1610612740),
 Row(GAME_ID='0022500039', SEASON_ID='22025', TEAM_ID=1610612752),
 Row(GAME_ID='0022500044', SEASON_ID='22025', TEAM_ID=1610612750),
 Row(GAME_ID='0022500043', SEASON_ID='22025', TEAM_ID=1610612749),
 Row(GAME_ID='0022500047', SEASON_ID='22025', TEAM_ID=1610612759),
 Row(GAME_ID='0022500040', SEASON_ID='22025', TEAM_ID=1610612753),
 Row(GAME_ID='0022500041', SEASON_ID='22025', TEAM_ID=1610612765),
 Row(GAME_ID='0022500231', SEASON_ID='22025', TEAM_ID=1610612749),
 Row(GAME_ID='0022500228', SEASON_ID='22025', TEAM_ID=1610612739),
 Row(GAME_ID='0022500229', SEASON_ID='22025', TEAM_ID=1610612766),
 Row(GAME_ID='0022500230', SEASON_ID='22025', TEAM_ID=1610612754),
 Row(GAME_ID='0022500232', SEASON_ID='22025', TEAM_ID=1610612750),
 Row(GAME_ID='0022500239', SEASON_ID='22025', TEAM_ID=1610612756),
 Row(GAME_ID='0022500237', SEASON_ID='22025', TEAM_ID=1610612740),
 Row(GAME_ID='0022500240', SEASON_ID='22025', TEAM_ID=1610612762),
 Row(GAME_ID='0022500236', SEASON_ID='22025', TEAM_ID=1610612745),
 Row(GAME_ID='0022500234', SEASON_ID='22025', TEAM_ID=1610612759),
 Row(GAME_ID='0022500233', SEASON_ID='22025', TEAM_ID=1610612738),
 Row(GAME_ID='0022500235', SEASON_ID='22025', TEAM_ID=1610612764),
 Row(GAME_ID='0022500238', SEASON_ID='22025', TEAM_ID=1610612742),
 Row(GAME_ID='0022500244', SEASON_ID='22025', TEAM_ID=1610612748),
 Row(GAME_ID='0022500247', SEASON_ID='22025', TEAM_ID=1610612740),
 Row(GAME_ID='0022500246', SEASON_ID='22025', TEAM_ID=1610612750),
 Row(GAME_ID='0022500241', SEASON_ID='22025', TEAM_ID=1610612739),
 Row(GAME_ID='0022500248', SEASON_ID='22025', TEAM_ID=1610612743),
 Row(GAME_ID='0022500243', SEASON_ID='22025', TEAM_ID=1610612755),
 Row(GAME_ID='0022500242', SEASON_ID='22025', TEAM_ID=1610612765),
 Row(GAME_ID='0022500245', SEASON_ID='22025', TEAM_ID=1610612761),
 Row(GAME_ID='0022500252', SEASON_ID='22025', TEAM_ID=1610612759),
 Row(GAME_ID='0022500250', SEASON_ID='22025', TEAM_ID=1610612751),
 Row(GAME_ID='0022500254', SEASON_ID='22025', TEAM_ID=1610612757),
 Row(GAME_ID='0022500253', SEASON_ID='22025', TEAM_ID=1610612747),
 Row(GAME_ID='0022500251', SEASON_ID='22025', TEAM_ID=1610612737),
 Row(GAME_ID='0022500249', SEASON_ID='22025', TEAM_ID=1610612753),
 Row(GAME_ID='0022500259', SEASON_ID='22025', TEAM_ID=1610612750),
 Row(GAME_ID='0022500263', SEASON_ID='22025', TEAM_ID=1610612757),
 Row(GAME_ID='0022500257', SEASON_ID='22025', TEAM_ID=1610612748),
 Row(GAME_ID='0022500255', SEASON_ID='22025', TEAM_ID=1610612739),
 Row(GAME_ID='0022500260', SEASON_ID='22025', TEAM_ID=1610612740),
 Row(GAME_ID='0022500262', SEASON_ID='22025', TEAM_ID=1610612742),
 Row(GAME_ID='0022500258', SEASON_ID='22025', TEAM_ID=1610612755),
 Row(GAME_ID='0022500256', SEASON_ID='22025', TEAM_ID=1610612754),
 Row(GAME_ID='0022500261', SEASON_ID='22025', TEAM_ID=1610612760),
 Row(GAME_ID='0022500266', SEASON_ID='22025', TEAM_ID=1610612749),
 Row(GAME_ID='0022500264', SEASON_ID='22025', TEAM_ID=1610612753),
 Row(GAME_ID='0022500267', SEASON_ID='22025', TEAM_ID=1610612759),
 Row(GAME_ID='0022500265', SEASON_ID='22025', TEAM_ID=1610612763),
 Row(GAME_ID='0022500050', SEASON_ID='22025', TEAM_ID=1610612761),
 Row(GAME_ID='0022500054', SEASON_ID='22025', TEAM_ID=1610612745),
 Row(GAME_ID='0022500051', SEASON_ID='22025', TEAM_ID=1610612741),
 Row(GAME_ID='0022500053', SEASON_ID='22025', TEAM_ID=1610612756),
 Row(GAME_ID='0022500049', SEASON_ID='22025', TEAM_ID=1610612738),
 Row(GAME_ID='0022500052', SEASON_ID='22025', TEAM_ID=1610612742),
 Row(GAME_ID='0022500048', SEASON_ID='22025', TEAM_ID=1610612739),
 Row(GAME_ID='0022500056', SEASON_ID='22025', TEAM_ID=1610612744),
 Row(GAME_ID='0022500055', SEASON_ID='22025', TEAM_ID=1610612762),
 Row(GAME_ID='0022500269', SEASON_ID='22025', TEAM_ID=1610612753),
 Row(GAME_ID='0022500272', SEASON_ID='22025', TEAM_ID=1610612749),
 Row(GAME_ID='0022500273', SEASON_ID='22025', TEAM_ID=1610612742),
 Row(GAME_ID='0022500274', SEASON_ID='22025', TEAM_ID=1610612743),
 Row(GAME_ID='0022500268', SEASON_ID='22025', TEAM_ID=1610612766),
 Row(GAME_ID='0022500270', SEASON_ID='22025', TEAM_ID=1610612740),
 Row(GAME_ID='0022500271', SEASON_ID='22025', TEAM_ID=1610612741),
 Row(GAME_ID='0022500279', SEASON_ID='22025', TEAM_ID=1610612761),
 Row(GAME_ID='0022500281', SEASON_ID='22025', TEAM_ID=1610612756),
 Row(GAME_ID='0022500275', SEASON_ID='22025', TEAM_ID=1610612755),
 Row(GAME_ID='0022500280', SEASON_ID='22025', TEAM_ID=1610612760),
 Row(GAME_ID='0022500276', SEASON_ID='22025', TEAM_ID=1610612737),
 Row(GAME_ID='0022500278', SEASON_ID='22025', TEAM_ID=1610612739),
 Row(GAME_ID='0022500282', SEASON_ID='22025', TEAM_ID=1610612762),
 Row(GAME_ID='0022500277', SEASON_ID='22025', TEAM_ID=1610612738),
 Row(GAME_ID='0022500292', SEASON_ID='22025', TEAM_ID=1610612758),
 Row(GAME_ID='0022500291', SEASON_ID='22025', TEAM_ID=1610612744),
 Row(GAME_ID='0022500289', SEASON_ID='22025', TEAM_ID=1610612740),
 Row(GAME_ID='0022500287', SEASON_ID='22025', TEAM_ID=1610612763),
 Row(GAME_ID='0022500284', SEASON_ID='22025', TEAM_ID=1610612761),
 Row(GAME_ID='0022500286', SEASON_ID='22025', TEAM_ID=1610612748),
 Row(GAME_ID='0022500290', SEASON_ID='22025', TEAM_ID=1610612756),
 Row(GAME_ID='0022500285', SEASON_ID='22025', TEAM_ID=1610612751),
 Row(GAME_ID='0022500283', SEASON_ID='22025', TEAM_ID=1610612754),
 Row(GAME_ID='0022500288', SEASON_ID='22025', TEAM_ID=1610612749),
 Row(GAME_ID='0022500057', SEASON_ID='22025', TEAM_ID=1610612764),
 Row(GAME_ID='0022500058', SEASON_ID='22025', TEAM_ID=1610612755),
 Row(GAME_ID='0022500059', SEASON_ID='22025', TEAM_ID=1610612747),
 Row(GAME_ID='0022500068', SEASON_ID='22025', TEAM_ID=1610612758),
 Row(GAME_ID='0022500063', SEASON_ID='22025', TEAM_ID=1610612761),
 Row(GAME_ID='0022500065', SEASON_ID='22025', TEAM_ID=1610612740),
 Row(GAME_ID='0022500062', SEASON_ID='22025', TEAM_ID=1610612748),
 Row(GAME_ID='0022500060', SEASON_ID='22025', TEAM_ID=1610612738),
 Row(GAME_ID='0022500066', SEASON_ID='22025', TEAM_ID=1610612744),
 Row(GAME_ID='0022500064', SEASON_ID='22025', TEAM_ID=1610612760),
 Row(GAME_ID='0022500061', SEASON_ID='22025', TEAM_ID=1610612766),
 Row(GAME_ID='0022500067', SEASON_ID='22025', TEAM_ID=1610612757),
 Row(GAME_ID='0022500077', SEASON_ID='22025', TEAM_ID=1610612762),
 Row(GAME_ID='0022500076', SEASON_ID='22025', TEAM_ID=1610612743),
 Row(GAME_ID='0022500073', SEASON_ID='22025', TEAM_ID=1610612754),
 Row(GAME_ID='0022500071', SEASON_ID='22025', TEAM_ID=1610612766),
 Row(GAME_ID='0022500074', SEASON_ID='22025', TEAM_ID=1610612752),
 Row(GAME_ID='0022500072', SEASON_ID='22025', TEAM_ID=1610612765),
 Row(GAME_ID='0022500079', SEASON_ID='22025', TEAM_ID=1610612746),
 Row(GAME_ID='0022500069', SEASON_ID='22025', TEAM_ID=1610612737),
 Row(GAME_ID='0022500078', SEASON_ID='22025', TEAM_ID=1610612747),
 Row(GAME_ID='0022500070', SEASON_ID='22025', TEAM_ID=1610612751),
 Row(GAME_ID='0022500075', SEASON_ID='22025', TEAM_ID=1610612760),
 Row(GAME_ID='0022500298', SEASON_ID='22025', TEAM_ID=1610612744),
 Row(GAME_ID='0022500295', SEASON_ID='22025', TEAM_ID=1610612754),
 Row(GAME_ID='0022500299', SEASON_ID='22025', TEAM_ID=1610612756),
 Row(GAME_ID='0022500297', SEASON_ID='22025', TEAM_ID=1610612749),
 Row(GAME_ID='0022500293', SEASON_ID='22025', TEAM_ID=1610612750),
 Row(GAME_ID='0022500300', SEASON_ID='22025', TEAM_ID=1610612746),
 Row(GAME_ID='0022500296', SEASON_ID='22025', TEAM_ID=1610612748),
 Row(GAME_ID='0022500294', SEASON_ID='22025', TEAM_ID=1610612766),
 Row(GAME_ID='0022500306', SEASON_ID='22025', TEAM_ID=1610612750),
 Row(GAME_ID='0022500307', SEASON_ID='22025', TEAM_ID=1610612758),
 Row(GAME_ID='0022500304', SEASON_ID='22025', TEAM_ID=1610612755),
 Row(GAME_ID='0022500302', SEASON_ID='22025', TEAM_ID=1610612739),
 Row(GAME_ID='0022500301', SEASON_ID='22025', TEAM_ID=1610612762),
 Row(GAME_ID='0022500308', SEASON_ID='22025', TEAM_ID=1610612747),
 Row(GAME_ID='0022500305', SEASON_ID='22025', TEAM_ID=1610612757),
 Row(GAME_ID='0022500303', SEASON_ID='22025', TEAM_ID=1610612752),

In [62]:
list_structs = []
for r in wtf:
    list_structs.append({
        "game_id":r["GAME_ID"],
        "season_id" : r["SEASON_ID"],
        "team_id" : r["TEAM_ID"]
    })

In [66]:
# list_structs

In [67]:
arena_data = spark.read.format("json").option("multiline", True).load("raw_data/arena_data/arena_*.json")

In [74]:
arena_data.show()

+--------------+------------+-------+--------------------+----------+-------------+----------+----------+
|     arenaCity|arenaCountry|arenaId|           arenaName|arenaState|arenaTimezone|    gameId|   team_id|
+--------------+------------+-------+--------------------+----------+-------------+----------+----------+
|     Cleveland|          US|1000006|Rocket Mortgage F...|        OH|      Eastern|0021900030|1610612739|
|     Cleveland|          US|1000006|Rocket Mortgage F...|        OH|      Eastern|0022000010|1610612739|
|     Cleveland|          US|1000006|Rocket Mortgage F...|        OH|      Eastern|0022100017|1610612739|
|     Cleveland|          US|1000006|Rocket Mortgage F...|        OH|      Eastern|0022200039|1610612739|
|     Cleveland|          US|1000006|Rocket Mortgage F...|        OH|      Eastern|0022300081|1610612739|
|     Cleveland|          US|1000006|Rocket Mortgage F...|        OH|      Eastern|0022400080|1610612739|
|Salt Lake City|          US|    596|Vivint Smart Home...|        UT|     Mountain|0021500068|1610612762|
|Salt Lake City|          US|    596|Vivint Smart Home...|        UT|     Mountain|0021600024|1610612762|
|Salt Lake City|          US|    596|Vivint Smart Home...|        UT|     Mountain|0021700010|1610612762|
|Salt Lake City|          US|    596|Vivint Smart Home...|        UT|     Mountain|0021800024|1610612762|
|Salt Lake City|          US|    596|Vivint Smart Home...|        UT|     Mountain|0021900011|1610612762|
|   Los Angeles|          US|    100|L.A. Memorial Spo...|        CA|      Pacific|0028500015|1610612746|
|  Philadelphia|          US|     12|Core States Spect...|        PA|      Eastern|0028500032|1610612755|
|   Los Angeles|          US|    100|L.A. Memorial Spo...|        CA|      Pacific|0028600016|1610612746|
|  Philadelphia|          US|     12|Core States Spect...|        PA|      Eastern|0028600002|1610612755|
|   Los Angeles|          US|    100|L.A. Memorial Spo...|        CA|      Pacific|0028700015|1610612746|
|  Philadelphia|          US|     12|Core States Spect...|        PA|      Eastern|0028700003|1610612755|
|   Los Angeles|          US|    100|L.A. Memorial Spo...|        CA|      Pacific|0028800057|1610612746|
|  Philadelphia|          US|     12|Core States Spect...|        PA|      Eastern|0028800003|1610612755|
|   Los Angeles|          US|    100|L.A. Memorial Spo...|        CA|      Pacific|0028900001|1610612746|
+--------------+------------+-------+--------------------+----------+-------------+----------+----------+
only showing top 20 rows

In [79]:
arena_data.drop_duplicates(["arenaId"]).where(col('arenaId')!=0).select(
    col('arenaCity').alias('arena_city'),
    col('arenaCountry').alias('arena_country'),
    col('arenaId').alias('arena_source_id'),
    col('arenaName').alias('arena_name'),
    col('arenaState').alias('arena_state'),
    col('arenaTimezone').alias('arena_timezone'),
    col('team_id').alias("team_source_id")
).show(100)

+--------------+-------------+---------------+--------------------+-----------+--------------+--------------+
|    arena_city|arena_country|arena_source_id|          arena_name|arena_state|arena_timezone|team_source_id|
+--------------+-------------+---------------+--------------------+-----------+--------------+--------------+
|   San Antonio|           US|              1|           Alamodome|         TX|       Central|    1610612759|
|       Phoenix|           US|              2|   US Airways Center|         AZ|      Mountain|    1610612756|
|    Sacramento|           US|              3|   Sleep Train Arena|         CA|       Pacific|    1610612758|
|     Milwaukee|           US|              5|BMO Harris Bradle...|         WI|       Central|    1610612749|
|     Charlotte|           US|              9|     Spectrum Center|         NC|       Eastern|    1610612766|
|    New Jersey|           US|             11|         IZOD Center|         NJ|       Eastern|    1610612751|
|  Philadelphia|           US|             12|Core States Spect...|         PA|       Eastern|    1610612755|
|Salt Lake City|           US|             15|EnergySolutions A...|         UT|      Mountain|    1610612762|
|        Boston|           US|             17|           TD Garden|         MA|       Eastern|    1610612738|
|     Vancouver|           US|             19|            GM Place|         BC|       Pacific|    1610612763|
|   Los Angeles|           US|             20| Great Western Forum|         LA|       Pacific|    1610612747|
|     Cleveland|           US|             22| Quicken Loans Arena|         OH|       Eastern|    1610612739|
|      New York|           US|             30|Madison Square Ga...|         NY|       Eastern|    1610612752|
|  Indianapolis|           US|             33| Market Square Arena|         IN|       Eastern|    1610612754|
|        Denver|           US|             36|McNichols Sports ...|         CO|      Mountain|    1610612743|
|         Miami|           US|             38|         Miami Arena|         FL|       Eastern|    1610612748|
|       Atlanta|           US|             41|                Omni|         GA|       Eastern|    1610612737|
|       Orlando|           US|             43|         Amway Arena|         FL|       Eastern|    1610612753|
|       Detroit|           US|             44|Palace of Auburn ...|         MI|       Eastern|    1610612765|
|       Memphis|           US|             48|             Pyramid|         TN|       Central|    1610612763|
|        Dallas|           US|             49|       Reunion Arena|         TX|       Central|    1610612742|
|      Portland|           US|             51|         Moda Center|         OR|       Pacific|    1610612757|
|      San Jose|           US|             53|      San Jose Arena|         CA|       Pacific|    1610612744|
|       Toronto|           US|             56|             SkyDome|         OT|       Eastern|    1610612761|
|   Los Angeles|           US|             59|        Sports Arena|         CA|       Pacific|    1610612746|
|       Houston|           US|             60|       Compaq Center|         TX|       Central|    1610612745|
|   Minneapolis|           US|             61|       Target Center|         MN|       Central|    1610612750|
|       Chicago|           US|             66|       United Center|         IL|       Central|    1610612741|
|       Oakland|           US|             71|        ORACLE Arena|         CA|       Pacific|    1610612744|
|       Seattle|           US|             72|            KeyArena|         WA|       Pacific|    1610612760|
|       Toronto|           US|             73|   Maple Leaf Garden|         ON|       Eastern|    1610612761|
|    Washington|           US|             74|        US Air Arena|         DC|       Eastern|    1610612764|
|       Atlanta|           US|             76|  Alexander Coliseum|         GA|       Eastern|    1610612737|
|    Washington|           US|             77|   Capital One Arena|         DC|       Eastern|    1610612764|
|       Atlanta|           US|             78|        Georgia Dome|         GA|       Eastern|    1610612737|
|   Los Angeles|           US|            100|L.A. Memorial Spo...|         CA|       Pacific|    1610612746|
|        Boston|           US|            111|       Boston Garden|         MA|       Eastern|    1610612738|
|   Minneapolis|           US|            112|          Metro Dome|         MN|       Central|    1610612750|
|       Toronto|           US|            116|   Air Canada Centre|         ON|       Eastern|    1610612761|
|  Philadelphia|           US|            130|     Wachovia Center|         PA|       Eastern|    1610612755|
|  Tokyo, Japan|           JP|            134|          Tokyo Dome|           |       Eastern|    1610612750|
|       Atlanta|           US|            135|       Philips Arena|         GA|       Eastern|    1610612737|
|  Indianapolis|           US|            136|Bankers Life Fiel...|         IN|       Eastern|    1610612754|
|   Los Angeles|           US|            137|      STAPLES Center|         CA|       Pacific|    1610612746|
|        Denver|           US|            139|        Pepsi Center|         CO|      Mountain|    1610612743|
|         Miami|           US|            146|AmericanAirlines ...|         FL|       Eastern|    1610612748|
|       Orlando|           US|            155|         Amway Arena|         FL|       Eastern|    1610612753|
|   New Orleans|           US|            160|Smoothie King Center|         LA|       Central|    1610612740|
|        Dallas|           US|            193|American Airlines...|         TX|       Central|    1610612742|
| Oklahoma City|           US|            196|Chesapeake Energy...|         OK|       Central|    1610612740|
|   San Antonio|           US|            199|         AT&T Center|         TX|       Central|    1610612759|
|       Houston|           US|            215|       Toyota Center|         TX|       Central|    1610612745|
|         Tokyo|           JP|            216| Saitama Super Arena|           |              |    1610612746|
|       Memphis|           US|            242|          FedExForum|         TN|       Central|    1610612763|
|        Newark|           US|            389|   Prudential Center|         NJ|       Eastern|    1610612751|
|  Philadelphia|           US|            419|  Wells Fargo Center|         PA|       Eastern|    1610612755|
|       Orlando|           US|            430|        Amway Center|         FL|       Eastern|    1610612753|
|      Brooklyn|           US|            461|     Barclays Center|         NY|       Eastern|    1610612751|
|       Phoenix|           US|            584|Talking Stick Res...|         AZ|      Mountain|    1610612756|
|Salt Lake City|           US|            596|Vivint Smart Home...|         UT|      Mountain|    1610612762|
|    Sacramento|           US|            609|     Golden 1 Center|         CA|       Pacific|    1610612758|
|       Detroit|           US|            624|Little Caesars Arena|         MI|       Eastern|    1610612765|
|     Milwaukee|           US|            642|        Fiserv Forum|         WI|       Central|    1610612749|
|       Toronto|           CA|            643|    Scotiabank Arena|         ON|       Eastern|    1610612761|
|       Atlanta|           US|            650|    State Farm Arena|         GA|       Eastern|    1610612737|
|     Cleveland|           US|        1000006|Rocket Mortgage F...|         OH|       Eastern|    1610612739|
| San Francisco|           US|        1000011|        Chase Center|         CA|       Pacific|    1610612744|
|         Tampa|           US|        1000045|        Amalie Arena|         FL|       Eastern|    1610612761|
|        Denver|           US|        1000046|          Ball Arena|         CO|      Mountain|    1610612743|
|       Phoenix|           US|        1000047|  Phoenix Suns Arena|         AZ|      Mountain|    1610612756|
|Salt Lake City|           US|        1000048|        Vivint Arena|         UT|      Mountain|    1610612762|
|         Miami|           US|        1000050|           FTX Arena|         FL|       Eastern|    1610612748|
|       Phoenix|           US|        1000051|    Footprint Center|         AZ|      Mountain|    1610612756|
| Oklahoma City|           US|        1000052|       Paycom Center|         OK|       Central|    1610612760|
|  Indianapolis|           US|        1000063|Gainbridge Fieldh...|         IN|       Eastern|    1610612754|
|   Los Angeles|           US|        1000069|    Crypto.com Arena|         CA|       Pacific|    1610612746|
|         Miami|           US|        1000100|       Kaseya Center|         FL|       Eastern|    1610612748|
|Salt Lake City|           US|        1000106|        Delta Center|         UT|      Mountain|    1610612762|
|   San Antonio|           US|        1000118|   Frost Bank Center|         TX|       Central|    1610612759|
|       Orlando|           US|        1000125|          Kia Center|         FL|       Eastern|    1610612753|
|     Inglewood|           US|        1000137|         Intuit Dome|         CA|       Pacific|    1610612746|
|     Cleveland|           US|        1000144|        Rocket Arena|         OH|       Eastern|    1610612739|
|  Philadelphia|           US|        1000152|Xfinity Mobile Arena|         PA|       Eastern|    1610612755|
|       Phoenix|           US|        1000159|Mortgage Matchup ...|         AZ|      Mountain|    1610612756|
+--------------+-------------+---------------+--------------------+-----------+--------------+--------------+

In [4]:
from pyspark.sql import SparkSession
from pyspark.sql.types import *
from pyspark.sql.functions import col

spark = (SparkSession.builder
         .master("local[*]")
         .appName("Load_Arenas")
         .config("spark.jars", "file:///C:/spark-jars/mssql-jdbc-13.4.0.jre11.jar")
         .getOrCreate()
)

server = "localhost:1433"
database = "Basketball"

url = f"jdbc:sqlserver://{server};databaseName={database};trustServerCertificate=true"
properties = {
    "user": "spark_user2",
    "password": "1234",
    "driver": "com.microsoft.sqlserver.jdbc.SQLServerDriver"
}

In [5]:
db_arenas_df = spark.read.jdbc(url=url, table="arena", properties=properties)

In [6]:
db_arenas_df.show()

+--------+----------+-------------+---------------+----------+-----------+--------------+--------------+
|arena_id|arena_city|arena_country|arena_source_id|arena_name|arena_state|arena_timezone|team_source_id|
+--------+----------+-------------+---------------+----------+-----------+--------------+--------------+
+--------+----------+-------------+---------------+----------+-----------+--------------+--------------+

In [7]:
arena_data = spark.read.format("json").option("multiline", True).load("raw_data/arena_data/arena_combined.json")
arena_data.count()

1177

In [8]:
arena_data.show()

+------------+------------+-------+--------------------+----------+-------------+----------+----------+
|   arenaCity|arenaCountry|arenaId|           arenaName|arenaState|arenaTimezone|    gameId|   team_id|
+------------+------------+-------+--------------------+----------+-------------+----------+----------+
|     Atlanta|          US|     41|                Omni|        GA|      Eastern|0028500005|1610612737|
|      Boston|          US|    111|       Boston Garden|        MA|      Eastern|0028500033|1610612738|
|   Cleveland|          US|     22| Quicken Loans Arena|        OH|      Eastern|0028500016|1610612739|
|     Chicago|          US|     66|       United Center|        IL|      Central|0028500007|1610612741|
|      Dallas|          US|     49|       Reunion Arena|        TX|      Central|0028500017|1610612742|
|      Denver|          US|     36|McNichols Sports ...|        CO|     Mountain|0028500018|1610612743|
|    San Jose|          US|     53|      San Jose Arena|        CA|      Pacific|0028500008|1610612744|
|     Houston|          US|     60|       Compaq Center|        TX|      Central|0028500022|1610612745|
| Los Angeles|          US|    100|L.A. Memorial Spo...|        CA|      Pacific|0028500015|1610612746|
| Los Angeles|          US|     20| Great Western Forum|        LA|      Pacific|0028500061|1610612747|
|   Milwaukee|          US|      5|BMO Harris Bradle...|        WI|      Central|0028500013|1610612749|
|  New Jersey|          US|     11|         IZOD Center|        NJ|      Eastern|0028500004|1610612751|
|    New York|          US|     30|Madison Square Ga...|        NY|      Eastern|0028500012|1610612752|
|Indianapolis|          US|     33| Market Square Arena|        IN|      Eastern|0028500020|1610612754|
|Philadelphia|          US|     12|Core States Spect...|        PA|      Eastern|0028500032|1610612755|
|     Phoenix|          US|      2|   US Airways Center|        AZ|     Mountain|0028500026|1610612756|
|    Portland|          US|     51|         Moda Center|        OR|      Pacific|0028500009|1610612757|
|  Sacramento|          US|      3|   Sleep Train Arena|        CA|      Pacific|0028500006|1610612758|
| San Antonio|          US|      1|           Alamodome|        TX|      Central|0028500019|1610612759|
|     Seattle|          US|     72|            KeyArena|        WA|      Pacific|0028500048|1610612760|
+------------+------------+-------+--------------------+----------+-------------+----------+----------+
only showing top 20 rows

In [9]:
arena_data = arena_data.drop_duplicates(["arenaId"]).where(col('arenaId')!=0)

In [10]:
arena_data.count()

84

In [11]:
src = arena_data.join(other=db_arenas_df,on=arena_data["arenaId"] == db_arenas_df["arena_source_id"],how="leftanti")

In [13]:
src.count()

84

In [1]:
import json
import glob

In [14]:
final_df = src.select(
                col('arenaCity').alias('arena_city'),
                col('arenaCountry').alias('arena_country'),
                col('arenaId').alias('arena_source_id'),
                col('arenaName').alias('arena_name'),
                col('arenaState').alias('arena_state'),
                col('arenaTimezone').alias('arena_timezone'),
                col('team_id').alias("team_source_id")
            ).show()

+--------------+-------------+---------------+--------------------+-----------+--------------+--------------+
|    arena_city|arena_country|arena_source_id|          arena_name|arena_state|arena_timezone|team_source_id|
+--------------+-------------+---------------+--------------------+-----------+--------------+--------------+
|   San Antonio|           US|              1|           Alamodome|         TX|       Central|    1610612759|
|       Phoenix|           US|              2|   US Airways Center|         AZ|      Mountain|    1610612756|
|    Sacramento|           US|              3|   Sleep Train Arena|         CA|       Pacific|    1610612758|
|     Milwaukee|           US|              5|BMO Harris Bradle...|         WI|       Central|    1610612749|
|     Charlotte|           US|              9|     Spectrum Center|         NC|       Eastern|    1610612766|
|    New Jersey|           US|             11|         IZOD Center|         NJ|       Eastern|    1610612751|
|  Philadelphia|           US|             12|Core States Spect...|         PA|       Eastern|    1610612755|
|Salt Lake City|           US|             15|EnergySolutions A...|         UT|      Mountain|    1610612762|
|        Boston|           US|             17|           TD Garden|         MA|       Eastern|    1610612738|
|     Vancouver|           US|             19|            GM Place|         BC|       Pacific|    1610612763|
|   Los Angeles|           US|             20| Great Western Forum|         LA|       Pacific|    1610612747|
|     Cleveland|           US|             22| Quicken Loans Arena|         OH|       Eastern|    1610612739|
|      New York|           US|             30|Madison Square Ga...|         NY|       Eastern|    1610612752|
|  Indianapolis|           US|             33| Market Square Arena|         IN|       Eastern|    1610612754|
|        Denver|           US|             36|McNichols Sports ...|         CO|      Mountain|    1610612743|
|         Miami|           US|             38|         Miami Arena|         FL|       Eastern|    1610612748|
|       Atlanta|           US|             41|                Omni|         GA|       Eastern|    1610612737|
|       Orlando|           US|             43|         Amway Arena|         FL|       Eastern|    1610612753|
|       Detroit|           US|             44|Palace of Auburn ...|         MI|       Eastern|    1610612765|
|       Memphis|           US|             48|             Pyramid|         TN|       Central|    1610612763|
+--------------+-------------+---------------+--------------------+-----------+--------------+--------------+
only showing top 20 rows

In [2]:
all_data = []
files = glob.glob("raw_data/arena_data/arena_*.json")

In [3]:
for file in files:
    with open(file) as f:
        data = json.load(f)
        if isinstance(data, list):
            all_data.extend(data)
        else:
            all_data.append(data)

with open("raw_data/arena_data/arena_combined.json", "w") as f:
    json.dump(all_data, f, indent=4)

print(f"Combined {len(files)} files into one, total records: {len(all_data)}")

Combined 1177 files into one, total records: 1177

In [15]:
from nba_api.stats.endpoints import teaminfocommon, teamdetails

In [17]:
df = teaminfocommon.TeamInfoCommon(team_id=1610612747).get_data_frames()

In [22]:
team_info_df = df[0]

In [34]:
team_info_df

,TEAM_ID,SEASON_YEAR,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CONFERENCE,TEAM_DIVISION,TEAM_CODE,TEAM_SLUG,W,L,PCT,CONF_RANK,DIV_RANK,MIN_YEAR,MAX_YEAR
0,1610612747,2025-26,Los Angeles,Lakers,LAL,West,Pacific,lakers,lakers,53,29,0.646,4,1,1948,2026

In [19]:
df_1 = teamdetails.TeamDetails(team_id=1610612747).get_data_frames()

In [23]:
team_details_df = df_1[0]

In [35]:
team_details_df

,TEAM_ID,ABBREVIATION,NICKNAME,YEARFOUNDED,CITY,ARENA,ARENACAPACITY,OWNER,GENERALMANAGER,HEADCOACH,DLEAGUEAFFILIATION
0,1610612747,LAL,Lakers,1948,Los Angeles,Crypto.com Arena,19060,Mark Walter & Jeanie Buss,Rob Pelinka,JJ Redick,South Bay Lakers

In [36]:
res = team_info_df.merge(right=team_details_df,how="inner",on="TEAM_ID" )
res.to_json

,TEAM_ID,SEASON_YEAR,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CONFERENCE,TEAM_DIVISION,TEAM_CODE,TEAM_SLUG,W,...,ABBREVIATION,NICKNAME,YEARFOUNDED,CITY,ARENA,ARENACAPACITY,OWNER,GENERALMANAGER,HEADCOACH,DLEAGUEAFFILIATION
0,1610612747,2025-26,Los Angeles,Lakers,LAL,West,Pacific,lakers,lakers,53,...,LAL,Lakers,1948,Los Angeles,Crypto.com Arena,19060,Mark Walter & Jeanie Buss,Rob Pelinka,JJ Redick,South Bay Lakers

In [37]:
import pandas as pd
import time

In [26]:
all_teams = pd.read_json("raw_data/all_teams.json")

In [33]:
all_teams_ids = all_teams["id"].tolist()

In [38]:
all_results = []
for team_id in all_teams_ids:
    try:
        df = teaminfocommon.TeamInfoCommon(team_id=team_id).get_data_frames()
        team_info_df = df[0]
        df_1 = teamdetails.TeamDetails(team_id=team_id).get_data_frames()
        team_details_df = df_1[0]
        res = team_info_df.merge(right=team_details_df,how="inner",on="TEAM_ID" )

        all_results.append(res)
        print(f"✅ Done team {team_id}")
    except Exception as e:
        print(f"❌ Failed team {team_id}: {e}")

    time.sleep(2)


final_df = pd.concat(all_results, ignore_index=True)

✅ Done team 1610612737
✅ Done team 1610612738
✅ Done team 1610612739
✅ Done team 1610612740
✅ Done team 1610612741
✅ Done team 1610612742
✅ Done team 1610612743
✅ Done team 1610612744
✅ Done team 1610612745
✅ Done team 1610612746
✅ Done team 1610612747
✅ Done team 1610612748
✅ Done team 1610612749
✅ Done team 1610612750
✅ Done team 1610612751
✅ Done team 1610612752
✅ Done team 1610612753
✅ Done team 1610612754
✅ Done team 1610612755
✅ Done team 1610612756
✅ Done team 1610612757
✅ Done team 1610612758
✅ Done team 1610612759
✅ Done team 1610612760
✅ Done team 1610612761
✅ Done team 1610612762
✅ Done team 1610612763
✅ Done team 1610612764
✅ Done team 1610612765
✅ Done team 1610612766

In [39]:
final_df

,TEAM_ID,SEASON_YEAR,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CONFERENCE,TEAM_DIVISION,TEAM_CODE,TEAM_SLUG,W,...,ABBREVIATION,NICKNAME,YEARFOUNDED,CITY,ARENA,ARENACAPACITY,OWNER,GENERALMANAGER,HEADCOACH,DLEAGUEAFFILIATION
0,1610612737,2025-26,Atlanta,Hawks,ATL,East,Southeast,hawks,hawks,46,...,ATL,Hawks,1949,Atlanta,State Farm Arena,18729,Tony Ressler,Travis Schlenk,Quin Snyder,College Park Skyhawks
1,1610612738,2025-26,Boston,Celtics,BOS,East,Atlantic,celtics,celtics,56,...,BOS,Celtics,1946,Boston,TD Garden,18624,Bill Chisholm,Brad Stevens,Joe Mazzulla,Maine Celtics
2,1610612739,2025-26,Cleveland,Cavaliers,CLE,East,Central,cavaliers,cavaliers,52,...,CLE,Cavaliers,1970,Cleveland,Rocket Arena,20562,Dan Gilbert,Koby Altman,Kenny Atkinson,Cleveland Charge
3,1610612740,2025-26,New Orleans,Pelicans,NOP,West,Southwest,pelicans,pelicans,26,...,NOP,Pelicans,2002,New Orleans,Smoothie King Center,None,Gayle Benson,Troy Weaver,Jamahl Mosley,Birmingham Squadron
4,1610612741,2025-26,Chicago,Bulls,CHI,East,Central,bulls,bulls,31,...,CHI,Bulls,1966,Chicago,United Center,21711,Michael Reinsdorf,,,Windy City Bulls
5,1610612742,2025-26,Dallas,Mavericks,DAL,West,Southwest,mavericks,mavericks,26,...,DAL,Mavericks,1980,Dallas,American Airlines Center,19200,Patrick Dumont,,,Texas Legends
6,1610612743,2025-26,Denver,Nuggets,DEN,West,Northwest,nuggets,nuggets,54,...,DEN,Nuggets,1976,Denver,Ball Arena,None,Stan Kroenke,,David Adelman,Grand Rapids Gold
7,1610612744,2025-26,Golden State,Warriors,GSW,West,Pacific,warriors,warriors,37,...,GSW,Warriors,1946,Golden State,Chase Center,None,Joe Lacob,Mike Dunleavy Jr.,Steve Kerr,Santa Cruz Warriors
8,1610612745,2025-26,Houston,Rockets,HOU,West,Southwest,rockets,rockets,52,...,HOU,Rockets,1967,Houston,Toyota Center,18104,Tilman Fertitta,Rafael Stone,Ime Udoka,Rio Grande Valley Vipers
9,1610612746,2025-26,LA,Clippers,LAC,West,Pacific,clippers,clippers,42,...,LAC,Clippers,1970,Los Angeles,Intuit Dome,19060,Steve Ballmer,Michael Winger,Tyronn Lue,Agua Caliente Clippers of Ontario
10,1610612747,2025-26,Los Angeles,Lakers,LAL,West,Pacific,lakers,lakers,53,...,LAL,Lakers,1948,Los Angeles,Crypto.com Arena,19060,Mark Walter & Jeanie Buss,Rob Pelinka,JJ Redick,South Bay Lakers
11,1610612748,2025-26,Miami,Heat,MIA,East,Southeast,heat,heat,43,...,MIA,Heat,1988,Miami,Kaseya Center,19600,Micky Arison,Pat Riley,Erik Spoelstra,Sioux Falls Skyforce
12,1610612749,2025-26,Milwaukee,Bucks,MIL,East,Central,bucks,bucks,32,...,MIL,Bucks,1968,Milwaukee,Fiserv Forum,17500,Wesley Edens,Jon Horst,Taylor Jenkins,Wisconsin Herd
13,1610612750,2025-26,Minnesota,Timberwolves,MIN,West,Northwest,timberwolves,timberwolves,49,...,MIN,Timberwolves,1989,Minnesota,Target Center,19356,Marc Lore & Alex Rodriguez,Tim Connelly,Chris Finch,Iowa Wolves
14,1610612751,2025-26,Brooklyn,Nets,BKN,East,Atlantic,nets,nets,20,...,BKN,Nets,1976,Brooklyn,Barclays Center,None,Joe Tsai,Sean Marks,Jordi Fernandez,Long Island Nets
15,1610612752,2025-26,New York,Knicks,NYK,East,Atlantic,knicks,knicks,53,...,NYK,Knicks,1946,New York,Madison Square Garden,19763,Jim Dolan,Leon Rose,Mike Brown,Westchester Knicks
16,1610612753,2025-26,Orlando,Magic,ORL,East,Southeast,magic,magic,45,...,ORL,Magic,1989,Orlando,Kia Center,0,Dan DeVos,John Hammond,,Osceola Magic
17,1610612754,2025-26,Indiana,Pacers,IND,East,Central,pacers,pacers,19,...,IND,Pacers,1976,Indiana,Gainbridge Fieldhouse,18345,Herb Simon,Kevin Pritchard,Rick Carlisle,Noblesville Boom
18,1610612755,2025-26,Philadelphia,76ers,PHI,East,Atlantic,sixers,sixers,45,...,PHI,76ers,1949,Philadelphia,Xfinity Mobile Arena,None,Joshua Harris & David Blitzer,Elton Brand,Nick Nurse,Delaware Blue Coats
19,1610612756,2025-26,Phoenix,Suns,PHX,West,Pacific,suns,suns,45,...,PHX,Suns,1968,Phoenix,Mortgage Matchup Center,None,Mat Ishbia,Brian Gregory,Jordan Ott,Valley Suns
20,1610612757,2025-26,Portland,Trail Blazers,POR,West,Northwest,blazers,blazers,42,...,POR,Trail Blazers,1970,Portland,Moda Center,19980,Tom Dundon,Joe Cronin,Chauncey Billups,Rip City Remix
21,1610612758,2025-26,Sacramento,Kings,SAC,West,Pacific,kings,kings,22,...,SAC,Kings,1948,Sacramento,Golden 1 Center,17500,Vivek Ranadive,Monte McNair,Doug Christie,Stockton Kings
22,1610612759,2025-26,San Antonio,Spurs,SAS,West,Southwest,spurs,spurs,62,...,SAS,Spurs,1976,San Antonio,Frost Bank Center,18694,Peter Holt,Brian Wright,Mitch Johnson,Austin Spurs
23,1610612760,2025-26,Oklahoma City,Thunder,OKC,West,Northwest,thunder,thunder,64,...,OKC,Thunder,1967,Oklahoma City,Paycom Center,None,Clay Bennett,Sam Presti,Mark Daigneault,Oklahoma City Blue
24,1610612761,2025-26,Toronto,Raptors,TOR,East,Atlantic,raptors,raptors,46,...,TOR,Raptors,1995,Toronto,Scotiabank Arena,None,Lawrence Tanenbaum,,Darko Rajakovic,Raptors 905
25,1610612762,2025-26,Utah,Jazz,UTA,West,Northwest,jazz,jazz,22,...,UTA,Jazz,1974,Utah,Delta Center,None,Ryan Smith,Justin Zanik,Will Hardy,Salt Lake City Stars
26,1610612763,2025-26,Memphis,Grizzlies,MEM,West,Southwest,grizzlies,grizzlies,25,...,MEM,Grizzlies,1995,Memphis,FedExForum,18119,Robert Pera,Zach Kleiman,Tuomas Iisalo,Memphis Hustle
27,1610612764,2025-26,Washington,Wizards,WAS,East,Southeast,wizards,wizards,17,...,WAS,Wizards,1961,Washington,Capital One Arena,20647,Ted Leonsis,Will Dawkins,Brian Keefe,Capital City Go-Go
28,1610612765,2025-26,Detroit,Pistons,DET,East,Central,pistons,pistons,60,...,DET,Pistons,1948,Detroit,Little Caesars Arena,None,Tom Gores,Trajan Langdon,J. B. Bickerstaff,Motor City Cruise
29,1610612766,2025-26,Charlotte,Hornets,CHA,East,Southeast,hornets,hornets,44,...,CHA,Hornets,1988,Charlotte,Spectrum Center,19026,Rick Schnall & Gabe Plotkin,Jeff Peterson,Charles Lee,Greensboro Swarm

In [41]:
pd.read_json("raw_data/team_info/all_teams_info.json")

,TEAM_ID,SEASON_YEAR,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CONFERENCE,TEAM_DIVISION,TEAM_CODE,TEAM_SLUG,W,...,ABBREVIATION,NICKNAME,YEARFOUNDED,CITY,ARENA,ARENACAPACITY,OWNER,GENERALMANAGER,HEADCOACH,DLEAGUEAFFILIATION
0,1610612737,2025-26,Atlanta,Hawks,ATL,East,Southeast,hawks,hawks,46,...,ATL,Hawks,1949,Atlanta,State Farm Arena,18729.0,Tony Ressler,Travis Schlenk,Quin Snyder,College Park Skyhawks
1,1610612738,2025-26,Boston,Celtics,BOS,East,Atlantic,celtics,celtics,56,...,BOS,Celtics,1946,Boston,TD Garden,18624.0,Bill Chisholm,Brad Stevens,Joe Mazzulla,Maine Celtics
2,1610612739,2025-26,Cleveland,Cavaliers,CLE,East,Central,cavaliers,cavaliers,52,...,CLE,Cavaliers,1970,Cleveland,Rocket Arena,20562.0,Dan Gilbert,Koby Altman,Kenny Atkinson,Cleveland Charge
3,1610612740,2025-26,New Orleans,Pelicans,NOP,West,Southwest,pelicans,pelicans,26,...,NOP,Pelicans,2002,New Orleans,Smoothie King Center,NaN,Gayle Benson,Troy Weaver,Jamahl Mosley,Birmingham Squadron
4,1610612741,2025-26,Chicago,Bulls,CHI,East,Central,bulls,bulls,31,...,CHI,Bulls,1966,Chicago,United Center,21711.0,Michael Reinsdorf,,,Windy City Bulls
5,1610612742,2025-26,Dallas,Mavericks,DAL,West,Southwest,mavericks,mavericks,26,...,DAL,Mavericks,1980,Dallas,American Airlines Center,19200.0,Patrick Dumont,,,Texas Legends
6,1610612743,2025-26,Denver,Nuggets,DEN,West,Northwest,nuggets,nuggets,54,...,DEN,Nuggets,1976,Denver,Ball Arena,NaN,Stan Kroenke,,David Adelman,Grand Rapids Gold
7,1610612744,2025-26,Golden State,Warriors,GSW,West,Pacific,warriors,warriors,37,...,GSW,Warriors,1946,Golden State,Chase Center,NaN,Joe Lacob,Mike Dunleavy Jr.,Steve Kerr,Santa Cruz Warriors
8,1610612745,2025-26,Houston,Rockets,HOU,West,Southwest,rockets,rockets,52,...,HOU,Rockets,1967,Houston,Toyota Center,18104.0,Tilman Fertitta,Rafael Stone,Ime Udoka,Rio Grande Valley Vipers
9,1610612746,2025-26,LA,Clippers,LAC,West,Pacific,clippers,clippers,42,...,LAC,Clippers,1970,Los Angeles,Intuit Dome,19060.0,Steve Ballmer,Michael Winger,Tyronn Lue,Agua Caliente Clippers of Ontario
10,1610612747,2025-26,Los Angeles,Lakers,LAL,West,Pacific,lakers,lakers,53,...,LAL,Lakers,1948,Los Angeles,Crypto.com Arena,19060.0,Mark Walter & Jeanie Buss,Rob Pelinka,JJ Redick,South Bay Lakers
11,1610612748,2025-26,Miami,Heat,MIA,East,Southeast,heat,heat,43,...,MIA,Heat,1988,Miami,Kaseya Center,19600.0,Micky Arison,Pat Riley,Erik Spoelstra,Sioux Falls Skyforce
12,1610612749,2025-26,Milwaukee,Bucks,MIL,East,Central,bucks,bucks,32,...,MIL,Bucks,1968,Milwaukee,Fiserv Forum,17500.0,Wesley Edens,Jon Horst,Taylor Jenkins,Wisconsin Herd
13,1610612750,2025-26,Minnesota,Timberwolves,MIN,West,Northwest,timberwolves,timberwolves,49,...,MIN,Timberwolves,1989,Minnesota,Target Center,19356.0,Marc Lore & Alex Rodriguez,Tim Connelly,Chris Finch,Iowa Wolves
14,1610612751,2025-26,Brooklyn,Nets,BKN,East,Atlantic,nets,nets,20,...,BKN,Nets,1976,Brooklyn,Barclays Center,NaN,Joe Tsai,Sean Marks,Jordi Fernandez,Long Island Nets
15,1610612752,2025-26,New York,Knicks,NYK,East,Atlantic,knicks,knicks,53,...,NYK,Knicks,1946,New York,Madison Square Garden,19763.0,Jim Dolan,Leon Rose,Mike Brown,Westchester Knicks
16,1610612753,2025-26,Orlando,Magic,ORL,East,Southeast,magic,magic,45,...,ORL,Magic,1989,Orlando,Kia Center,0.0,Dan DeVos,John Hammond,,Osceola Magic
17,1610612754,2025-26,Indiana,Pacers,IND,East,Central,pacers,pacers,19,...,IND,Pacers,1976,Indiana,Gainbridge Fieldhouse,18345.0,Herb Simon,Kevin Pritchard,Rick Carlisle,Noblesville Boom
18,1610612755,2025-26,Philadelphia,76ers,PHI,East,Atlantic,sixers,sixers,45,...,PHI,76ers,1949,Philadelphia,Xfinity Mobile Arena,NaN,Joshua Harris & David Blitzer,Elton Brand,Nick Nurse,Delaware Blue Coats
19,1610612756,2025-26,Phoenix,Suns,PHX,West,Pacific,suns,suns,45,...,PHX,Suns,1968,Phoenix,Mortgage Matchup Center,NaN,Mat Ishbia,Brian Gregory,Jordan Ott,Valley Suns
20,1610612757,2025-26,Portland,Trail Blazers,POR,West,Northwest,blazers,blazers,42,...,POR,Trail Blazers,1970,Portland,Moda Center,19980.0,Tom Dundon,Joe Cronin,Chauncey Billups,Rip City Remix
21,1610612758,2025-26,Sacramento,Kings,SAC,West,Pacific,kings,kings,22,...,SAC,Kings,1948,Sacramento,Golden 1 Center,17500.0,Vivek Ranadive,Monte McNair,Doug Christie,Stockton Kings
22,1610612759,2025-26,San Antonio,Spurs,SAS,West,Southwest,spurs,spurs,62,...,SAS,Spurs,1976,San Antonio,Frost Bank Center,18694.0,Peter Holt,Brian Wright,Mitch Johnson,Austin Spurs
23,1610612760,2025-26,Oklahoma City,Thunder,OKC,West,Northwest,thunder,thunder,64,...,OKC,Thunder,1967,Oklahoma City,Paycom Center,NaN,Clay Bennett,Sam Presti,Mark Daigneault,Oklahoma City Blue
24,1610612761,2025-26,Toronto,Raptors,TOR,East,Atlantic,raptors,raptors,46,...,TOR,Raptors,1995,Toronto,Scotiabank Arena,NaN,Lawrence Tanenbaum,,Darko Rajakovic,Raptors 905
25,1610612762,2025-26,Utah,Jazz,UTA,West,Northwest,jazz,jazz,22,...,UTA,Jazz,1974,Utah,Delta Center,NaN,Ryan Smith,Justin Zanik,Will Hardy,Salt Lake City Stars
26,1610612763,2025-26,Memphis,Grizzlies,MEM,West,Southwest,grizzlies,grizzlies,25,...,MEM,Grizzlies,1995,Memphis,FedExForum,18119.0,Robert Pera,Zach Kleiman,Tuomas Iisalo,Memphis Hustle
27,1610612764,2025-26,Washington,Wizards,WAS,East,Southeast,wizards,wizards,17,...,WAS,Wizards,1961,Washington,Capital One Arena,20647.0,Ted Leonsis,Will Dawkins,Brian Keefe,Capital City Go-Go
28,1610612765,2025-26,Detroit,Pistons,DET,East,Central,pistons,pistons,60,...,DET,Pistons,1948,Detroit,Little Caesars Arena,NaN,Tom Gores,Trajan Langdon,J. B. Bickerstaff,Motor City Cruise
29,1610612766,2025-26,Charlotte,Hornets,CHA,East,Southeast,hornets,hornets,44,...,CHA,Hornets,1988,Charlotte,Spectrum Center,19026.0,Rick Schnall & Gabe Plotkin,Jeff Peterson,Charles Lee,Greensboro Swarm

In [1]:
from pyspark.sql.types import *
from pyspark.sql.functions import col, concat, lit,when
from constants import *
from utils import *

In [2]:
spark = create_spark_session("Load_Arena_Tea")

In [30]:
db_team_df = spark.read.jdbc(url=URL,table="team",properties=PROPERTIES)
db_team_df.show()

+-------+--------------+-------------+---------+--------------------+-----------------+----------+---------+---------+------------+--------------------+---------------+-----------------+--------------------+--------+
|team_id|team_source_id|    team_city|team_name|      full_team_name|team_abbreviation|conference| division| nickname|year_founded|               owner|general_manager|       head_coach|d_league_affiliation|logo_url|
+-------+--------------+-------------+---------+--------------------+-----------------+----------+---------+---------+------------+--------------------+---------------+-----------------+--------------------+--------+
|      1|    1610612763|      Memphis|Grizzlies|   Memphis Grizzlies|              MEM|      West|Southwest|Grizzlies|        1995|         Robert Pera|   Zach Kleiman|    Tuomas Iisalo|      Memphis Hustle|    NULL|
|      2|    1610612743|       Denver|  Nuggets|      Denver Nuggets|              DEN|      West|Northwest|  Nuggets|        1976|        Stan Kroenke|               |    David Adelman|   Grand Rapids Gold|    NULL|
|      3|    1610612738|       Boston|  Celtics|      Boston Celtics|              BOS|      East| Atlantic|  Celtics|        1946|       Bill Chisholm|   Brad Stevens|     Joe Mazzulla|       Maine Celtics|    NULL|
|      4|    1610612740|  New Orleans| Pelicans|New Orleans Pelicans|              NOP|      West|Southwest| Pelicans|        2002|        Gayle Benson|    Troy Weaver|    Jamahl Mosley| Birmingham Squadron|    NULL|
|      5|    1610612758|   Sacramento|    Kings|    Sacramento Kings|              SAC|      West|  Pacific|    Kings|        1948|      Vivek Ranadive|   Monte McNair|    Doug Christie|      Stockton Kings|    NULL|
|      6|    1610612751|     Brooklyn|     Nets|       Brooklyn Nets|              BKN|      East| Atlantic|     Nets|        1976|            Joe Tsai|     Sean Marks|  Jordi Fernandez|    Long Island Nets|    NULL|
|      7|    1610612745|      Houston|  Rockets|     Houston Rockets|              HOU|      West|Southwest|  Rockets|        1967|     Tilman Fertitta|   Rafael Stone|        Ime Udoka|Rio Grande Valley...|    NULL|
|      8|    1610612759|  San Antonio|    Spurs|   San Antonio Spurs|              SAS|      West|Southwest|    Spurs|        1976|          Peter Holt|   Brian Wright|    Mitch Johnson|        Austin Spurs|    NULL|
|      9|    1610612741|      Chicago|    Bulls|       Chicago Bulls|              CHI|      East|  Central|    Bulls|        1966|   Michael Reinsdorf|               |                 |    Windy City Bulls|    NULL|
|     10|    1610612749|    Milwaukee|    Bucks|     Milwaukee Bucks|              MIL|      East|  Central|    Bucks|        1968|        Wesley Edens|      Jon Horst|   Taylor Jenkins|      Wisconsin Herd|    NULL|
|     11|    1610612748|        Miami|     Heat|          Miami Heat|              MIA|      East|Southeast|     Heat|        1988|        Micky Arison|      Pat Riley|   Erik Spoelstra|Sioux Falls Skyforce|    NULL|
|     12|    1610612739|    Cleveland|Cavaliers| Cleveland Cavaliers|              CLE|      East|  Central|Cavaliers|        1970|         Dan Gilbert|    Koby Altman|   Kenny Atkinson|    Cleveland Charge|    NULL|
|     13|    1610612754|      Indiana|   Pacers|      Indiana Pacers|              IND|      East|  Central|   Pacers|        1976|          Herb Simon|Kevin Pritchard|    Rick Carlisle|    Noblesville Boom|    NULL|
|     14|    1610612746|           LA| Clippers|         LA Clippers|              LAC|      West|  Pacific| Clippers|        1970|       Steve Ballmer| Michael Winger|       Tyronn Lue|Agua Caliente Cli...|    NULL|
|     15|    1610612755| Philadelphia|    76ers|  Philadelphia 76ers|              PHI|      East| Atlantic|    76ers|        1949|Joshua Harris & D...|    Elton Brand|       Nick Nurse| Delaware Blue Coats|    NULL|
|     16|    1610612760|Oklahoma City|  Thunder|Oklahoma City Thu...|              OKC|      West|Northwest|  Thunder|        1967|        Clay Bennett|     Sam Presti|  Mark Daigneault|  Oklahoma City Blue|    NULL|
|     17|    1610612756|      Phoenix|     Suns|        Phoenix Suns|              PHX|      West|  Pacific|     Suns|        1968|          Mat Ishbia|  Brian Gregory|       Jordan Ott|         Valley Suns|    NULL|
|     18|    1610612742|       Dallas|Mavericks|    Dallas Mavericks|              DAL|      West|Southwest|Mavericks|        1980|      Patrick Dumont|               |                 |       Texas Legends|    NULL|
|     19|    1610612753|      Orlando|    Magic|       Orlando Magic|              ORL|      East|Southeast|    Magic|        1989|           Dan DeVos|   John Hammond|                 |       Osceola Magic|    NULL|
|     20|    1610612765|      Detroit|  Pistons|     Detroit Pistons|              DET|      East|  Central|  Pistons|        1948|           Tom Gores| Trajan Langdon|J. B. Bickerstaff|   Motor City Cruise|    NULL|
+-------+--------------+-------------+---------+--------------------+-----------------+----------+---------+---------+------------+--------------------+---------------+-----------------+--------------------+--------+
only showing top 20 rows

In [31]:
db_arena_df = spark.read.jdbc(url=URL,table="arena", properties=PROPERTIES)
db_arena_df.show()

+--------+--------------+-------------+---------------+--------------------+-----------+--------------+--------------+
|arena_id|    arena_city|arena_country|arena_source_id|          arena_name|arena_state|arena_timezone|team_source_id|
+--------+--------------+-------------+---------------+--------------------+-----------+--------------+--------------+
|       1|   San Antonio|           US|              1|           Alamodome|         TX|       Central|    1610612759|
|       2|       Phoenix|           US|              2|   US Airways Center|         AZ|      Mountain|    1610612756|
|       3|    Sacramento|           US|              3|   Sleep Train Arena|         CA|       Pacific|    1610612758|
|       4|     Milwaukee|           US|              5|BMO Harris Bradle...|         WI|       Central|    1610612749|
|       5|     Charlotte|           US|              9|     Spectrum Center|         NC|       Eastern|    1610612766|
|       6|    New Jersey|           US|             11|         IZOD Center|         NJ|       Eastern|    1610612751|
|       7|  Philadelphia|           US|             12|Core States Spect...|         PA|       Eastern|    1610612755|
|       8|Salt Lake City|           US|             15|EnergySolutions A...|         UT|      Mountain|    1610612762|
|       9|        Boston|           US|             17|           TD Garden|         MA|       Eastern|    1610612738|
|      10|     Vancouver|           US|             19|            GM Place|         BC|       Pacific|    1610612763|
|      11|   Los Angeles|           US|             20| Great Western Forum|         LA|       Pacific|    1610612747|
|      12|     Cleveland|           US|             22| Quicken Loans Arena|         OH|       Eastern|    1610612739|
|      13|      New York|           US|             30|Madison Square Ga...|         NY|       Eastern|    1610612752|
|      14|  Indianapolis|           US|             33| Market Square Arena|         IN|       Eastern|    1610612754|
|      15|        Denver|           US|             36|McNichols Sports ...|         CO|      Mountain|    1610612743|
|      16|         Miami|           US|             38|         Miami Arena|         FL|       Eastern|    1610612748|
|      17|       Atlanta|           US|             41|                Omni|         GA|       Eastern|    1610612737|
|      18|       Orlando|           US|             43|         Amway Arena|         FL|       Eastern|    1610612753|
|      19|       Detroit|           US|             44|Palace of Auburn ...|         MI|       Eastern|    1610612765|
|      20|       Memphis|           US|             48|             Pyramid|         TN|       Central|    1610612763|
+--------+--------------+-------------+---------------+--------------------+-----------+--------------+--------------+
only showing top 20 rows

In [32]:
joined = db_team_df.join(other=db_arena_df,on = "team_source_id",how="inner")
joined.show()

+--------------+-------+------------+---------+--------------------+-----------------+----------+---------+---------+------------+-----------------+-----------------+--------------+--------------------+--------+--------+-------------+-------------+---------------+--------------------+-----------+--------------+
|team_source_id|team_id|   team_city|team_name|      full_team_name|team_abbreviation|conference| division| nickname|year_founded|            owner|  general_manager|    head_coach|d_league_affiliation|logo_url|arena_id|   arena_city|arena_country|arena_source_id|          arena_name|arena_state|arena_timezone|
+--------------+-------+------------+---------+--------------------+-----------------+----------+---------+---------+------------+-----------------+-----------------+--------------+--------------------+--------+--------+-------------+-------------+---------------+--------------------+-----------+--------------+
|    1610612737|     25|     Atlanta|    Hawks|       Atlanta Hawks|              ATL|      East|Southeast|    Hawks|        1949|     Tony Ressler|   Travis Schlenk|   Quin Snyder|College Park Skyh...|    NULL|      17|      Atlanta|           US|             41|                Omni|         GA|       Eastern|
|    1610612737|     25|     Atlanta|    Hawks|       Atlanta Hawks|              ATL|      East|Southeast|    Hawks|        1949|     Tony Ressler|   Travis Schlenk|   Quin Snyder|College Park Skyh...|    NULL|      33|      Atlanta|           US|             76|  Alexander Coliseum|         GA|       Eastern|
|    1610612737|     25|     Atlanta|    Hawks|       Atlanta Hawks|              ATL|      East|Southeast|    Hawks|        1949|     Tony Ressler|   Travis Schlenk|   Quin Snyder|College Park Skyh...|    NULL|      35|      Atlanta|           US|             78|        Georgia Dome|         GA|       Eastern|
|    1610612737|     25|     Atlanta|    Hawks|       Atlanta Hawks|              ATL|      East|Southeast|    Hawks|        1949|     Tony Ressler|   Travis Schlenk|   Quin Snyder|College Park Skyh...|    NULL|      42|      Atlanta|           US|            135|       Philips Arena|         GA|       Eastern|
|    1610612737|     25|     Atlanta|    Hawks|       Atlanta Hawks|              ATL|      East|Southeast|    Hawks|        1949|     Tony Ressler|   Travis Schlenk|   Quin Snyder|College Park Skyh...|    NULL|      65|      Atlanta|           US|            650|    State Farm Arena|         GA|       Eastern|
|    1610612738|      3|      Boston|  Celtics|      Boston Celtics|              BOS|      East| Atlantic|  Celtics|        1946|    Bill Chisholm|     Brad Stevens|  Joe Mazzulla|       Maine Celtics|    NULL|       9|       Boston|           US|             17|           TD Garden|         MA|       Eastern|
|    1610612738|      3|      Boston|  Celtics|      Boston Celtics|              BOS|      East| Atlantic|  Celtics|        1946|    Bill Chisholm|     Brad Stevens|  Joe Mazzulla|       Maine Celtics|    NULL|      37|       Boston|           US|            111|       Boston Garden|         MA|       Eastern|
|    1610612739|     12|   Cleveland|Cavaliers| Cleveland Cavaliers|              CLE|      East|  Central|Cavaliers|        1970|      Dan Gilbert|      Koby Altman|Kenny Atkinson|    Cleveland Charge|    NULL|      12|    Cleveland|           US|             22| Quicken Loans Arena|         OH|       Eastern|
|    1610612739|     12|   Cleveland|Cavaliers| Cleveland Cavaliers|              CLE|      East|  Central|Cavaliers|        1970|      Dan Gilbert|      Koby Altman|Kenny Atkinson|    Cleveland Charge|    NULL|      66|    Cleveland|           US|        1000006|Rocket Mortgage F...|         OH|       Eastern|
|    1610612739|     12|   Cleveland|Cavaliers| Cleveland Cavaliers|              CLE|      East|  Central|Cavaliers|        1970|      Dan Gilbert|      Koby Altman|Kenny Atkinson|    Cleveland Charge|    NULL|      82|    Cleveland|           US|        1000144|        Rocket Arena|         OH|       Eastern|
|    1610612740|      4| New Orleans| Pelicans|New Orleans Pelicans|              NOP|      West|Southwest| Pelicans|        2002|     Gayle Benson|      Troy Weaver| Jamahl Mosley| Birmingham Squadron|    NULL|      48|  New Orleans|           US|            160|Smoothie King Center|         LA|       Central|
|    1610612740|      4| New Orleans| Pelicans|New Orleans Pelicans|              NOP|      West|Southwest| Pelicans|        2002|     Gayle Benson|      Troy Weaver| Jamahl Mosley| Birmingham Squadron|    NULL|      50|Oklahoma City|           US|            196|Chesapeake Energy...|         OK|       Central|
|    1610612741|      9|     Chicago|    Bulls|       Chicago Bulls|              CHI|      East|  Central|    Bulls|        1966|Michael Reinsdorf|                 |              |    Windy City Bulls|    NULL|      28|      Chicago|           US|             66|       United Center|         IL|       Central|
|    1610612742|     18|      Dallas|Mavericks|    Dallas Mavericks|              DAL|      West|Southwest|Mavericks|        1980|   Patrick Dumont|                 |              |       Texas Legends|    NULL|      21|       Dallas|           US|             49|       Reunion Arena|         TX|       Central|
|    1610612742|     18|      Dallas|Mavericks|    Dallas Mavericks|              DAL|      West|Southwest|Mavericks|        1980|   Patrick Dumont|                 |              |       Texas Legends|    NULL|      49|       Dallas|           US|            193|American Airlines...|         TX|       Central|
|    1610612743|      2|      Denver|  Nuggets|      Denver Nuggets|              DEN|      West|Northwest|  Nuggets|        1976|     Stan Kroenke|                 | David Adelman|   Grand Rapids Gold|    NULL|      15|       Denver|           US|             36|McNichols Sports ...|         CO|      Mountain|
|    1610612743|      2|      Denver|  Nuggets|      Denver Nuggets|              DEN|      West|Northwest|  Nuggets|        1976|     Stan Kroenke|                 | David Adelman|   Grand Rapids Gold|    NULL|      45|       Denver|           US|            139|        Pepsi Center|         CO|      Mountain|
|    1610612743|      2|      Denver|  Nuggets|      Denver Nuggets|              DEN|      West|Northwest|  Nuggets|        1976|     Stan Kroenke|                 | David Adelman|   Grand Rapids Gold|    NULL|      69|       Denver|           US|        1000046|          Ball Arena|         CO|      Mountain|
|    1610612744|     30|Golden State| Warriors|Golden State Warr...|              GSW|      West|  Pacific| Warriors|        1946|        Joe Lacob|Mike Dunleavy Jr.|    Steve Kerr| Santa Cruz Warriors|    NULL|      23|     San Jose|           US|             53|      San Jose Arena|         CA|       Pacific|
|    1610612744|     30|Golden State| Warriors|Golden State Warr...|              GSW|      West|  Pacific| Warriors|        1946|        Joe Lacob|Mike Dunleavy Jr.|    Steve Kerr| Santa Cruz Warriors|    NULL|      29|      Oakland|           US|             71|        ORACLE Arena|         CA|       Pacific|
+--------------+-------+------------+---------+--------------------+-----------------+----------+---------+---------+------------+-----------------+-----------------+--------------+--------------------+--------+--------+-------------+-------------+---------------+--------------------+-----------+--------------+
only showing top 20 rows

In [33]:
arena_info_df = spark.read.format("json").option("multiline",True).load("raw_data/team_info/all_teams_info.json")
arena_info_df.show()

+------------+--------------------+-------------+------------+---------+--------+--------------------+-----------------+---------------+---+--------+--------+------------+--------------------+-----+-----------+-----------------+------------+------------+---------------+-------------+----------+------------+------------+---+-----------+
|ABBREVIATION|               ARENA|ARENACAPACITY|        CITY|CONF_RANK|DIV_RANK|  DLEAGUEAFFILIATION|   GENERALMANAGER|      HEADCOACH|  L|MAX_YEAR|MIN_YEAR|    NICKNAME|               OWNER|  PCT|SEASON_YEAR|TEAM_ABBREVIATION|   TEAM_CITY|   TEAM_CODE|TEAM_CONFERENCE|TEAM_DIVISION|   TEAM_ID|   TEAM_NAME|   TEAM_SLUG|  W|YEARFOUNDED|
+------------+--------------------+-------------+------------+---------+--------+--------------------+-----------------+---------------+---+--------+--------+------------+--------------------+-----+-----------+-----------------+------------+------------+---------------+-------------+----------+------------+------------+---+-----------+
|         ATL|    State Farm Arena|        18729|     Atlanta|        6|       1|College Park Skyh...|   Travis Schlenk|    Quin Snyder| 36|    2026|    1949|       Hawks|        Tony Ressler|0.561|    2025-26|              ATL|     Atlanta|       hawks|           East|    Southeast|1610612737|       Hawks|       hawks| 46|       1949|
|         BOS|           TD Garden|        18624|      Boston|        2|       1|       Maine Celtics|     Brad Stevens|   Joe Mazzulla| 26|    2026|    1946|     Celtics|       Bill Chisholm|0.683|    2025-26|              BOS|      Boston|     celtics|           East|     Atlantic|1610612738|     Celtics|     celtics| 56|       1946|
|         CLE|        Rocket Arena|        20562|   Cleveland|        4|       2|    Cleveland Charge|      Koby Altman| Kenny Atkinson| 30|    2026|    1970|   Cavaliers|         Dan Gilbert|0.634|    2025-26|              CLE|   Cleveland|   cavaliers|           East|      Central|1610612739|   Cavaliers|   cavaliers| 52|       1970|
|         NOP|Smoothie King Center|         NULL| New Orleans|       11|       3| Birmingham Squadron|      Troy Weaver|  Jamahl Mosley| 56|    2026|    2002|    Pelicans|        Gayle Benson|0.317|    2025-26|              NOP| New Orleans|    pelicans|           West|    Southwest|1610612740|    Pelicans|    pelicans| 26|       2002|
|         CHI|       United Center|        21711|     Chicago|       12|       4|    Windy City Bulls|                 |               | 51|    2026|    1966|       Bulls|   Michael Reinsdorf|0.378|    2025-26|              CHI|     Chicago|       bulls|           East|      Central|1610612741|       Bulls|       bulls| 31|       1966|
|         DAL|American Airlines...|        19200|      Dallas|       12|       4|       Texas Legends|                 |               | 56|    2026|    1980|   Mavericks|      Patrick Dumont|0.317|    2025-26|              DAL|      Dallas|   mavericks|           West|    Southwest|1610612742|   Mavericks|   mavericks| 26|       1980|
|         DEN|          Ball Arena|         NULL|      Denver|        3|       2|   Grand Rapids Gold|                 |  David Adelman| 28|    2026|    1976|     Nuggets|        Stan Kroenke|0.659|    2025-26|              DEN|      Denver|     nuggets|           West|    Northwest|1610612743|     Nuggets|     nuggets| 54|       1976|
|         GSW|        Chase Center|         NULL|Golden State|       10|       4| Santa Cruz Warriors|Mike Dunleavy Jr.|     Steve Kerr| 45|    2026|    1946|    Warriors|           Joe Lacob|0.451|    2025-26|              GSW|Golden State|    warriors|           West|      Pacific|1610612744|    Warriors|    warriors| 37|       1946|
|         HOU|       Toyota Center|        18104|     Houston|        5|       2|Rio Grande Valley...|     Rafael Stone|      Ime Udoka| 30|    2026|    1967|     Rockets|     Tilman Fertitta|0.634|    2025-26|              HOU|     Houston|     rockets|           West|    Southwest|1610612745|     Rockets|     rockets| 52|       1967|
|         LAC|         Intuit Dome|        19060| Los Angeles|        9|       3|Agua Caliente Cli...|   Michael Winger|     Tyronn Lue| 40|    2026|    1970|    Clippers|       Steve Ballmer|0.512|    2025-26|              LAC|          LA|    clippers|           West|      Pacific|1610612746|    Clippers|    clippers| 42|       1970|
|         LAL|    Crypto.com Arena|        19060| Los Angeles|        4|       1|    South Bay Lakers|      Rob Pelinka|      JJ Redick| 29|    2026|    1948|      Lakers|Mark Walter & Jea...|0.646|    2025-26|              LAL| Los Angeles|      lakers|           West|      Pacific|1610612747|      Lakers|      lakers| 53|       1948|
|         MIA|       Kaseya Center|        19600|       Miami|       10|       4|Sioux Falls Skyforce|        Pat Riley| Erik Spoelstra| 39|    2026|    1988|        Heat|        Micky Arison|0.524|    2025-26|              MIA|       Miami|        heat|           East|    Southeast|1610612748|        Heat|        heat| 43|       1988|
|         MIL|        Fiserv Forum|        17500|   Milwaukee|       11|       3|      Wisconsin Herd|        Jon Horst| Taylor Jenkins| 50|    2026|    1968|       Bucks|        Wesley Edens| 0.39|    2025-26|              MIL|   Milwaukee|       bucks|           East|      Central|1610612749|       Bucks|       bucks| 32|       1968|
|         MIN|       Target Center|        19356|   Minnesota|        6|       3|         Iowa Wolves|     Tim Connelly|    Chris Finch| 33|    2026|    1989|Timberwolves|Marc Lore & Alex ...|0.598|    2025-26|              MIN|   Minnesota|timberwolves|           West|    Northwest|1610612750|Timberwolves|timberwolves| 49|       1989|
|         BKN|     Barclays Center|         NULL|    Brooklyn|       13|       5|    Long Island Nets|       Sean Marks|Jordi Fernandez| 62|    2026|    1976|        Nets|            Joe Tsai|0.244|    2025-26|              BKN|    Brooklyn|        nets|           East|     Atlantic|1610612751|        Nets|        nets| 20|       1976|
|         NYK|Madison Square Ga...|        19763|    New York|        3|       2|  Westchester Knicks|        Leon Rose|     Mike Brown| 29|    2026|    1946|      Knicks|           Jim Dolan|0.646|    2025-26|              NYK|    New York|      knicks|           East|     Atlantic|1610612752|      Knicks|      knicks| 53|       1946|
|         ORL|          Kia Center|            0|     Orlando|        8|       2|       Osceola Magic|     John Hammond|               | 37|    2026|    1989|       Magic|           Dan DeVos|0.549|    2025-26|              ORL|     Orlando|       magic|           East|    Southeast|1610612753|       Magic|       magic| 45|       1989|
|         IND|Gainbridge Fieldh...|        18345|     Indiana|       14|       5|    Noblesville Boom|  Kevin Pritchard|  Rick Carlisle| 63|    2026|    1976|      Pacers|          Herb Simon|0.232|    2025-26|              IND|     Indiana|      pacers|           East|      Central|1610612754|      Pacers|      pacers| 19|       1976|
|         PHI|Xfinity Mobile Arena|         NULL|Philadelphia|        7|       4| Delaware Blue Coats|      Elton Brand|     Nick Nurse| 37|    2026|    1949|       76ers|Joshua Harris & D...|0.549|    2025-26|              PHI|Philadelphia|      sixers|           East|     Atlantic|1610612755|       76ers|      sixers| 45|       1949|
|         PHX|Mortgage Matchup ...|         NULL|     Phoenix|        7|       2|         Valley Suns|    Brian Gregory|     Jordan Ott| 37|    2026|    1968|        Suns|          Mat Ishbia|0.549|    2025-26|              PHX|     Phoenix|        suns|           West|      Pacific|1610612756|        Suns|        suns| 45|       1968|
+------------+--------------------+-------------+------------+---------+--------+--------------------+-----------------+---------------+---+--------+--------+------------+--------------------+-----+-----------+-----------------+------------+------------+---------------+-------------+----------+------------+------------+---+-----------+
only showing top 20 rows

In [34]:
res = joined.join(other=arena_info_df,on=(joined["team_source_id"] == arena_info_df["TEAM_ID"]) & (joined["arena_name"] == arena_info_df["ARENA"]),how="left" )

res = res.drop(arena_info_df["TEAM_ID"])
res.show()

+--------------+-------+------------+---------+--------------------+-----------------+----------+---------+---------+------------+-----------------+-----------------+--------------+--------------------+--------+--------+-------------+-------------+---------------+--------------------+-----------+--------------+------------+--------------------+-------------+-----------+---------+--------+--------------------+--------------+--------------+----+--------+--------+---------+-----------------+-----+-----------+-----------------+-----------+---------+---------------+-------------+---------+---------+----+-----------+
|team_source_id|team_id|   team_city|team_name|      full_team_name|team_abbreviation|conference| division| nickname|year_founded|            owner|  general_manager|    head_coach|d_league_affiliation|logo_url|arena_id|   arena_city|arena_country|arena_source_id|          arena_name|arena_state|arena_timezone|ABBREVIATION|               ARENA|ARENACAPACITY|       CITY|CONF_RANK|DIV_RANK|  DLEAGUEAFFILIATION|GENERALMANAGER|     HEADCOACH|   L|MAX_YEAR|MIN_YEAR| NICKNAME|            OWNER|  PCT|SEASON_YEAR|TEAM_ABBREVIATION|  TEAM_CITY|TEAM_CODE|TEAM_CONFERENCE|TEAM_DIVISION|TEAM_NAME|TEAM_SLUG|   W|YEARFOUNDED|
+--------------+-------+------------+---------+--------------------+-----------------+----------+---------+---------+------------+-----------------+-----------------+--------------+--------------------+--------+--------+-------------+-------------+---------------+--------------------+-----------+--------------+------------+--------------------+-------------+-----------+---------+--------+--------------------+--------------+--------------+----+--------+--------+---------+-----------------+-----+-----------+-----------------+-----------+---------+---------------+-------------+---------+---------+----+-----------+
|    1610612737|     25|     Atlanta|    Hawks|       Atlanta Hawks|              ATL|      East|Southeast|    Hawks|        1949|     Tony Ressler|   Travis Schlenk|   Quin Snyder|College Park Skyh...|    NULL|      17|      Atlanta|           US|             41|                Omni|         GA|       Eastern|        NULL|                NULL|         NULL|       NULL|     NULL|    NULL|                NULL|          NULL|          NULL|NULL|    NULL|    NULL|     NULL|             NULL| NULL|       NULL|             NULL|       NULL|     NULL|           NULL|         NULL|     NULL|     NULL|NULL|       NULL|
|    1610612737|     25|     Atlanta|    Hawks|       Atlanta Hawks|              ATL|      East|Southeast|    Hawks|        1949|     Tony Ressler|   Travis Schlenk|   Quin Snyder|College Park Skyh...|    NULL|      33|      Atlanta|           US|             76|  Alexander Coliseum|         GA|       Eastern|        NULL|                NULL|         NULL|       NULL|     NULL|    NULL|                NULL|          NULL|          NULL|NULL|    NULL|    NULL|     NULL|             NULL| NULL|       NULL|             NULL|       NULL|     NULL|           NULL|         NULL|     NULL|     NULL|NULL|       NULL|
|    1610612737|     25|     Atlanta|    Hawks|       Atlanta Hawks|              ATL|      East|Southeast|    Hawks|        1949|     Tony Ressler|   Travis Schlenk|   Quin Snyder|College Park Skyh...|    NULL|      35|      Atlanta|           US|             78|        Georgia Dome|         GA|       Eastern|        NULL|                NULL|         NULL|       NULL|     NULL|    NULL|                NULL|          NULL|          NULL|NULL|    NULL|    NULL|     NULL|             NULL| NULL|       NULL|             NULL|       NULL|     NULL|           NULL|         NULL|     NULL|     NULL|NULL|       NULL|
|    1610612737|     25|     Atlanta|    Hawks|       Atlanta Hawks|              ATL|      East|Southeast|    Hawks|        1949|     Tony Ressler|   Travis Schlenk|   Quin Snyder|College Park Skyh...|    NULL|      42|      Atlanta|           US|            135|       Philips Arena|         GA|       Eastern|        NULL|                NULL|         NULL|       NULL|     NULL|    NULL|                NULL|          NULL|          NULL|NULL|    NULL|    NULL|     NULL|             NULL| NULL|       NULL|             NULL|       NULL|     NULL|           NULL|         NULL|     NULL|     NULL|NULL|       NULL|
|    1610612737|     25|     Atlanta|    Hawks|       Atlanta Hawks|              ATL|      East|Southeast|    Hawks|        1949|     Tony Ressler|   Travis Schlenk|   Quin Snyder|College Park Skyh...|    NULL|      65|      Atlanta|           US|            650|    State Farm Arena|         GA|       Eastern|         ATL|    State Farm Arena|        18729|    Atlanta|        6|       1|College Park Skyh...|Travis Schlenk|   Quin Snyder|  36|    2026|    1949|    Hawks|     Tony Ressler|0.561|    2025-26|              ATL|    Atlanta|    hawks|           East|    Southeast|    Hawks|    hawks|  46|       1949|
|    1610612738|      3|      Boston|  Celtics|      Boston Celtics|              BOS|      East| Atlantic|  Celtics|        1946|    Bill Chisholm|     Brad Stevens|  Joe Mazzulla|       Maine Celtics|    NULL|       9|       Boston|           US|             17|           TD Garden|         MA|       Eastern|         BOS|           TD Garden|        18624|     Boston|        2|       1|       Maine Celtics|  Brad Stevens|  Joe Mazzulla|  26|    2026|    1946|  Celtics|    Bill Chisholm|0.683|    2025-26|              BOS|     Boston|  celtics|           East|     Atlantic|  Celtics|  celtics|  56|       1946|
|    1610612738|      3|      Boston|  Celtics|      Boston Celtics|              BOS|      East| Atlantic|  Celtics|        1946|    Bill Chisholm|     Brad Stevens|  Joe Mazzulla|       Maine Celtics|    NULL|      37|       Boston|           US|            111|       Boston Garden|         MA|       Eastern|        NULL|                NULL|         NULL|       NULL|     NULL|    NULL|                NULL|          NULL|          NULL|NULL|    NULL|    NULL|     NULL|             NULL| NULL|       NULL|             NULL|       NULL|     NULL|           NULL|         NULL|     NULL|     NULL|NULL|       NULL|
|    1610612739|     12|   Cleveland|Cavaliers| Cleveland Cavaliers|              CLE|      East|  Central|Cavaliers|        1970|      Dan Gilbert|      Koby Altman|Kenny Atkinson|    Cleveland Charge|    NULL|      12|    Cleveland|           US|             22| Quicken Loans Arena|         OH|       Eastern|        NULL|                NULL|         NULL|       NULL|     NULL|    NULL|                NULL|          NULL|          NULL|NULL|    NULL|    NULL|     NULL|             NULL| NULL|       NULL|             NULL|       NULL|     NULL|           NULL|         NULL|     NULL|     NULL|NULL|       NULL|
|    1610612739|     12|   Cleveland|Cavaliers| Cleveland Cavaliers|              CLE|      East|  Central|Cavaliers|        1970|      Dan Gilbert|      Koby Altman|Kenny Atkinson|    Cleveland Charge|    NULL|      66|    Cleveland|           US|        1000006|Rocket Mortgage F...|         OH|       Eastern|        NULL|                NULL|         NULL|       NULL|     NULL|    NULL|                NULL|          NULL|          NULL|NULL|    NULL|    NULL|     NULL|             NULL| NULL|       NULL|             NULL|       NULL|     NULL|           NULL|         NULL|     NULL|     NULL|NULL|       NULL|
|    1610612739|     12|   Cleveland|Cavaliers| Cleveland Cavaliers|              CLE|      East|  Central|Cavaliers|        1970|      Dan Gilbert|      Koby Altman|Kenny Atkinson|    Cleveland Charge|    NULL|      82|    Cleveland|           US|        1000144|        Rocket Arena|         OH|       Eastern|         CLE|        Rocket Arena|        20562|  Cleveland|        4|       2|    Cleveland Charge|   Koby Altman|Kenny Atkinson|  30|    2026|    1970|Cavaliers|      Dan Gilbert|0.634|    2025-26|              CLE|  Cleveland|cavaliers|           East|      Central|Cavaliers|cavaliers|  52|       1970|
|    1610612740|      4| New Orleans| Pelicans|New Orleans Pelicans|              NOP|      West|Southwest| Pelicans|        2002|     Gayle Benson|      Troy Weaver| Jamahl Mosley| Birmingham Squadron|    NULL|      48|  New Orleans|           US|            160|Smoothie King Center|         LA|       Central|         NOP|Smoothie King Center|         NULL|New Orleans|       11|       3| Birmingham Squadron|   Troy Weaver| Jamahl Mosley|  56|    2026|    2002| Pelicans|     Gayle Benson|0.317|    2025-26|              NOP|New Orleans| pelicans|           West|    Southwest| Pelicans| pelicans|  26|       2002|
|    1610612740|      4| New Orleans| Pelicans|New Orleans Pelicans|              NOP|      West|Southwest| Pelicans|        2002|     Gayle Benson|      Troy Weaver| Jamahl Mosley| Birmingham Squadron|    NULL|      50|Oklahoma City|           US|            196|Chesapeake Energy...|         OK|       Central|        NULL|                NULL|         NULL|       NULL|     NULL|    NULL|                NULL|          NULL|          NULL|NULL|    NULL|    NULL|     NULL|             NULL| NULL|       NULL|             NULL|       NULL|     NULL|           NULL|         NULL|     NULL|     NULL|NULL|       NULL|
|    1610612741|      9|     Chicago|    Bulls|       Chicago Bulls|              CHI|      East|  Central|    Bulls|        1966|Michael Reinsdorf|                 |              |    Windy City Bulls|    NULL|      28|      Chicago|           US|             66|       United Center|         IL|       Central|         CHI|       United Center|        21711|    Chicago|       12|       4|    Windy City Bulls|              |              |  51|    2026|    1966|    Bulls|Michael Reinsdorf|0.378|    2025-26|              CHI|    Chicago|    bulls|           East|      Central|    Bulls|    bulls|  31|       1966|
|    1610612742|     18|      Dallas|Mavericks|    Dallas Mavericks|              DAL|      West|Southwest|Mavericks|        1980|   Patrick Dumont|                 |              |       Texas Legends|    NULL|      21|       Dallas|           US|             49|       Reunion Arena|         TX|       Central|        NULL|                NULL|         NULL|       NULL|     NULL|    NULL|                NULL|          NULL|          NULL|NULL|    NULL|    NULL|     NULL|             NULL| NULL|       NULL|             NULL|       NULL|     NULL|           NULL|         NULL|     NULL|     NULL|NULL|       NULL|
|    1610612742|     18|      Dallas|Mavericks|    Dallas Mavericks|              DAL|      West|Southwest|Mavericks|        1980|   Patrick Dumont|                 |              |       Texas Legends|    NULL|      49|       Dallas|           US|            193|American Airlines...|         TX|       Central|         DAL|American Airlines...|        19200|     Dallas|       12|       4|       Texas Legends|              |              |  56|    2026|    1980|Mavericks|   Patrick Dumont|0.317|    2025-26|              DAL|     Dallas|mavericks|           West|    Southwest|Mavericks|mavericks|  26|       1980|
|    1610612743|      2|      Denver|  Nuggets|      Denver Nuggets|              DEN|      West|Northwest|  Nuggets|        1976|     Stan Kroenke|                 | David Adelman|   Grand Rapids Gold|    NULL|      15|       Denver|           US|             36|McNichols Sports ...|         CO|      Mountain|        NULL|                NULL|         NULL|       NULL|     NULL|    NULL|                NULL|          NULL|          NULL|NULL|    NULL|    NULL|     NULL|             NULL| NULL|       NULL|             NULL|       NULL|     NULL|           NULL|         NULL|     NULL|     NULL|NULL|       NULL|
|    1610612743|      2|      Denver|  Nuggets|      Denver Nuggets|              DEN|      West|Northwest|  Nuggets|        1976|     Stan Kroenke|                 | David Adelman|   Grand Rapids Gold|    NULL|      45|       Denver|           US|            139|        Pepsi Center|         CO|      Mountain|        NULL|                NULL|         NULL|       NULL|     NULL|    NULL|                NULL|          NULL|          NULL|NULL|    NULL|    NULL|     NULL|             NULL| NULL|       NULL|             NULL|       NULL|     NULL|           NULL|         NULL|     NULL|     NULL|NULL|       NULL|
|    1610612743|      2|      Denver|  Nuggets|      Denver Nuggets|              DEN|      West|Northwest|  Nuggets|        1976|     Stan Kroenke|                 | David Adelman|   Grand Rapids Gold|    NULL|      69|       Denver|           US|        1000046|          Ball Arena|         CO|      Mountain|         DEN|          Ball Arena|         NULL|     Denver|        3|       2|   Grand Rapids Gold|              | David Adelman|  28|    2026|    1976|  Nuggets|     Stan Kroenke|0.659|    2025-26|              DEN|     Denver|  nuggets|           West|    Northwest|  Nuggets|  nuggets|  54|       1976|
|    1610612744|     30|Golden State| Warriors|Golden State Warr...|              GSW|      West|  Pacific| Warriors|        1946|        Joe Lacob|Mike Dunleavy Jr.|    Steve Kerr| Santa Cruz Warriors|    NULL|      23|     San Jose|           US|             53|      San Jose Arena|         CA|       Pacific|        NULL|                NULL|         NULL|       NULL|     NULL|    NULL|                NULL|          NULL|          NULL|NULL|    NULL|    NULL|     NULL|             NULL| NULL|       NULL|             NULL|       NULL|     NULL|           NULL|         NULL|     NULL|     NULL|NULL|       NULL|
|    1610612744|     30|Golden State| Warriors|Golden State Warr...|              GSW|      West|  Pacific| Warriors|        1946|        Joe Lacob|Mike Dunleavy Jr.|    Steve Kerr| Santa Cruz Warriors|    NULL|      29|      Oakland|           US|             71|        ORACLE Arena|         CA|       Pacific|        NULL|                NULL|         NULL|       NULL|     NULL|    NULL|                NULL|          NULL|          NULL|NULL|    NULL|    NULL|     NULL|             NULL| NULL|       NULL|             NULL|       NULL|     NULL|           NULL|         NULL|     NULL|     NULL|NULL|       NULL|
+--------------+-------+------------+---------+--------------------+-----------------+----------+---------+---------+------------+-----------------+-----------------+--------------+--------------------+--------+--------+-------------+-------------+---------------+--------------------+-----------+--------------+------------+--------------------+-------------+-----------+---------+--------+--------------------+--------------+--------------+----+--------+--------+---------+-----------------+-----+-----------+-----------------+-----------+---------+---------------+-------------+---------+---------+----+-----------+
only showing top 20 rows

In [36]:
final_df = res.select(
    col("team_id"),
    col("arena_id"),
    col("full_team_name"),
    col("arena_name"),
    when(col("TEAM_CODE").isNull(), False).otherwise(True).alias("is_current")
)

final_df.show(200)

+-------+--------+--------------------+--------------------+----------+
|team_id|arena_id|      full_team_name|          arena_name|is_current|
+-------+--------+--------------------+--------------------+----------+
|     25|      17|       Atlanta Hawks|                Omni|     false|
|     25|      33|       Atlanta Hawks|  Alexander Coliseum|     false|
|     25|      35|       Atlanta Hawks|        Georgia Dome|     false|
|     25|      42|       Atlanta Hawks|       Philips Arena|     false|
|     25|      65|       Atlanta Hawks|    State Farm Arena|      true|
|      3|       9|      Boston Celtics|           TD Garden|      true|
|      3|      37|      Boston Celtics|       Boston Garden|     false|
|     12|      12| Cleveland Cavaliers| Quicken Loans Arena|     false|
|     12|      66| Cleveland Cavaliers|Rocket Mortgage F...|     false|
|     12|      82| Cleveland Cavaliers|        Rocket Arena|      true|
|      4|      48|New Orleans Pelicans|Smoothie King Center|      true|
|      4|      50|New Orleans Pelicans|Chesapeake Energy...|     false|
|      9|      28|       Chicago Bulls|       United Center|      true|
|     18|      21|    Dallas Mavericks|       Reunion Arena|     false|
|     18|      49|    Dallas Mavericks|American Airlines...|      true|
|      2|      15|      Denver Nuggets|McNichols Sports ...|     false|
|      2|      45|      Denver Nuggets|        Pepsi Center|     false|
|      2|      69|      Denver Nuggets|          Ball Arena|      true|
|     30|      23|Golden State Warr...|      San Jose Arena|     false|
|     30|      29|Golden State Warr...|        ORACLE Arena|     false|
|     30|      67|Golden State Warr...|        Chase Center|      true|
|      7|      26|     Houston Rockets|       Compaq Center|     false|
|      7|      52|     Houston Rockets|       Toyota Center|      true|
|     14|      25|         LA Clippers|        Sports Arena|     false|
|     14|      36|         LA Clippers|L.A. Memorial Spo...|     false|
|     14|      44|         LA Clippers|      STAPLES Center|     false|
|     14|      53|         LA Clippers| Saitama Super Arena|     false|
|     14|      76|         LA Clippers|    Crypto.com Arena|     false|
|     14|      81|         LA Clippers|         Intuit Dome|      true|
|     24|      11|  Los Angeles Lakers| Great Western Forum|     false|
|     24|      86|  Los Angeles Lakers|      STAPLES Center|     false|
|     24|      89|  Los Angeles Lakers|    Crypto.com Arena|      true|
|     11|      16|          Miami Heat|         Miami Arena|     false|
|     11|      46|          Miami Heat|AmericanAirlines ...|     false|
|     11|      72|          Miami Heat|           FTX Arena|     false|
|     11|      77|          Miami Heat|       Kaseya Center|      true|
|     10|       4|     Milwaukee Bucks|BMO Harris Bradle...|     false|
|     10|      63|     Milwaukee Bucks|        Fiserv Forum|      true|
|     28|      27|Minnesota Timberw...|       Target Center|      true|
|     28|      38|Minnesota Timberw...|          Metro Dome|     false|
|     28|      41|Minnesota Timberw...|          Tokyo Dome|     false|
|      6|       6|       Brooklyn Nets|         IZOD Center|     false|
|      6|      55|       Brooklyn Nets|   Prudential Center|     false|
|      6|      58|       Brooklyn Nets|     Barclays Center|      true|
|     22|      13|     New York Knicks|Madison Square Ga...|      true|
|     19|      18|       Orlando Magic|         Amway Arena|     false|
|     19|      47|       Orlando Magic|         Amway Arena|     false|
|     19|      57|       Orlando Magic|        Amway Center|     false|
|     19|      80|       Orlando Magic|          Kia Center|      true|
|     13|      14|      Indiana Pacers| Market Square Arena|     false|
|     13|      43|      Indiana Pacers|Bankers Life Fiel...|     false|
|     13|      75|      Indiana Pacers|Gainbridge Fieldh...|     false|
|     15|       7|  Philadelphia 76ers|Core States Spect...|     false|
|     15|      40|  Philadelphia 76ers|     Wachovia Center|     false|
|     15|      56|  Philadelphia 76ers|  Wells Fargo Center|     false|
|     15|      83|  Philadelphia 76ers|Xfinity Mobile Arena|      true|
|     17|       2|        Phoenix Suns|   US Airways Center|     false|
|     17|      59|        Phoenix Suns|Talking Stick Res...|     false|
|     17|      70|        Phoenix Suns|  Phoenix Suns Arena|     false|
|     17|      73|        Phoenix Suns|    Footprint Center|     false|
|     17|      84|        Phoenix Suns|Mortgage Matchup ...|      true|
|     21|      22|Portland Trail Bl...|         Moda Center|      true|
|      5|       3|    Sacramento Kings|   Sleep Train Arena|     false|
|      5|      61|    Sacramento Kings|     Golden 1 Center|      true|
|      5|      85|    Sacramento Kings|          Tokyo Dome|     false|
|      8|       1|   San Antonio Spurs|           Alamodome|     false|
|      8|      51|   San Antonio Spurs|         AT&T Center|     false|
|      8|      79|   San Antonio Spurs|   Frost Bank Center|      true|
|     16|      30|Oklahoma City Thu...|            KeyArena|     false|
|     16|      74|Oklahoma City Thu...|       Paycom Center|      true|
|     16|      87|Oklahoma City Thu...|Chesapeake Energy...|     false|
|     16|      88|Oklahoma City Thu...| Saitama Super Arena|     false|
|     26|      24|     Toronto Raptors|             SkyDome|     false|
|     26|      31|     Toronto Raptors|   Maple Leaf Garden|     false|
|     26|      39|     Toronto Raptors|   Air Canada Centre|     false|
|     26|      64|     Toronto Raptors|    Scotiabank Arena|      true|
|     26|      68|     Toronto Raptors|        Amalie Arena|     false|
|     29|       8|           Utah Jazz|EnergySolutions A...|     false|
|     29|      60|           Utah Jazz|Vivint Smart Home...|     false|
|     29|      71|           Utah Jazz|        Vivint Arena|     false|
|     29|      78|           Utah Jazz|        Delta Center|      true|
|      1|      10|   Memphis Grizzlies|            GM Place|     false|
|      1|      20|   Memphis Grizzlies|             Pyramid|     false|
|      1|      54|   Memphis Grizzlies|          FedExForum|      true|
|     27|      32|  Washington Wizards|        US Air Arena|     false|
|     27|      34|  Washington Wizards|   Capital One Arena|      true|
|     20|      19|     Detroit Pistons|Palace of Auburn ...|     false|
|     20|      62|     Detroit Pistons|Little Caesars Arena|      true|
|     23|       5|   Charlotte Hornets|     Spectrum Center|      true|
+-------+--------+--------------------+--------------------+----------+

In [19]:
import pandas as pd
import json

In [28]:
with open("raw_data/arena_data/arena_combined.json") as f:
    data = json.load(f)

df = pd.DataFrame(data)

# Get distinct rows based on one column (keeps first occurrence, full row)
df_unique = df.drop_duplicates(subset=["arenaId", "team_id"])

In [22]:
df_unique

,gameId,arenaId,arenaName,arenaCity,arenaState,arenaCountry,arenaTimezone,team_id
0,0028500005,41,Omni,Atlanta,GA,US,Eastern,1610612737
1,0028500033,111,Boston Garden,Boston,MA,US,Eastern,1610612738
2,0028500016,22,Quicken Loans Arena,Cleveland,OH,US,Eastern,1610612739
3,0028500007,66,United Center,Chicago,IL,US,Central,1610612741
4,0028500017,49,Reunion Arena,Dallas,TX,US,Central,1610612742
...,...,...,...,...,...,...,...,...
1126,0022400071,1000137,Intuit Dome,Inglewood,CA,US,Pacific,1610612746
1133,0022400077,1000125,Kia Center,Orlando,FL,US,Eastern,1610612753
1149,0022500107,1000144,Rocket Arena,Cleveland,OH,US,Eastern,1610612739
1165,0022500102,1000152,Xfinity Mobile Arena,Philadelphia,PA,US,Eastern,1610612755
1166,0022500088,1000159,Mortgage Matchup Center,Phoenix,AZ,US,Mountain,1610612756

In [49]:
import pandas as pd
import json

In [57]:
with open("raw_data/games/games_2023-24_regular_log.json") as f:
    data = json.load(f)

df = pd.DataFrame(data["LeagueGameLog"])
df

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,...,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
0,22023,1610612743,DEN,Denver Nuggets,0022300061,2023-10-24,DEN vs. LAL,W,240,48,...,33,42,29,9,6,12,15,119,12,1
1,22023,1610612744,GSW,Golden State Warriors,0022300062,2023-10-24,GSW vs. PHX,L,240,36,...,31,49,19,11,6,11,23,104,-4,1
2,22023,1610612747,LAL,Los Angeles Lakers,0022300061,2023-10-24,LAL @ DEN,L,240,41,...,31,44,23,5,4,12,18,107,-12,1
3,22023,1610612756,PHX,Phoenix Suns,0022300062,2023-10-24,PHX @ GSW,W,240,42,...,43,60,23,5,7,19,22,108,4,1
4,22023,1610612740,NOP,New Orleans Pelicans,0022300071,2023-10-25,NOP @ MEM,W,240,40,...,41,52,22,8,5,21,21,111,7,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,22023,1610612760,OKC,Oklahoma City Thunder,0022301196,2024-04-14,OKC vs. DAL,W,240,54,...,47,58,38,6,6,15,17,135,49,1
2456,22023,1610612765,DET,Detroit Pistons,0022301197,2024-04-14,DET @ SAS,L,240,36,...,29,40,17,7,3,14,9,95,-28,1
2457,22023,1610612738,BOS,Boston Celtics,0022301186,2024-04-14,BOS vs. WAS,W,240,51,...,38,48,29,10,15,17,13,132,10,1
2458,22023,1610612743,DEN,Denver Nuggets,0022301193,2024-04-14,DEN @ MEM,W,240,46,...,38,54,32,9,5,18,17,126,15,1
2459,22023,1610612762,UTA,Utah Jazz,0022301198,2024-04-14,UTA @ GSW,L,240,46,...,34,48,22,6,5,20,20,116,-7,1

In [58]:
len(df["GAME_ID"].tolist())

2460

In [59]:
game_ids = df["GAME_ID"].unique().tolist()

In [60]:
game_ids[0]

'0022300061'

In [61]:
game_df = df[df["GAME_ID"] == game_ids[0]]
home_team = game_df[ game_df["MATCHUP"].str.contains("vs", case=False,na=False)]
home_team

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,...,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
0,22023,1610612743,DEN,Denver Nuggets,0022300061,2023-10-24,DEN vs. LAL,W,240,48,...,33,42,29,9,6,12,15,119,12,1

In [62]:
away_team = game_df[ game_df["MATCHUP"].str.contains("@", case=False,na=False)]
away_team

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,...,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
2,22023,1610612747,LAL,Los Angeles Lakers,0022300061,2023-10-24,LAL @ DEN,L,240,41,...,31,44,23,5,4,12,18,107,-12,1

In [64]:
df = pd.DataFrame(
    {
        "game_source_id": [away_team["GAME_ID"].iloc[0]],
        "season": ['2023-24'],
        "home_team": [home_team["TEAM_ID"].iloc[0]],
        "away_team": [away_team["TEAM_ID"].iloc[0]],
        "game_date": [home_team["GAME_DATE"].iloc[0]]
    }
)
df

  game_source_id   season   home_team   away_team   game_date
0     0022300061  2023-24  1610612743  1610612747  2023-10-24